import { cookies } from "next/headers";
import { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getPrisma } from "@/lib/prisma";
import type { StudentDirectoryRecord } from "@/lib/storage/studentDirectory";
import { compareResultStudentRolls } from "@/lib/resultStudentOrder";

type ResultStudent={studentId:string;rollNo?:string;failedSubjects?:string[]};
type ResultArchive={examYear:string;academicYear:string;students:ResultStudent[]};
type Publication={examType?:"Regular"|"Backlog";examYear:string;academicYear:string;published?:boolean};
type Syllabus={active?:boolean;courses:Array<{code:string;title:string;semester?:string}>};
type Course={courseCode:string;courseTitle:string;semester:"Odd"|"Even"};
type Candidate={studentId:string;studentName:string;rollNo:string;registrationNo:string;examYear:string;courses:Course[]};
type Registration=Candidate&{confirmedAt:string};
const SECTION="short-semester-registrations",norm=(value:string)=>value.replace(/\s/g,"").toLowerCase();
const schema=z.object({examYear:z.string().regex(/^\d{4}$/),selections:z.array(z.object({studentId:z.string().min(1),courseCodes:z.array(z.string().min(1)).max(100)})).max(1000)});
async function stored<T>(prisma:NonNullable<ReturnType<typeof getPrisma>>,section:string):Promise<T[]>{const rows=await prisma.$queryRaw<Array<{data:Prisma.JsonValue}>>(Prisma.sql`SELECT "data" FROM "ResultSectionStore" WHERE "section"=${section} LIMIT 1`);return Array.isArray(rows[0]?.data)?rows[0].data as unknown as T[]:[]}
async function teacher(){const prisma=getPrisma(),id=(await cookies()).get("becm-portal-account")?.value;if(!prisma||!id)return null;return await prisma.portalAccount.findFirst({where:{id,role:"teacher",active:true},select:{id:true}})?prisma:null}
async function candidates(prisma:NonNullable<ReturnType<typeof getPrisma>>):Promise<Candidate[]>{const[directory,results,publications,syllabuses]=await Promise.all([stored<StudentDirectoryRecord>(prisma,"student-directory"),stored<ResultArchive>(prisma,"result-sheet-backlog"),stored<Publication>(prisma,"add-viva-marks"),stored<Syllabus>(prisma,"syllabuses")]);const courseMap=new Map(syllabuses.filter(x=>x.active!==false).flatMap(x=>x.courses).map(course=>[norm(course.code),course]));const output:Candidate[]=[];for(const result of results.filter(x=>x.academicYear==="4th")){const published=publications.some(x=>(x.examType||"Regular")==="Backlog"&&x.examYear===result.examYear&&x.academicYear==="4th"&&x.published===true);if(!published)continue;for(const row of result.students){const failed=[...new Set(row.failedSubjects||[])];if(!failed.length)continue;const student=directory.find(x=>x.id===row.studentId||Boolean(row.rollNo)&&norm(x.rollNo)===norm(row.rollNo!));if(!student)continue;output.push({studentId:student.id,studentName:student.name,rollNo:student.rollNo,registrationNo:student.registrationNo,examYear:result.examYear,courses:failed.map(courseCode=>{const course=courseMap.get(norm(courseCode));return{courseCode,courseTitle:course?.title||courseCode,semester:course?.semester==="Even"?"Even":"Odd"}})})}}return output.sort((a,b)=>Number(b.examYear)-Number(a.examYear)||compareResultStudentRolls(a.rollNo,b.rollNo,a.examYear,"4th"))}
export async function GET(){const prisma=await teacher();if(!prisma)return NextResponse.json({error:"Teacher login required"},{status:401});try{return NextResponse.json({candidates:await candidates(prisma),registrations:await stored<Registration>(prisma,SECTION)},{headers:{"Cache-Control":"no-store"}})}catch(error){console.error("Unable to load short semester registrations",error);return NextResponse.json({error:"Unable to load short semester registrations"},{status:503})}}
export async function PUT(request:Request){const prisma=await teacher();if(!prisma)return NextResponse.json({error:"Teacher login required"},{status:401});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Invalid registration selection"},{status:400});try{const available=await candidates(prisma),registrations=await stored<Registration>(prisma,SECTION),now=new Date().toISOString();for(const selection of parsed.data.selections){const candidate=available.find(x=>x.examYear===parsed.data.examYear&&x.studentId===selection.studentId);if(!candidate)return NextResponse.json({error:"A selected student is not eligible for short semester registration."},{status:403});const allowed=new Map(candidate.courses.map(course=>[norm(course.courseCode),course])),courses=[...new Set(selection.courseCodes.map(norm))].map(code=>allowed.get(code)).filter((course):course is Course=>Boolean(course));if(courses.length!==new Set(selection.courseCodes.map(norm)).size)return NextResponse.json({error:"One or more selected subjects are not eligible."},{status:403});const record:Registration={...candidate,courses,confirmedAt:now},index=registrations.findIndex(x=>x.examYear===record.examYear&&x.studentId===record.studentId);if(courses.length){if(index<0)registrations.push(record);else registrations[index]=record}else if(index>=0)registrations.splice(index,1)}const serialized=JSON.stringify(registrations);await prisma.$executeRaw(Prisma.sql`INSERT INTO "ResultSectionStore"("section","data","updatedAt") VALUES(${SECTION},CAST(${serialized} AS jsonb),NOW()) ON CONFLICT("section") DO UPDATE SET "data"=EXCLUDED."data","updatedAt"=NOW()`);return NextResponse.json({registrations})}catch(error){console.error("Unable to save short semester registrations",error);return NextResponse.json({error:"Unable to save short semester registrations"},{status:503})}}