import { cookies } from "next/headers";
import { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getPrisma } from "@/lib/prisma";
import type { StudentDirectoryRecord } from "@/lib/storage/studentDirectory";

type Course = { courseCode:string; courseTitle:string; semester:"Odd"|"Even" };
type Registration = { studentId:string; studentName:string; rollNo:string; registrationNo:string; examYear:string; academicYear:string; courses:Course[]; confirmedAt:string };
type Archive = { examYear:string; academicYear:string; semester:string; students:Array<{studentId:string;rollNo?:string;failedSubjects:string[];registerAgain:string[]}> };
type ResultArchive = { examYear:string; academicYear:string; semester:string; students:Array<{studentId:string;rollNo?:string;failedSubjects:string[];registerAgain:string[]}> };
type Publication = { examType?:"Regular"|"Backlog"; examYear:string; academicYear:string; semester:string; published?:boolean };
type Syllabus = { active?:boolean; courses:Array<{code:string;title:string;semester?:string}> };
type Candidate = Omit<Registration,"courses"|"confirmedAt"> & { courses:Course[] };
const SECTION="backlog-registrations";
const requestSchema=z.object({examYear:z.string().regex(/^\d{4}$/),academicYear:z.enum(["1st","2nd","3rd","4th"]),selections:z.array(z.object({studentId:z.string().min(1),courses:z.array(z.object({courseCode:z.string().min(1),semester:z.enum(["Odd","Even"])})).max(30)})).max(1000)});
const yearNumber:Record<string,number>={"1st":1,"2nd":2,"3rd":3,"4th":4};
const normalized=(value:string)=>value.replace(/\s/g,"").toLowerCase();
const backlogResultPublished=(publications:Publication[],examYear:string,academicYear:string)=>publications.some(result=>result.examType==="Backlog"&&result.examYear===examYear&&result.academicYear===academicYear&&result.published===true);
async function stored<T>(prisma:NonNullable<ReturnType<typeof getPrisma>>,section:string):Promise<T[]>{const rows=await prisma.$queryRaw<Array<{data:Prisma.JsonValue}>>(Prisma.sql`SELECT "data" FROM "ResultSectionStore" WHERE "section"=${section} LIMIT 1`);return Array.isArray(rows[0]?.data)?rows[0].data as unknown as T[]:[]}
async function teacher(){const prisma=getPrisma(),id=(await cookies()).get("becm-portal-account")?.value;if(!prisma||!id)return null;const account=await prisma.portalAccount.findFirst({where:{id,role:"teacher",active:true},select:{id:true}});return account?prisma:null}
async function candidates(prisma:NonNullable<ReturnType<typeof getPrisma>>):Promise<Candidate[]>{
 const[directory,archives,resultArchives,syllabuses,publications]=await Promise.all([stored<StudentDirectoryRecord>(prisma,"student-directory"),stored<Archive>(prisma,"marks-sheet"),stored<ResultArchive>(prisma,"result-sheet"),stored<Syllabus>(prisma,"syllabuses"),stored<Publication>(prisma,"add-viva-marks")]);
 const syllabusCourses=syllabuses.filter(item=>item.active!==false).flatMap(item=>item.courses),titles=new Map(syllabusCourses.map(course=>[normalized(course.code),course.title])),semesters=new Map(syllabusCourses.map(course=>[normalized(course.code),course.semester==="Even"?"Even" as const:"Odd" as const]));const output:Candidate[]=[];
 for(const evenArchive of archives.filter(archive=>archive.semester==="Even")){
  const examYear=evenArchive.examYear,academicYear=evenArchive.academicYear;
  if(backlogResultPublished(publications,examYear,academicYear))continue;
  const published=(semester:"Odd"|"Even")=>publications.some(result=>(result.examType||"Regular")==="Regular"&&result.examYear===examYear&&result.academicYear===academicYear&&result.semester===semester&&result.published===true);
  if(!published("Odd")||!published("Even"))continue;
  const oddArchive=archives.find(archive=>archive.examYear===examYear&&archive.academicYear===academicYear&&archive.semester==="Odd"),archivedStudents=[...new Map([...(oddArchive?.students||[]),...evenArchive.students].map(student=>[student.studentId,student])).values()];
  for(const archivedStudent of archivedStudents){const student=directory.find(candidate=>candidate.id===archivedStudent.studentId||Boolean(archivedStudent.rollNo)&&normalized(candidate.rollNo)===normalized(archivedStudent.rollNo!));if(!student)continue;
   const cumulativeResult=academicYear==="4th"?resultArchives.find(archive=>archive.examYear===examYear&&archive.academicYear==="4th"&&archive.semester==="Even")?.students.find(row=>row.studentId===archivedStudent.studentId||Boolean(row.rollNo)&&normalized(row.rollNo!)===normalized(student.rollNo)):undefined;
   const courses=cumulativeResult?[...new Set([...(cumulativeResult.failedSubjects||[]),...(cumulativeResult.registerAgain||[])])].map(courseCode=>({courseCode,courseTitle:titles.get(normalized(courseCode))||courseCode,semester:semesters.get(normalized(courseCode))||"Odd" as "Odd"|"Even"})):([oddArchive,evenArchive]as const).flatMap(archive=>{if(!archive)return[];const result=archive.students.find(row=>row.studentId===archivedStudent.studentId||Boolean(row.rollNo)&&normalized(row.rollNo!)===normalized(student.rollNo));return[...new Set([...(result?.failedSubjects||[]),...(result?.registerAgain||[])])].map(courseCode=>({courseCode,courseTitle:titles.get(normalized(courseCode))||courseCode,semester:archive.semester as "Odd"|"Even"}))});
   const unique=[...new Map(courses.map(course=>[`${course.semester}|${normalized(course.courseCode)}`,course])).values()];if(unique.length)output.push({studentId:student.id,studentName:student.name,rollNo:student.rollNo,registrationNo:student.registrationNo,examYear,academicYear,courses:unique});
  }
 } const seriesByStudent=new Map(directory.map(student=>[student.id,student.series]));return output.sort((a,b)=>{const expectedA=String(Number(a.examYear)-(yearNumber[a.academicYear]||1)),expectedB=String(Number(b.examYear)-(yearNumber[b.academicYear]||1)),groupA=seriesByStudent.get(a.studentId)===expectedA?0:1,groupB=seriesByStudent.get(b.studentId)===expectedB?0:1;return groupA-groupB||Number(seriesByStudent.get(b.studentId)||0)-Number(seriesByStudent.get(a.studentId)||0)||a.rollNo.localeCompare(b.rollNo,undefined,{numeric:true})});
}export async function GET(){const prisma=await teacher();if(!prisma)return NextResponse.json({error:"Teacher login required"},{status:401});try{return NextResponse.json({candidates:await candidates(prisma),registrations:await stored<Registration>(prisma,SECTION)},{headers:{"Cache-Control":"no-store"}})}catch(error){console.error("Unable to load backlog registrations",error);return NextResponse.json({error:"Unable to load backlog registrations"},{status:503})}}
export async function PUT(request:Request){const prisma=await teacher();if(!prisma)return NextResponse.json({error:"Teacher login required"},{status:401});const parsed=requestSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Invalid backlog selection"},{status:400});try{const available=await candidates(prisma),registrations=await stored<Registration>(prisma,SECTION),now=new Date().toISOString();for(const selection of parsed.data.selections){const candidate=available.find(item=>item.studentId===selection.studentId&&item.examYear===parsed.data.examYear&&item.academicYear===parsed.data.academicYear);if(!candidate)return NextResponse.json({error:"A selected student is not eligible for this backlog examination."},{status:403});const allowed=new Map(candidate.courses.map(course=>[`${course.semester}|${normalized(course.courseCode)}`,course]));const courses=selection.courses.map(course=>allowed.get(`${course.semester}|${normalized(course.courseCode)}`)).filter((course):course is Course=>Boolean(course));if(courses.length!==selection.courses.length)return NextResponse.json({error:"One or more selected subjects are not eligible."},{status:403});const record:Registration={studentId:candidate.studentId,studentName:candidate.studentName,rollNo:candidate.rollNo,registrationNo:candidate.registrationNo,examYear:parsed.data.examYear,academicYear:parsed.data.academicYear,courses,confirmedAt:now};const index=registrations.findIndex(item=>item.studentId===record.studentId&&item.examYear===record.examYear&&item.academicYear===record.academicYear);if(courses.length){if(index<0)registrations.push(record);else registrations[index]=record}else if(index>=0)registrations.splice(index,1)}const serialized=JSON.stringify(registrations);await prisma.$executeRaw(Prisma.sql`INSERT INTO "ResultSectionStore"("section","data","updatedAt") VALUES(${SECTION},CAST(${serialized} AS jsonb),NOW()) ON CONFLICT("section") DO UPDATE SET "data"=EXCLUDED."data","updatedAt"=NOW()`);return NextResponse.json({registrations})}catch(error){console.error("Unable to save backlog registrations",error);return NextResponse.json({error:"Unable to save backlog registrations"},{status:503})}}
