import { promotedBacklogCourses } from "@/lib/promotedBacklogCourses";
import { cookies } from "next/headers";
import { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getPrisma } from "@/lib/prisma";
import type { OldStudentRecord, StudentDirectoryRecord } from "@/lib/storage/studentDirectory";

type Course = { courseId?:string; courseCode:string; courseTitle:string; semester:"Odd"|"Even" };
type Registration = { studentId:string; studentName:string; rollNo:string; registrationNo:string; series?:string; specialStudent?:boolean; examYear:string; academicYear:string; courses:Course[]; confirmedAt:string };
type Archive = { examYear:string; academicYear:string; semester:string; students:Array<{studentId:string;rollNo?:string;failedSubjects:string[];registerAgain:string[]}> };
type ResultArchive = { examYear:string; academicYear:string; semester:string; students:Array<{studentId:string;rollNo?:string;failedSubjects:string[];registerAgain:string[]}> };
type Publication = { examType?:"Regular"|"Backlog"; examYear:string; academicYear:string; semester:string; published?:boolean; students?:Array<{id:string;rollNo?:string;marks?:string;present?:boolean}> };
type Prepared = { examYear:string; academicYear:string; semester:string; courseId:string; students:Array<{studentId:string;rollNo?:string;present?:boolean;withheld?:boolean;partA?:string;partB?:string;classTestAttendance?:string;sessional?:string;internal?:string;external?:string;thesisViva?:string}> };
type Eligibility = { examYear:string; academicYear:string; semester:string; courseId:string; students:Array<{studentId:string;eligible:boolean}> };
type Syllabus = { active?:boolean; fromSeries?:string; toSeries?:string; courses:Array<{id:string;code:string;title:string;type?:string;year?:string;semester?:string}> };
type Candidate = Omit<Registration,"courses"|"confirmedAt"|"series"|"specialStudent"> & { series:string; specialStudent:boolean; courses:Course[] };
const SECTION="backlog-registrations";
const requestSchema=z.object({examYear:z.string().regex(/^\d{4}$/),academicYear:z.enum(["1st","2nd","3rd","4th"]),selections:z.array(z.object({studentId:z.string().min(1),courses:z.array(z.object({courseCode:z.string().min(1),semester:z.enum(["Odd","Even"])})).max(30)})).max(1000)});
const yearNumber:Record<string,number>={"1st":1,"2nd":2,"3rd":3,"4th":4};
const normalized=(value:string)=>value.replace(/\s/g,"").toLowerCase();
const backlogResultPublished=(publications:Publication[],examYear:string,academicYear:string)=>publications.some(result=>result.examType==="Backlog"&&result.examYear===examYear&&result.academicYear===academicYear&&result.published===true);
async function stored<T>(prisma:NonNullable<ReturnType<typeof getPrisma>>,section:string):Promise<T[]>{const rows=await prisma.$queryRaw<Array<{data:Prisma.JsonValue}>>(Prisma.sql`SELECT "data" FROM "ResultSectionStore" WHERE "section"=${section} LIMIT 1`);return Array.isArray(rows[0]?.data)?rows[0].data as unknown as T[]:[]}
async function teacher(){const prisma=getPrisma(),id=(await cookies()).get("becm-portal-account")?.value;if(!prisma||!id)return null;const account=await prisma.portalAccount.findFirst({where:{id,role:"teacher",active:true},select:{id:true}});return account?prisma:null}
async function candidates(prisma:NonNullable<ReturnType<typeof getPrisma>>):Promise<Candidate[]>{
 const[directory,oldStudents,archives,resultArchives,prepared,eligibility,syllabuses,publications]=await Promise.all([stored<StudentDirectoryRecord>(prisma,"student-directory"),stored<OldStudentRecord>(prisma,"old-student-directory"),stored<Archive>(prisma,"marks-sheet"),stored<ResultArchive>(prisma,"result-sheet"),stored<Prepared>(prisma,"prepare-result"),stored<Eligibility>(prisma,"student-eligibility"),stored<Syllabus>(prisma,"syllabuses"),stored<Publication>(prisma,"add-viva-marks")]);
 const syllabusCourses=syllabuses.filter(item=>item.active!==false).flatMap(item=>item.courses),courseById=new Map(syllabusCourses.map(course=>[course.id,course])),summaryArchives:Archive[]=[...archives];for(const resultArchive of resultArchives){const index=summaryArchives.findIndex(archive=>archive.examYear===resultArchive.examYear&&archive.academicYear===resultArchive.academicYear&&archive.semester===resultArchive.semester);if(index<0)summaryArchives.push(resultArchive);else summaryArchives[index]=resultArchive}const output:Candidate[]=[];
 for(const evenArchive of summaryArchives.filter(archive=>archive.semester==="Even")){
  const examYear=evenArchive.examYear,academicYear=evenArchive.academicYear;
  if(backlogResultPublished(publications,examYear,academicYear))continue;
  const published=(semester:"Odd"|"Even")=>publications.some(result=>(result.examType||"Regular")==="Regular"&&result.examYear===examYear&&result.academicYear===academicYear&&result.semester===semester&&result.published===true);
  if(!published("Odd")||!published("Even"))continue;
  const oddArchive=summaryArchives.find(archive=>archive.examYear===examYear&&archive.academicYear===academicYear&&archive.semester==="Odd");if(!oddArchive)continue;const examPrepared=prepared.filter(record=>record.examYear===examYear&&record.academicYear===academicYear&&(record.semester==="Odd"||record.semester==="Even")),archivedStudents=[...new Map(examPrepared.flatMap(record=>record.students).map(row=>[normalized(row.rollNo||row.studentId),row])).values()];
  for(const archivedStudent of archivedStudents){const currentStudent=directory.find(candidate=>candidate.id===archivedStudent.studentId||Boolean(archivedStudent.rollNo)&&normalized(candidate.rollNo)===normalized(archivedStudent.rollNo!)),oldStudent=oldStudents.find(candidate=>candidate.id===archivedStudent.studentId||Boolean(archivedStudent.rollNo)&&normalized(candidate.rollNo)===normalized(archivedStudent.rollNo!)),student=currentStudent||oldStudent,expectedSeries=String(Number(examYear)-(yearNumber[academicYear]||1));if(!student)continue;
   const regularPromotion=oldStudent?.promotions.some(promotion=>promotion.examType==="Regular"&&promotion.examYear===examYear&&promotion.academicYear===academicYear&&(promotion.semester==="Odd"||promotion.semester==="Even")),backlogPromotion=oldStudent?.promotions.find(promotion=>promotion.examType==="Backlog"&&promotion.examYear===examYear&&promotion.academicYear===academicYear),obeSpecial=Boolean(currentStudent?.obeBatchPlacements?.length)||(oldStudent?Number(oldStudent.series)>=2020:false),normalSeries=student.series===expectedSeries;
   if(!normalSeries&&!obeSpecial&&!backlogPromotion)continue;if(oldStudent&&Number(oldStudent.series)<2020&&(!regularPromotion||!backlogPromotion))continue;
   const sameStudent=(row:{studentId:string;rollNo?:string})=>row.studentId===archivedStudent.studentId||row.studentId===student.id||Boolean(row.rollNo)&&normalized(row.rollNo!)===normalized(student.rollNo),numberValue=(value?:string)=>Number(value)||0,preparedFailed=examPrepared.flatMap(record=>{const syllabusCourse=courseById.get(record.courseId),mark=record.students.find(sameStudent),nonEligible=eligibility.find(item=>item.examYear===examYear&&item.academicYear===academicYear&&item.semester===record.semester&&item.courseId===record.courseId)?.students.some(item=>item.studentId===mark?.studentId&&item.eligible===false);if(!syllabusCourse||!mark||nonEligible||(academicYear!=="4th"&&syllabusCourse.year!==academicYear))return[];const theory=syllabusCourse.type==="Theory",thesis=syllabusCourse.type==="Thesis",viva=publications.find(item=>(item.examType||"Regular")==="Regular"&&item.examYear===examYear&&item.academicYear===academicYear&&item.semester===record.semester)?.students?.find(item=>item.id===student.id||Boolean(item.rollNo)&&normalized(item.rollNo!)===normalized(student.rollNo)),vivaMark=viva?.present===false?0:numberValue(viva?.marks),score=Math.round(theory?(mark.present===false?0:numberValue(mark.partA)+numberValue(mark.partB))+numberValue(mark.classTestAttendance):thesis?numberValue(mark.internal)+numberValue(mark.external)+numberValue(mark.thesisViva):numberValue(mark.sessional)+vivaMark),failed=Boolean(mark.withheld)||mark.present===false||(theory&&numberValue(mark.partA)+numberValue(mark.partB)<15)||(!theory&&!thesis&&vivaMark<=0)||score<40;return failed?[syllabusCourse]:[]}),statusCourses=(oldStudent?.outstandingCourses||[]).filter(item=>item.status==="failed").map(item=>courseById.get(item.courseId)).filter((course):course is NonNullable<typeof course>=>Boolean(course)),allowedPromotionIds=backlogPromotion?new Set(backlogPromotion.courseIds):undefined;
   const archivedFailedCourses=(evenArchive.students.find(sameStudent)?.failedSubjects||[]).flatMap(code=>{const course=syllabusCourses.find(item=>normalized(item.code)===normalized(code)&&item.semester!=="Short Semester"&&(academicYear==="4th"||item.year===academicYear)&&syllabuses.some(segment=>segment.courses.some(candidate=>candidate.id===item.id)&&Number(student.series)>=Number(segment.fromSeries||0)&&Number(student.series)<=Number(segment.toSeries||9999)));return course?[course]:[]});
   const courses=[...preparedFailed,...statusCourses,...archivedFailedCourses].flatMap(syllabusCourse=>{if((academicYear!=="4th"&&syllabusCourse.year!==academicYear))return[];if(oldStudent&&Number(oldStudent.series)<2020&&(!allowedPromotionIds||!allowedPromotionIds.has(syllabusCourse.id)))return[];return[{courseId:syllabusCourse.id,courseCode:syllabusCourse.code,courseTitle:syllabusCourse.title,semester:syllabusCourse.semester==="Even"?"Even" as const:"Odd" as const}]});
   const unique=[...new Map(courses.map(course=>[`${course.semester}|${normalized(course.courseCode)}`,course])).values()];if(unique.length)output.push({studentId:student.id,studentName:student.name,rollNo:student.rollNo,registrationNo:student.registrationNo,series:student.series,specialStudent:obeSpecial,examYear,academicYear,courses:unique});
  }
}
 for(const student of oldStudents)for(const promotion of student.promotions){
  if(promotion.examType!=="Backlog"||backlogResultPublished(publications,promotion.examYear,promotion.academicYear))continue;
  const courses=promotedBacklogCourses(promotion.courseIds,syllabuses);
  const candidate:Candidate={studentId:student.id,studentName:student.name,rollNo:student.rollNo,registrationNo:student.registrationNo,series:student.series,specialStudent:true,examYear:promotion.examYear,academicYear:promotion.academicYear,courses};
  const index=output.findIndex(item=>item.studentId===student.id&&item.examYear===promotion.examYear&&item.academicYear===promotion.academicYear);
  if(courses.length){if(index<0)output.push(candidate);else output[index]=candidate}
 }
 return output.sort((a,b)=>a.rollNo.localeCompare(b.rollNo,undefined,{numeric:true}));
}export async function GET(){const prisma=await teacher();if(!prisma)return NextResponse.json({error:"Teacher login required"},{status:401});try{return NextResponse.json({candidates:await candidates(prisma),registrations:await stored<Registration>(prisma,SECTION)},{headers:{"Cache-Control":"no-store"}})}catch(error){console.error("Unable to load backlog registrations",error);return NextResponse.json({error:"Unable to load backlog registrations"},{status:503})}}
export async function PUT(request:Request){const prisma=await teacher();if(!prisma)return NextResponse.json({error:"Teacher login required"},{status:401});const parsed=requestSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Invalid backlog selection"},{status:400});try{const available=await candidates(prisma),registrations=await stored<Registration>(prisma,SECTION),now=new Date().toISOString();for(const selection of parsed.data.selections){const candidate=available.find(item=>item.studentId===selection.studentId&&item.examYear===parsed.data.examYear&&item.academicYear===parsed.data.academicYear);if(!candidate)return NextResponse.json({error:"A selected student is not eligible for this backlog examination."},{status:403});const allowed=new Map(candidate.courses.map(course=>[`${course.semester}|${normalized(course.courseCode)}`,course]));const courses=selection.courses.map(course=>allowed.get(`${course.semester}|${normalized(course.courseCode)}`)).filter((course):course is Course=>Boolean(course));if(courses.length!==selection.courses.length)return NextResponse.json({error:"One or more selected subjects are not eligible."},{status:403});const record:Registration={studentId:candidate.studentId,studentName:candidate.studentName,rollNo:candidate.rollNo,registrationNo:candidate.registrationNo,series:candidate.series,specialStudent:candidate.specialStudent,examYear:parsed.data.examYear,academicYear:parsed.data.academicYear,courses,confirmedAt:now};const index=registrations.findIndex(item=>item.studentId===record.studentId&&item.examYear===record.examYear&&item.academicYear===record.academicYear);if(courses.length){if(index<0)registrations.push(record);else registrations[index]=record}else if(index>=0)registrations.splice(index,1)}const serialized=JSON.stringify(registrations);await prisma.$executeRaw(Prisma.sql`INSERT INTO "ResultSectionStore"("section","data","updatedAt") VALUES(${SECTION},CAST(${serialized} AS jsonb),NOW()) ON CONFLICT("section") DO UPDATE SET "data"=EXCLUDED."data","updatedAt"=NOW()`);return NextResponse.json({registrations})}catch(error){console.error("Unable to save backlog registrations",error);return NextResponse.json({error:"Unable to save backlog registrations"},{status:503})}}
