export type SyllabusCourse = { id: string; title: string; code: string; credit: string; type: "Theory" | "Sessional" | "Thesis"; department: string; year: "1st" | "2nd" | "3rd" | "4th"; semester: "Odd" | "Even" | "Short Semester" };
export type SyllabusSegment = { id: string; name: string; fromSeries: string; toSeries: string; courses: SyllabusCourse[] };

export function syllabusCoursesForExam(
  syllabuses: SyllabusSegment[],
  series: string,
  year: SyllabusCourse["year"],
  semester: SyllabusCourse["semester"],
) {
  const matchingSegments = syllabuses
    .filter((segment) => Number(series) >= Number(segment.fromSeries) && Number(series) <= Number(segment.toSeries))
    .sort((left, right) => (Number(left.toSeries) - Number(left.fromSeries)) - (Number(right.toSeries) - Number(right.fromSeries)));

  const courses = matchingSegments.flatMap((segment) =>
    segment.courses.filter((course) => course.year === year && course.semester === semester),
  );

  return Array.from(new Map(courses.map((course) => [course.id, course])).values());
}

type SeedRow = [string, string, string, SyllabusCourse["type"], SyllabusCourse["year"], SyllabusCourse["semester"]];
const rows: SeedRow[] = [
["Surveying","CE 1125","3.00","Theory","1st","Odd"],["Chemistry","Chem 1107","3.00","Theory","1st","Odd"],["Physics - I","Phy 1107","3.00","Theory","1st","Odd"],["Mathematics - I","Math 1107","3.00","Theory","1st","Odd"],["Basic Electrical Engineering","EEE 1147","3.00","Theory","1st","Odd"],["Graphics and Basic Engineering Drawing","BECM 1100","1.50","Sessional","1st","Odd"],["Wood and Sheet Metal Shop","BECM 1102","1.50","Sessional","1st","Odd"],["Sessional on Physics","Phy 1108","1.50","Sessional","1st","Odd"],["Sessional on Basic Electrical Engineering","EEE 1148","1.50","Sessional","1st","Odd"],["Engineering Mechanics","BECM 1223","3.00","Theory","1st","Even"],
["Building and Construction Materials","BECM 1201","3.00","Theory","1st","Even"],["Physics-II","Phy 1207","3.00","Theory","1st","Even"],["Mathematics-II","Math 1207","3.00","Theory","1st","Even"],["English","Hum 1205","2.00","Theory","1st","Even"],["Sessional on Building and Construction Materials","BECM 1202","1.50","Sessional","1st","Even"],["English Skill Practices","Hum 1206","1.50","Sessional","1st","Even"],["Practical Surveying","CE 1226","1.50","Sessional","1st","Even"],["Sessional on Chemistry","Chem 1208","1.50","Sessional","1st","Even"],["Building Engineering Systems","BECM 2101","3.00","Theory","2nd","Odd"],["Aesthetics and Design","BECM 2131","3.00","Theory","2nd","Odd"],
["Mechanics of Materials-I","BECM 2125","3.00","Theory","2nd","Odd"],["Mathematics-III","Math 2107","3.00","Theory","2nd","Odd"],["Engineering Economics and Financial Accounting","Hum 2109","3.00","Theory","2nd","Odd"],["Construction Estimating Sessional","BECM 2100","1.50","Sessional","2nd","Odd"],["Architectural Design Sessional-I","BECM 2132","1.50","Sessional","2nd","Odd"],["Construction Technique and Equipment Sessional-I","BECM 2104","1.50","Sessional","2nd","Odd"],["Numerical Analysis and Computer Programming","BECM 2203","3.00","Theory","2nd","Even"],["Mechanics of Materials-II","BECM 2225","3.00","Theory","2nd","Even"],["Climate and Architectural Design","BECM 2231","2.00","Theory","2nd","Even"],["Mathematics-IV","Math 2207","3.00","Theory","2nd","Even"],
["Sociology and Government","Hum 2209","3.00","Theory","2nd","Even"],["Mechanics of Materials Sessional","BECM 2226","1.50","Sessional","2nd","Even"],["Architectural Design Sessional-II","BECM 2232","1.50","Sessional","2nd","Even"],["Computer Application and Programming Sessional","BECM 2204","1.50","Sessional","2nd","Even"],["Construction Techniques and Equipment Sessional-II","BECM 2202","1.50","Sessional","2nd","Even"],["Construction and Project Management-I","BECM 3111","3.00","Theory","3rd","Odd"],["Construction Contract and Law","BECM 3113","3.00","Theory","3rd","Odd"],["Structural Analysis and Design-I","BECM 3171","3.00","Theory","3rd","Odd"],["Reinforced Concrete Structures-I","BECM 3173","3.00","Theory","3rd","Odd"],["Geotechnical Engineering-I","BECM 3141","3.00","Theory","3rd","Odd"],
["Geotechnical Engineering Sessional-I","BECM 3142","1.50","Sessional","3rd","Odd"],["Landscape Design Sessional","BECM 3132","1.50","Sessional","3rd","Odd"],["Architectural Design of High Rise Building Sessional","BECM 3134","1.50","Sessional","3rd","Odd"],["Construction and Project Management-II","BECM 3211","3.00","Theory","3rd","Even"],["Structural Analysis and Design-II","BECM 3271","3.00","Theory","3rd","Even"],["Reinforced Concrete Structures-II","BECM 3273","3.00","Theory","3rd","Even"],["Acoustics and Lighting","BECM 3231","3.00","Theory","3rd","Even"],["Geotechnical Engineering-II","BECM 3241","3.00","Theory","3rd","Even"],["Structural Analysis and Design Sessional","BECM 3270","1.50","Sessional","3rd","Even"],["Research Methodology Sessional","BECM 3202","1.50","Sessional","3rd","Even"],
["Building Project Management Sessional","BECM 3210","1.50","Sessional","3rd","Even"],["Geotechnical Engineering Sessional-II","BECM 3242","1.50","Sessional","3rd","Even"],["Sustainable Materials and Green Buildings","BECM 4101","3.00","Theory","4th","Odd"],["Project Financing and Construction Marketing","BECM 4111","2.00","Theory","4th","Odd"],["Health and Safety in Construction","BECM 4115","3.00","Theory","4th","Odd"],["Foundation Engineering","BECM 4141","3.00","Theory","4th","Odd"],["Basic Environmental Engineering","CE 4103","3.00","Theory","4th","Odd"],["Undergraduate Thesis","BECM 4000","1.50","Thesis","4th","Odd"],["Working Drawing Sessional","BECM 4132","1.50","Sessional","4th","Odd"],["Computer Aided Analysis and Design of Tall Building Sessional","BECM 4170","1.50","Sessional","4th","Odd"],
["Interior Design Sessional","BECM 4130","1.50","Sessional","4th","Odd"],["Professional Training","BECM 4100","1.50","Sessional","4th","Odd"],["Transportation Engineering in Construction","CE 4201","3.00","Theory","4th","Even"],["Quality Management in Construction","BECM 4211","2.00","Theory","4th","Even"],["Design of Steel Structures and Prestressed Concrete","BECM 4271","3.00","Theory","4th","Even"],["Earthquake Analysis and Design","BECM 4273","2.00","Theory","4th","Even"],["Finite Element Method","BECM 4227","2.00","Theory","4th","Even"],["Professional Practices and Communication Sessional","BECM 4200","1.50","Sessional","4th","Even"],["Foundation Engineering Sessional","BECM 4242","1.50","Sessional","4th","Even"],["Structural Health Monitoring Sessional","BECM 4276","1.50","Sessional","4th","Even"],
["Building Information Modelling Sessional","BECM 4214","1.50","Sessional","4th","Even"],["Undergraduate Thesis","BECM 4000","3.00","Thesis","4th","Even"]
];
export const defaultSyllabuses: SyllabusSegment[] = [{ id: "syllabus-2020-2024", name: "BECM Syllabus 2020-2024", fromSeries: "2020", toSeries: "2024", courses: rows.map(([title,code,credit,type,year,semester], index) => ({ id: `course-${index + 1}`, title, code, credit, type, department: "BECM", year, semester })) }];
