import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getPrisma } from "@/lib/prisma";
import { hashStudentServiceCode, type StudentService } from "@/lib/studentServiceVerification";
const itemSchema=z.enum(["lab-report","association-fee","letter-attestation","equivalent-certificate"]);
const verifySchema=z.object({item:itemSchema,code:z.string().regex(/^\d{6}$/)});
const whereFor=(item:StudentService)=>item==="lab-report"?{labReportOption:{not:"none"}}:item==="association-fee"?{associationYear:{gt:0}}:item==="letter-attestation"?{letterOfAttestation:true}:{equivalentCertificate:true};
async function staffPrisma(){const prisma=getPrisma();if(!prisma)return null;const id=(await cookies()).get("becm-portal-account")?.value;if(!id)return null;const rows=await prisma.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "PortalAccount" WHERE "id"=${id} AND "role"='staff' AND "active"=true LIMIT 1`;return rows.length?prisma:null;}
export async function GET(request:Request){const prisma=await staffPrisma();if(!prisma)return NextResponse.json({error:"Active staff login required"},{status:401});const item=itemSchema.safeParse(new URL(request.url).searchParams.get("item"));if(!item.success)return NextResponse.json({error:"Invalid payment item"},{status:400});const payments=await prisma.studentBillPayment.findMany({where:whereFor(item.data),orderBy:{createdAt:"desc"}});const emails=[...new Set(payments.map(p=>p.email.toLowerCase()))];const profiles=emails.length?await prisma.studentProfile.findMany({where:{email:{in:emails}},select:{email:true,roll:true,series:true,department:true}}):[];const verifications=await prisma.$queryRaw<Array<{paymentId:string;verifiedAt:Date|null}>>`SELECT "paymentId","verifiedAt" FROM "StudentServiceVerification" WHERE "service"=${item.data}`;const profileMap=new Map(profiles.map(p=>[p.email.toLowerCase(),p]));const verificationMap=new Map(verifications.map(v=>[v.paymentId,v.verifiedAt]));return NextResponse.json({payments:payments.map(p=>({...p,profile:profileMap.get(p.email.toLowerCase())||null,verifiedAt:verificationMap.get(p.id)||null}))});}
export async function POST(request:Request){const prisma=await staffPrisma();if(!prisma)return NextResponse.json({error:"Active staff login required"},{status:401});const parsed=verifySchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Enter a valid six-digit verification code"},{status:400});const codeHash=hashStudentServiceCode(parsed.data.item,parsed.data.code);const used=await prisma.$queryRaw<Array<{paymentId:string;verifiedAt:Date}>>`UPDATE "StudentServiceVerification" SET "verifiedAt"=NOW(),"updatedAt"=NOW() WHERE "service"=${parsed.data.item} AND "codeHash"=${codeHash} AND "verifiedAt" IS NULL RETURNING "paymentId","verifiedAt"`;if(!used.length)return NextResponse.json({error:"Invalid or already used verification code"},{status:409});const payment=await prisma.studentBillPayment.findUnique({where:{id:used[0].paymentId}});if(!payment)return NextResponse.json({error:"Payment record was not found"},{status:404});const profile=await prisma.studentProfile.findUnique({where:{email:payment.email.toLowerCase()}});return NextResponse.json({verified:true,verifiedAt:used[0].verifiedAt,payment,profile});}