import { cookies } from "next/headers";
import { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getPrisma } from "@/lib/prisma";
import type { OldStudentRecord } from "@/lib/storage/studentDirectory";
const SECTION="old-student-directory";
const course=z.object({courseId:z.string().min(1),status:z.enum(["failed","need-register"])});
const promotion=z.object({id:z.string().min(1),examYear:z.string().regex(/^\d{4}$/),academicYear:z.enum(["1st","2nd","3rd","4th"]),semester:z.enum(["Odd","Even","Short Semester","Backlog"]),examType:z.enum(["Regular","Backlog"]),courseIds:z.array(z.string().min(1)).min(1),promotedAt:z.string().datetime()});
const record=z.object({id:z.string().min(1),department:z.string().min(1),series:z.string().regex(/^(?:201[6-9]|202[0-4])$/),section:z.enum(["A","B"]),name:z.string().trim().min(2),rollNo:z.string().trim().min(1),registrationNo:z.string().trim().min(1),fatherName:z.string(),motherName:z.string(),localGuardian:z.string(),gender:z.enum(["Male","Female","Other"]),birthDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),earnedCredit:z.number().min(0).max(250),gradePoints:z.number().min(0).max(1000),outstandingCourses:z.array(course).max(500),promotions:z.array(promotion),createdAt:z.string().datetime(),updatedAt:z.string().datetime()});
async function access(){const id=(await cookies()).get("becm-portal-account")?.value,p=getPrisma();if(!id||!p)return null;return await p.portalAccount.findFirst({where:{id,role:"teacher",active:true},select:{id:true}})?p:null}
async function load(p:NonNullable<ReturnType<typeof getPrisma>>){await p.$executeRaw(Prisma.sql`INSERT INTO "ResultSectionStore" ("section","data","updatedAt") VALUES (${SECTION},'[]'::jsonb,NOW()) ON CONFLICT ("section") DO NOTHING`);const r=await p.$queryRaw<Array<{data:Prisma.JsonValue}>>(Prisma.sql`SELECT "data" FROM "ResultSectionStore" WHERE "section"=${SECTION} LIMIT 1`);return Array.isArray(r[0]?.data)?r[0].data as unknown as OldStudentRecord[]:[]}
async function save(p:NonNullable<ReturnType<typeof getPrisma>>,records:OldStudentRecord[]){await p.$executeRaw(Prisma.sql`UPDATE "ResultSectionStore" SET "data"=CAST(${JSON.stringify(records)} AS jsonb),"updatedAt"=NOW() WHERE "section"=${SECTION}`)}
export async function GET(){const p=await access();if(!p)return NextResponse.json({error:"Teacher login required"},{status:401});try{return NextResponse.json({records:await load(p)},{headers:{"Cache-Control":"no-store"}})}catch(e){console.error(e);return NextResponse.json({error:"Unable to load Non-OBE students"},{status:503})}}
export async function PUT(request:Request){const p=await access();if(!p)return NextResponse.json({error:"Teacher login required"},{status:401});const parsed=record.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Invalid old student data"},{status:400});const item=parsed.data as OldStudentRecord,status=new Map(item.outstandingCourses.map(c=>[c.courseId,c.status]));if(item.promotions.some(x=>x.examType==="Backlog"&&x.courseIds.some(id=>status.get(id)==="need-register")))return NextResponse.json({error:"Need-to-register courses cannot be selected for a backlog examination"},{status:400});try{const current=await load(p),duplicate=current.find(x=>x.id!==item.id&&(x.rollNo===item.rollNo||x.registrationNo===item.registrationNo));if(duplicate)return NextResponse.json({error:"Roll or registration number already exists"},{status:409});const next=[...current.filter(x=>x.id!==item.id),item];await save(p,next);return NextResponse.json({records:next,record:item})}catch(e){console.error(e);return NextResponse.json({error:"Unable to save Non-OBE student"},{status:503})}}
export async function DELETE(request:Request){
 const p=await access();if(!p)return NextResponse.json({error:"Teacher login required"},{status:401});
 const parsed=z.object({id:z.string().min(1)}).safeParse(await request.json().catch(()=>null));
 if(!parsed.success)return NextResponse.json({error:"Old student ID is required"},{status:400});
 try{const current=await load(p),student=current.find(x=>x.id===parsed.data.id);if(!student)return NextResponse.json({error:"Non-OBE student not found"},{status:404});const next=current.filter(x=>x.id!==parsed.data.id);await save(p,next);return NextResponse.json({records:next,deletedId:student.id})}catch(e){console.error(e);return NextResponse.json({error:"Unable to delete Non-OBE student"},{status:503})}
}
