"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Search } from "lucide-react";

type Course = { courseCode: string; courseTitle: string };
type Option = { examYear: string; academicYear: string; semester: "Odd" | "Even"; courses: Course[] };
type Registration = Option & { courses: Course[]; confirmedAt: string };
const currentYear = String(new Date().getFullYear());

export default function BacklogRegistration() {
  const [options, setOptions] = useState<Option[]>([]);
  const [registrations, setRegistrations] = useState<Registration[]>([]);
  const [selection, setSelection] = useState({ examYear: currentYear, academicYear: "1st", semester: "Odd" as "Odd" | "Even" });
  const [shown, setShown] = useState<Option | null>(null);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/backlog-registrations", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setOptions(body.options || []); setRegistrations(body.registrations || []); const first = body.options?.[0]; if (first) setSelection({ examYear: first.examYear, academicYear: first.academicYear, semester: first.semester }); }).catch((error) => setMessage(error.message || "Unable to load backlog registration")).finally(() => setLoading(false)); }, []);
  const examYears = useMemo(() => [...new Set([currentYear, ...options.map((item) => item.examYear)])].sort().reverse(), [options]);
  const field = "h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm";
  function search() { const option = options.find((item) => item.examYear === selection.examYear && item.academicYear === selection.academicYear && item.semester === selection.semester) || null; setShown(option); const saved = registrations.find((item) => item.examYear === selection.examYear && item.academicYear === selection.academicYear && item.semester === selection.semester); setSelected(new Set(saved?.courses.map((course) => course.courseCode) || [])); setMessage(option ? "" : "No backlog-eligible failed or need-to-register courses were found. Registration opens only after promotion to the next year Odd semester."); }
  function toggle(code: string) { setSelected((current) => { const next = new Set(current); if (next.has(code)) next.delete(code); else next.add(code); return next; }); }
  async function confirm() { if (!shown || !selected.size) { setMessage("Select at least one course."); return; } setSaving(true); setMessage(""); try { const response = await fetch("/api/backlog-registrations", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...selection, courses: [...selected] }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setRegistrations((current) => [...current.filter((item) => !(item.examYear === selection.examYear && item.academicYear === selection.academicYear && item.semester === selection.semester)), body.registration]); setMessage("Backlog registration confirmed successfully. The selected courses are now available to Prepare Result (Backlog)."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to confirm backlog registration"); } finally { setSaving(false); } }
  return <section><div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="border-b px-6 py-5"><h1 className="text-2xl font-extrabold">Backlog Registration</h1><p className="mt-1 text-sm text-slate-500">Available only after completing both semesters and promotion to the next academic year Odd semester.</p></header><div className="grid gap-4 border-b p-6 md:grid-cols-3"><label className="grid gap-2 text-sm font-semibold">Exam Year<select value={selection.examYear} onChange={(event) => setSelection({ ...selection, examYear: event.target.value })} className={field}>{examYears.map((year) => <option key={year}>{year}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Academic Year<select value={selection.academicYear} onChange={(event) => setSelection({ ...selection, academicYear: event.target.value })} className={field}>{["1st","2nd","3rd","4th"].map((year) => <option key={year}>{year}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Semester<select value={selection.semester} onChange={(event) => setSelection({ ...selection, semester: event.target.value as "Odd" | "Even" })} className={field}><option>Odd</option><option>Even</option></select></label><button type="button" disabled={loading} onClick={search} className="inline-flex w-fit items-center rounded-lg bg-emerald-600 px-4 py-2 font-semibold text-white md:col-span-3"><Search className="mr-2 h-4 w-4" />Search Courses</button></div>{message && <p role="status" className={`m-5 rounded-lg p-3 text-sm font-semibold ${message.includes("successfully") ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{message}</p>}{shown && <div className="p-6"><h2 className="text-lg font-bold">Eligible Courses</h2><div className="mt-3 overflow-hidden rounded-lg border"><table className="w-full border-collapse text-sm"><thead className="bg-[#082f57] text-white"><tr><th className="w-16 p-3">Select</th><th className="p-3 text-left">Course Code</th><th className="p-3 text-left">Course Title</th></tr></thead><tbody>{shown.courses.map((course) => <tr key={course.courseCode} className="border-t even:bg-slate-50"><td className="p-3 text-center"><input type="checkbox" checked={selected.has(course.courseCode)} onChange={() => toggle(course.courseCode)} /></td><td className="p-3 font-semibold">{course.courseCode}</td><td className="p-3">{course.courseTitle}</td></tr>)}</tbody></table></div><button type="button" disabled={saving || !selected.size} onClick={() => void confirm()} className="mt-5 inline-flex items-center rounded-lg bg-blue-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50"><CheckCircle2 className="mr-2 h-4 w-4" />{saving ? "Confirming..." : "Confirm Registration"}</button></div>}</div></section>;
}