"use client";

import { useEffect, useState } from "react";
import { Check, Pencil, Plus, Trash2, X } from "lucide-react";

const normalizeName = (value: string) => value.trim().replace(/^(?:Mr|Mrs)\.?(?:\s+|$)/i, "").trim();

export default function ExaminationCommitteeMembersAdmin() {
  const [names, setNames] = useState<string[]>([]);
  const [name, setName] = useState("");
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);
  const [editingName, setEditingName] = useState<string | null>(null);
  const [editedName, setEditedName] = useState("");

  useEffect(() => { fetch("/api/exam-committee-members", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw Error(body.error); return body; }).then((body) => setNames(body.names || [])).catch((error) => setMessage(error instanceof Error ? error.message : "Unable to load names")); }, []);
  async function save(next: string[]) { setSaving(true); setMessage(""); try { const response = await fetch("/api/exam-committee-members", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ names: next }) }); const body = await response.json(); if (!response.ok) throw Error(body.error); setNames(body.names || []); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save names"); } finally { setSaving(false); } }
  async function add() { const value = normalizeName(name); if (!value) return; if (names.some((item) => item.toLowerCase() === value.toLowerCase())) { setMessage("This committee member is already listed."); return; } await save([...names, value]); setName(""); }
  function startEditing(item: string) { setEditingName(item); setEditedName(item); setMessage(""); }
  async function updateName() { if (!editingName) return; const value = normalizeName(editedName); if (!value) { setMessage("Committee member name is required."); return; } if (names.some((item) => item !== editingName && item.toLowerCase() === value.toLowerCase())) { setMessage("This committee member is already listed."); return; } await save(names.map((item) => item === editingName ? value : item)); setEditingName(null); setEditedName(""); }

  return <section><header><h1 className="text-3xl font-extrabold text-[#102555]">Examination Committee</h1><p className="mt-2 text-slate-500">Only names saved here appear in examination committee dropdowns. Leading Mr. and Mrs. titles are removed automatically.</p></header><div className="mt-6 flex max-w-2xl gap-3 rounded-xl border bg-white p-4 shadow-sm"><input value={name} onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); void add(); } }} className="h-11 min-w-0 flex-1 rounded-lg border px-3" placeholder="Committee member name"/><button type="button" disabled={saving || !normalizeName(name)} onClick={() => void add()} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white disabled:opacity-50"><Plus className="h-4 w-4"/>Add name</button></div>{message && <p role="status" className="mt-4 text-sm text-red-600">{message}</p>}<div className="mt-6 max-w-3xl overflow-hidden rounded-xl border bg-white shadow-sm"><table className="w-full border-collapse"><thead className="bg-[#082452] text-white"><tr><th className="p-3 text-left">Name</th><th className="w-32 p-3">Actions</th></tr></thead><tbody>{names.map((item) => <tr key={item} className="border-t"><td className="p-3 font-medium">{editingName === item ? <input autoFocus value={editedName} onChange={(event) => setEditedName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); void updateName(); } else if (event.key === "Escape") setEditingName(null); }} className="h-10 w-full rounded-lg border px-3" aria-label={`Edit ${item}`}/> : item}</td><td className="p-3 text-center"><div className="flex justify-center gap-2">{editingName === item ? <><button type="button" disabled={saving || !normalizeName(editedName)} onClick={() => void updateName()} aria-label={`Save ${item}`} className="rounded-lg bg-emerald-600 p-2 text-white disabled:opacity-50"><Check className="h-4 w-4"/></button><button type="button" disabled={saving} onClick={() => setEditingName(null)} aria-label="Cancel editing" className="rounded-lg bg-slate-500 p-2 text-white disabled:opacity-50"><X className="h-4 w-4"/></button></> : <><button type="button" disabled={saving} onClick={() => startEditing(item)} aria-label={`Edit ${item}`} className="rounded-lg bg-amber-500 p-2 text-white disabled:opacity-50"><Pencil className="h-4 w-4"/></button><button type="button" disabled={saving} onClick={() => void save(names.filter((candidate) => candidate !== item))} aria-label={`Remove ${item}`} className="rounded-lg bg-red-500 p-2 text-white disabled:opacity-50"><Trash2 className="h-4 w-4"/></button></>}</div></td></tr>)}{!names.length && <tr><td colSpan={2} className="p-8 text-center text-slate-500">No committee member names saved.</td></tr>}</tbody></table></div></section>;
}