"use client";
import {compareResultStudentGroups} from "@/lib/resultStudentOrder";
import {priorYearlyCredit,specialPriorYearlyCredit} from "@/lib/yearlyEarnedCredit";
import {clearedBacklogSubjects} from "@/lib/clearedBacklogSubjects";
import Link from "next/link";
import {useEffect,useState} from "react";
import * as XLSX from "xlsx";
import {loadResultSection,saveResultSection} from "@/lib/storage/resultSections";
import {academicYears,departmentName,oldStudentPromotionForExam,studentAssignedToRegularExam,type OldStudentRecord,type StudentDirectoryRecord} from "@/lib/storage/studentDirectory";
import {cohortSeries,type CourseEligibility} from "@/lib/storage/studentEligibility";
import {syllabusCoursesForExam,type SyllabusCourse,type SyllabusSegment} from "@/lib/storage/syllabuses";
import type {VivaCohort} from "@/lib/storage/vivaMarks";
import {missedRegistrationCourseCodes} from "@/lib/missedRegistrationCourses";
import {formatResultToTwo} from "@/lib/resultRounding";
import {backlogGrade} from "@/lib/backlogGrading";
import {excelCoursePrefix,excelCourseValue} from "@/lib/excelCourseColumns";
import {orderBacklogCourses} from "@/lib/backlogCourseOrder";
import {encodeExcelDraft,excelDraftKey,restoreExcelDraft} from "@/lib/excelInputDraft";

type Cell={a:string;b:string;ct:string;sessional:string;internal:string;external:string;viva:string};
type GridRow={nonObe?:boolean;id:string;name:string;roll:string;registration:string;boardViva:string;cells:Record<string,Cell>;registered:Record<string,boolean>;failed:string[];need:string[];previousGp:number;previousCredit:number;yearlyRegularCredit:number;identityIds:Set<string>;specialCourseIds?:Set<string>;archivedGp?:number;archivedCredit?:number;dirty?:boolean};
type Mark={studentId:string;name:string;rollNo:string;registrationNo:string;registrationType:string;withheld:boolean;present:boolean;partA:string;partB:string;classTestAttendance:string;sessional:string;internal?:string;external?:string;thesisViva?:string;remarks:string;sourceCourseId?:string};
type Prepared={examYear:string;academicYear:string;semester:string;courseId:string;courseCode:string;courseTitle:string;courseType?:SyllabusCourse["type"];students:Mark[];updatedAt:string;published?:boolean};
type Backlog={id:string;studentId:string;studentName:string;rollNo:string;registrationNo:string;examYear:string;academicYear:string;semester:"Odd"|"Even";courseId?:string;courseCode:string;courseTitle:string;present:boolean;partA:string;partB:string;classTestAttendance:string;marks:string;result:"Pass"|"Fail";remarks:string;updatedAt:string;published?:boolean};
type RegCourse={courseId?:string;courseCode:string;courseTitle:string;semester:"Odd"|"Even"};
type Registration={studentId:string;studentName:string;rollNo:string;registrationNo:string;series?:string;specialStudent?:boolean;examYear:string;academicYear:string;courses:RegCourse[]};
type MarkSheetArchive={examYear:string;academicYear:string;semester:string;students:Array<{studentId:string;rollNo:string;earnedCredit:number;gradePoints:number;failedSubjects:string[];registerAgain:string[]}>};
type ResultHistory={examYear:string;academicYear:string;semester:string;students:Array<{studentId:string;rollNo?:string;failedSubjects:string[];registerAgain:string[];totalEarnedCredit?:number;totalGradePoints?:number}>};
const empty=():Cell=>({a:"",b:"",ct:"",sessional:"",internal:"",external:"",viva:""});
const norm=(v:string)=>v.replace(/\s/g,"").toLowerCase(),number=(v:string)=>Number(v)||0,key=(c:SyllabusCourse)=>c.semester+"|"+c.id,rollSeries=(roll:string)=>roll.replace(/\D/g,"").slice(0,2);
const total=(x:Cell,c:SyllabusCourse,v:string)=>Math.round(c.type==="Theory"?number(x.a)+number(x.b)+number(x.ct):c.type==="Thesis"?number(x.internal)+number(x.external)+number(x.viva):number(x.sessional)+number(v));
const grade=(x:Cell,c:SyllabusCourse,v:string,capped=false)=>{const entered=c.type==="Theory"?[x.a,x.b,x.ct]:c.type==="Thesis"?[x.internal,x.external,x.viva]:[x.sessional,v];if(entered.every(value=>value.trim()===""))return"";const s=total(x,c,v);if(c.type==="Theory"&&number(x.a)+number(x.b)<15)return"F";if(c.type==="Sessional"&&number(v)<=0)return"F";return capped?backlogGrade(s):s>=80?"A+":s>=75?"A":s>=70?"A-":s>=65?"B+":s>=60?"B":s>=55?"B-":s>=50?"C+":s>=45?"C":s>=40?"D":"F"};
const gradePoints:Record<string,number>={"A+":4,A:3.75,"A-":3.5,"B+":3.25,B:3,"B-":2.75,"C+":2.5,C:2.25,D:2,F:0};
const field="h-9 rounded border border-slate-300 bg-white px-2 text-sm outline-none focus:border-blue-500 disabled:bg-slate-100";
const nonEligibleFor=(records:CourseEligibility[],row:Pick<GridRow,"id"|"identityIds">,course:SyllabusCourse,selection:{examYear:string;academicYear:string;semester:string})=>records.some(record=>record.examYear===selection.examYear&&record.academicYear===selection.academicYear&&record.semester===selection.semester&&(record.courseId===course.id||norm(record.courseCode)===norm(course.code))&&record.students.some(student=>(student.studentId===row.id||row.identityIds.has(student.studentId))&&student.eligible===false));

export default function ExcelResultInput(){
 const current=String(new Date().getFullYear());
 const[examType,setExamType]=useState<"Regular"|"Backlog">("Regular"),[examYear,setExamYear]=useState(current),[academicYear,setAcademicYear]=useState("1st"),[semester,setSemester]=useState<"Odd"|"Even">("Odd");
 const[courses,setCourses]=useState<SyllabusCourse[]>([]),[regularCourseIds,setRegularCourseIds]=useState<Set<string>>(new Set()),[rows,setRowsState]=useState<GridRow[]>([]),[eligibility,setEligibility]=useState<CourseEligibility[]>([]),[prepared,setPrepared]=useState<Prepared[]>([]),[backlog,setBacklog]=useState<Backlog[]>([]);
 const[busy,setBusy]=useState(false),[submitted,setSubmitted]=useState(false),[message,setMessage]=useState("");
 const[loadedDraftKey,setLoadedDraftKey]=useState<string|null>(null);
 useEffect(()=>{
  if(!loadedDraftKey||!rows.some(row=>row.dirty))return;
  try{
   localStorage.setItem(loadedDraftKey,encodeExcelDraft(rows));
  }catch{
   // Surface an external storage failure instead of silently claiming the draft is safe.
   // eslint-disable-next-line react-hooks/set-state-in-effect
   setMessage("Your browser could not keep a draft. Click Save Marks before leaving this page.");
  }
 },[rows,loadedDraftKey]);
 useEffect(()=>{
  if(!rows.some(row=>row.dirty))return;
  const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=""};
  window.addEventListener("beforeunload",warn);
  return()=>window.removeEventListener("beforeunload",warn);
 },[rows]);
 function clearSheet(){setRows([]);setLoadedDraftKey(null);setCourses([]);setMessage("");setSubmitted(false)}
 const years=Array.from({length:10},(_,i)=>String(Number(current)-i));
function setRows(action:React.SetStateAction<GridRow[]>){setRowsState(previous=>{const next=typeof action==="function"?action(previous):action;return [...next].sort((a,b)=>compareResultStudentGroups(a.roll,b.roll,Boolean(a.nonObe),Boolean(b.nonObe),examYear,academicYear))})}
 const enabled=(r:GridRow,c:SyllabusCourse)=>examType==="Backlog"?Boolean(r.registered[key(c)]):(r.specialCourseIds?r.specialCourseIds.has(c.id):regularCourseIds.has(c.id))&&!nonEligibleFor(eligibility,r,c,{examYear,academicYear,semester});
 const columns=(c:SyllabusCourse)=>c.type==="Theory"?["A","B","CT"]:c.type==="Thesis"?["Internal","External","Viva"]:["Sessional"];

 async function openSheet(){
  setBusy(true);setSubmitted(false);setMessage("");
  const draftKey=excelDraftKey(examType,examYear,academicYear,semester);
  let draft:string|null=null;
  try{draft=loadedDraftKey===draftKey&&rows.some(row=>row.dirty)?encodeExcelDraft(rows):localStorage.getItem(draftKey)}catch{setMessage("Unable to read the local draft. Existing saved marks will still load.")}
  const loadRows=(fresh:GridRow[])=>{
   let restored=fresh;
   try{restored=restoreExcelDraft(fresh,draft)}catch{setMessage("The local draft could not be restored. Existing saved marks have been loaded.")}
   if(restored.some(row=>row.dirty))setMessage("Your unsaved input was restored. Click Save Marks to save it to the server.");
   setLoadedDraftKey(draftKey);setRows(restored);
   if(!fresh.length)setMessage("No registered students found for this examination.");
  };
  try{
   const get=async(u:string)=>{const response=await fetch(u,{cache:"no-store"}),body=await response.json();if(!response.ok)throw Error(body.error||"Unable to load data");return body};
const[bundle,r,sh]=await Promise.all([get("/api/excel-result-input"),examType==="Backlog"?get("/api/backlog-registrations"):Promise.resolve({registrations:[],candidates:[]}),get("/api/students/old/result-history")]),data=bundle.data||{},d={records:data["student-directory"]||[]},s={syllabuses:data.syllabuses||[]},e={records:data["student-eligibility"]||[]},p=(data["prepare-result"]||[]) as Prepared[],b=(data["prepare-result-backlog"]||[]) as Backlog[],v=(data["add-viva-marks"]||[]) as VivaCohort[],o={records:data["old-student-directory"]||[]},ma=(data["marks-sheet"]||[]) as MarkSheetArchive[],mba=(data["marks-sheet-backlog"]||[]) as MarkSheetArchive[],rh=(data["result-sheet"]||[]) as ResultHistory[],rbh=(data["result-sheet-backlog"]||[]) as ResultHistory[];
   const syllabi=(s.syllabuses||[]) as SyllabusSegment[],elig=(e.records||[]) as CourseEligibility[];setEligibility(elig);setPrepared(p||[]);setBacklog(b||[]);
   const historyOrder:Record<string,number>={"1st":1,"2nd":2,"3rd":3,"4th":4},recordRank=(item:{examYear:string;academicYear:string;semester:string})=>Number(item.examYear)*100+(historyOrder[item.academicYear]||0)*3+(item.semester==="Odd"?0:item.semester==="Even"?1:2),allSyllabusCourses=syllabi.flatMap(segment=>segment.courses),backlogCarry=(st:{id:string;rollNo:string},beforeRank:number)=>{const same=(item:{studentId:string;rollNo?:string})=>item.studentId===st.id||norm(item.rollNo||"")===norm(st.rollNo),archived=(mark:Backlog)=>(mba||[]).some(archive=>archive.examYear===mark.examYear&&archive.academicYear===mark.academicYear&&archive.students.some(same)),passed=(b as Backlog[]).filter(mark=>same(mark)&&recordRank(mark)<beforeRank&&mark.result!=="Fail"&&Number(mark.marks)>=40&&!archived(mark)),unique=[...new Map(passed.map(mark=>[mark.examYear+"|"+mark.academicYear+"|"+norm(mark.courseCode),mark])).values()];const totals=unique.reduce((sum,mark)=>{const course=allSyllabusCourses.find(item=>item.id===mark.courseId)||allSyllabusCourses.find(item=>item.semester===mark.semester&&norm(item.code)===norm(mark.courseCode)),credit=Number(course?.credit||0),letter=Number(mark.marks)>=80?"A+":Number(mark.marks)>=75?"A":Number(mark.marks)>=70?"A-":Number(mark.marks)>=65?"B+":Number(mark.marks)>=60?"B":Number(mark.marks)>=55?"B-":Number(mark.marks)>=50?"C+":Number(mark.marks)>=45?"C":"D";return{credit:sum.credit+credit,gp:sum.gp+(gradePoints[letter]||0)*credit}},{credit:0,gp:0});return{...totals,cleared:clearedBacklogSubjects(st,{examYear,academicYear,semester,examType},b as Backlog[])}};
   if(examType==="Regular"){
    const cs=syllabusCoursesForExam(syllabi,cohortSeries(examYear,academicYear),academicYear as SyllabusCourse["year"],semester),baseCourseIds=new Set(cs.map(course=>course.id));
    setRegularCourseIds(baseCourseIds);
    const viva=(v as VivaCohort[]).find(x=>(x.examType||"Regular")==="Regular"&&x.examYear===examYear&&x.academicYear===academicYear&&x.semester===semester);
    const promotedOld=((o.records||[]) as OldStudentRecord[]).filter(student=>Boolean(oldStudentPromotionForExam(student,examYear,academicYear,semester,"Regular")));
    const oldCourseIds=new Set(promotedOld.flatMap(student=>oldStudentPromotionForExam(student,examYear,academicYear,semester,"Regular")?.courseIds||[]));
    const extraCourses=syllabi.flatMap(segment=>segment.courses).filter(course=>oldCourseIds.has(course.id)&&!cs.some(item=>item.id===course.id));
    if(extraCourses.length)cs.push(...extraCourses);
    const savedIds=new Set((p as Prepared[]).filter(record=>record.examYear===examYear&&record.academicYear===academicYear&&record.semester===semester).flatMap(record=>record.students.map(student=>student.studentId))),promotedRolls=new Set(promotedOld.map(student=>norm(student.rollNo)));
    const candidates=(d.records as StudentDirectoryRecord[]).filter(student=>!promotedRolls.has(norm(student.rollNo))&&(studentAssignedToRegularExam(student,{examYear,academicYear,semester})||savedIds.has(student.id)||Boolean(viva?.students.some(item=>item.id===student.id))));
    const expectedSeries=cohortSeries(examYear,academicYear),byRoll=new Map<string,StudentDirectoryRecord>();
    candidates.forEach(student=>{const identity=norm(student.rollNo),current=byRoll.get(identity);if(!current||String(student.series)===expectedSeries&&String(current.series)!==expectedSeries)byRoll.set(identity,student)});
    const expectedRollSeries=expectedSeries.slice(-2);
    const students=[...byRoll.values()].sort((a,b)=>(rollSeries(a.rollNo)===expectedRollSeries?0:1)-(rollSeries(b.rollNo)===expectedRollSeries?0:1)||Number(rollSeries(b.rollNo))-Number(rollSeries(a.rollNo))||a.rollNo.localeCompare(b.rollNo,undefined,{numeric:true}));
    const includedIds=new Set(students.map(st=>st.id)),includedRolls=new Set(students.map(st=>norm(st.rollNo)));
    const specialStudents=promotedOld.filter(student=>!includedIds.has(student.id)&&!includedRolls.has(norm(student.rollNo))).sort((a,b)=>a.rollNo.localeCompare(b.rollNo,undefined,{numeric:true}));
    const order:Record<string,number>={"1st":1,"2nd":2,"3rd":3,"4th":4},isPrior=(item:{examYear:string;academicYear:string;semester:string})=>Number(item.examYear)!==Number(examYear)?Number(item.examYear)<Number(examYear):order[item.academicYear]!==order[academicYear]?order[item.academicYear]<order[academicYear]:item.semester==="Odd"&&semester==="Even",selectedArchive=(ma||[]).find((item:MarkSheetArchive)=>item.examYear===examYear&&item.academicYear===academicYear&&item.semester===semester),historyFor=(st:{id:string;rollNo:string})=>{const same=(x:{studentId:string;rollNo?:string})=>x.studentId===st.id||norm(x.rollNo||"")===norm(st.rollNo),previous=[...(ma||[]),...(mba||[])].filter(isPrior).map(archive=>archive.students.find(same)).filter((item):item is MarkSheetArchive["students"][number]=>Boolean(item)),previousResults=[...(rh||[]),...(rbh||[])].filter(isPrior).flatMap((record:ResultHistory)=>record.students.filter(item=>same(item))),latestPublishedEntry=[...(rh||[]),...(rbh||[])].filter((record:ResultHistory)=>isPrior(record)).sort((left:ResultHistory,right:ResultHistory)=>recordRank(right)-recordRank(left)).map((record:ResultHistory)=>({record,student:record.students.find(item=>same(item))})).find(item=>Boolean(item.student)),latestPublished=latestPublishedEntry?.student,supplemental=[...(ma||[]),...(mba||[])].filter((archive:MarkSheetArchive)=>isPrior(archive)&&Boolean(latestPublishedEntry)&&recordRank(archive)>recordRank(latestPublishedEntry!.record)).map((archive:MarkSheetArchive)=>archive.students.find(same)).filter((item):item is MarkSheetArchive["students"][number]=>Boolean(item)),carry=backlogCarry(st,Number(examYear)*100+(order[academicYear]||0)*3+(semester==="Odd"?0:1)),archiveGp=previous.reduce((sum,item)=>sum+Number(item.gradePoints||0),0),archiveCredit=previous.reduce((sum,item)=>sum+Number(item.earnedCredit||0),0),publishedGp=latestPublished?Number(latestPublished.totalGradePoints||0)+supplemental.reduce((sum,item)=>sum+Number(item.gradePoints||0),0):0,publishedCredit=latestPublished?Number(latestPublished.totalEarnedCredit||0)+supplemental.reduce((sum,item)=>sum+Number(item.earnedCredit||0),0):0;return{previousGp:Math.max(archiveGp,publishedGp),previousCredit:Math.max(archiveCredit,publishedCredit),failed:[...new Set(latestPublished?.failedSubjects||[...previousResults.flatMap(item=>item.failedSubjects),...previous.flatMap(item=>item.failedSubjects)])].filter(code=>!carry.cleared.includes(norm(code))),need:[...new Set(latestPublished?.registerAgain||[...(ma||[]),...(mba||[])].filter(isPrior).sort((left,right)=>recordRank(right)-recordRank(left)).map(archive=>archive.students.find(same)).find(Boolean)?.registerAgain||[])].filter(code=>!carry.cleared.includes(norm(code)))}};
    const buildRow=(st:StudentDirectoryRecord|OldStudentRecord,specialCourseIds?:Set<string>)=>{const identityIds=new Set<string>([st.id,...((d.records||[]) as StudentDirectoryRecord[]).filter(item=>norm(item.rollNo)===norm(st.rollNo)).map(item=>item.id),...((o.records||[]) as OldStudentRecord[]).filter(item=>norm(item.rollNo)===norm(st.rollNo)).map(item=>item.id)]),history=historyFor(st),specialOutstanding="outstandingCourses" in st?st.outstandingCourses.map(item=>({status:item.status,code:allSyllabusCourses.find(course=>course.id===item.courseId)?.code||item.courseId})):[],historicalFailed=specialCourseIds?specialOutstanding.filter(item=>item.status==="failed").map(item=>item.code):history.failed,historicalNeed=specialCourseIds?specialOutstanding.filter(item=>item.status==="need-register").map(item=>item.code):history.need,missed="year" in st?missedRegistrationCourseCodes(st,{academicYear,semester},syllabi,[...(ma||[]),...(mba||[])],p,false):[];return({nonObe:Boolean(specialCourseIds),id:st.id,name:st.name,roll:st.rollNo,registration:st.registrationNo,boardViva:viva?.students.find(x=>x.id===st.id)?.marks||"",registered:{},failed:historicalFailed.filter(code=>!clearedBacklogSubjects(st,{examYear,academicYear,semester,examType},b as Backlog[]).includes(norm(code))),previousGp:"gradePoints" in st?st.gradePoints:history.previousGp,previousCredit:"earnedCredit" in st?st.earnedCredit:history.previousCredit,yearlyRegularCredit:specialCourseIds?specialPriorYearlyCredit(st,{examYear,academicYear,semester,examType},sh.records||[]):priorYearlyCredit(st,{examYear,academicYear,semester,examType},ma||[],mba||[],[...(rh||[]),...(rbh||[]).map(item=>({...item,examType:"Backlog"}))]),identityIds,specialCourseIds,archivedGp:specialCourseIds?undefined:selectedArchive?.students.find(item=>identityIds.has(item.studentId)||norm(item.rollNo||"")===norm(st.rollNo))?.gradePoints,archivedCredit:specialCourseIds?undefined:selectedArchive?.students.find(item=>identityIds.has(item.studentId)||norm(item.rollNo||"")===norm(st.rollNo))?.earnedCredit,need:[...new Set([...historicalNeed,...missed,...cs.filter(c=>(specialCourseIds?specialCourseIds.has(c.id):baseCourseIds.has(c.id))&&nonEligibleFor(elig,{id:st.id,identityIds},c,{examYear,academicYear,semester})).map(c=>c.code)])],cells:Object.fromEntries(cs.map(c=>{const old=(p as Prepared[]).find(z=>z.examYear===examYear&&z.academicYear===academicYear&&z.semester===semester&&z.courseId===c.id)?.students.find(z=>z.studentId===st.id);return[key(c),old?{a:old.partA||"",b:old.partB||"",ct:old.classTestAttendance||"",sessional:old.sessional||"",internal:old.internal||"",external:old.external||"",viva:old.thesisViva||""}:empty()]}))})};
    setCourses(cs);loadRows([...students.map(st=>buildRow(st)),...specialStudents.map(st=>buildRow(st,new Set(oldStudentPromotionForExam(st,examYear,academicYear,semester,"Regular")?.courseIds||[])))]);
   }else{
    const promotedSpecial=(o.records||[]) as OldStudentRecord[];
    const specialRegistrations:Registration[]=promotedSpecial.flatMap(student=>{const promotion=student.promotions.find(item=>item.examType==="Backlog"&&item.examYear===examYear&&item.academicYear===academicYear);if(!promotion)return[];return[{studentId:student.id,studentName:student.name,rollNo:student.rollNo,registrationNo:student.registrationNo,examYear,academicYear,courses:allSyllabusCourses.filter(course=>promotion.courseIds.includes(course.id)&&course.semester!=="Short Semester").map(course=>({courseId:course.id,courseCode:course.code,courseTitle:course.title,semester:course.semester as "Odd"|"Even"}))}]});
    const registrations=[...(r.registrations||[]).filter((item:Registration)=>!specialRegistrations.some(special=>special.studentId===item.studentId&&special.examYear===item.examYear&&special.academicYear===item.academicYear)),...specialRegistrations];
    const relevant=registrations.filter((x:Registration)=>x.examYear===examYear&&x.academicYear===academicYear&&x.courses.length>0),people=[...new Map(relevant.map((x:Registration)=>[x.studentId,x])).values()] as Registration[];
    const all=syllabi.flatMap(x=>x.courses),resolveRegistrationCourse=(course:RegCourse,registration:Registration)=>{const obeStudent=((d.records||[]) as StudentDirectoryRecord[]).find(item=>item.id===registration.studentId||norm(item.rollNo)===norm(registration.rollNo)),nonObeStudent=((o.records||[]) as OldStudentRecord[]).some(item=>item.id===registration.studentId||norm(item.rollNo)===norm(registration.rollNo));if(course.courseId){const exact=all.find(item=>item.id===course.courseId);if(exact&&(nonObeStudent||!exact.id.startsWith("old-course-")))return exact}const placement=obeStudent?.obeBatchPlacements?.filter(item=>item.academicYear===registration.academicYear&&Number(item.effectiveExamYear)<=Number(registration.examYear)).sort((left,right)=>Number(right.effectiveExamYear)-Number(left.effectiveExamYear))[0],studentSeries=Number(placement?.series||registration.series||obeStudent?.series||0),matching=syllabi.filter(segment=>segment.active!==false&&studentSeries>=Number(segment.fromSeries)&&studentSeries<=Number(segment.toSeries)).sort((left,right)=>(Number(left.toSeries)-Number(left.fromSeries))-(Number(right.toSeries)-Number(right.fromSeries))).flatMap(segment=>segment.courses);return matching.find(item=>item.semester===course.semester&&norm(item.code)===norm(course.courseCode))||all.find(item=>item.semester===course.semester&&norm(item.code)===norm(course.courseCode))||{id:course.semester+"-"+norm(course.courseCode),code:course.courseCode,title:course.courseTitle,credit:"0",type:"Theory" as const,department:"BECM",year:academicYear as SyllabusCourse["year"],semester:course.semester}},cs:SyllabusCourse[]=[...new Map(relevant.flatMap((registration:Registration)=>registration.courses.map((course:RegCourse)=>resolveRegistrationCourse(course,registration))).map((course:SyllabusCourse)=>[key(course),course])).values()];
    const backlogOrder:Record<string,number>={"1st":1,"2nd":2,"3rd":3,"4th":4},archiveRank=(item:{examYear:string;academicYear:string;semester:string})=>Number(item.examYear)*100+(backlogOrder[item.academicYear]||0)*3+(item.semester==="Odd"?0:item.semester==="Even"?1:2),currentRank=Number(examYear)*100+(backlogOrder[academicYear]||0)*3+2,backlogHistory=(st:Registration)=>{const special=promotedSpecial.find(student=>student.id===st.studentId);if(special)return{previousGp:special.gradePoints,previousCredit:special.earnedCredit,yearlyRegularCredit:0,failed:special.outstandingCourses.filter(item=>item.status==="failed").map(item=>allSyllabusCourses.find(course=>course.id===item.courseId)?.code||item.courseId),need:special.outstandingCourses.filter(item=>item.status==="need-register").map(item=>allSyllabusCourses.find(course=>course.id===item.courseId)?.code||item.courseId)};const same=(item:{studentId:string;rollNo?:string})=>item.studentId===st.studentId||norm(item.rollNo||"")===norm(st.rollNo),prior=[...(ma||[]),...(mba||[])].filter(item=>archiveRank(item)<currentRank),previous=prior.map(archive=>archive.students.find(same)).filter((item):item is MarkSheetArchive["students"][number]=>Boolean(item)),latest=prior.sort((left,right)=>archiveRank(right)-archiveRank(left)).map(archive=>archive.students.find(same)).find(Boolean),published=[...(rh||[]),...(rbh||[])].filter(item=>archiveRank(item)<currentRank).sort((left,right)=>archiveRank(right)-archiveRank(left)).flatMap(item=>item.students.filter(student=>student.studentId===st.studentId||norm(student.rollNo||"")===norm(st.rollNo))).at(0),outstanding=published||latest,carry=backlogCarry({id:st.studentId,rollNo:st.rollNo},currentRank),archiveGp=previous.reduce((sum,item)=>sum+Number(item.gradePoints||0),0),archiveCredit=previous.reduce((sum,item)=>sum+Number(item.earnedCredit||0),0);return{previousGp:published?Number(published.totalGradePoints||0):archiveGp,previousCredit:published?Number(published.totalEarnedCredit||0):archiveCredit,yearlyRegularCredit:(ma||[]).filter(item=>item.academicYear===academicYear&&archiveRank(item)<currentRank).reduce((sum,archive)=>sum+Number(archive.students.find(same)?.earnedCredit||0),0),failed:(outstanding?.failedSubjects||[]).filter(code=>!carry.cleared.includes(norm(code))),need:(outstanding?.registerAgain||[]).filter(code=>!carry.cleared.includes(norm(code)))}};
    setCourses(orderBacklogCourses(cs,syllabi));loadRows(people.map(st=>{const history=backlogHistory(st),obeStudent=((d.records||[]) as StudentDirectoryRecord[]).find(item=>item.id===st.studentId||norm(item.rollNo)===norm(st.rollNo)),missed=obeStudent&&!promotedSpecial.some(item=>item.id===st.studentId||norm(item.rollNo)===norm(st.rollNo))?missedRegistrationCourseCodes(obeStudent,{academicYear,semester:"Even"},syllabi,[...(ma||[]),...(mba||[])],p,false):[],saved=registrations.find((x:Registration)=>x.studentId===st.studentId&&x.examYear===examYear&&x.academicYear===academicYear),registered=Object.fromEntries(cs.map(c=>[key(c),Boolean(saved?.courses.some((x:RegCourse)=>key(resolveRegistrationCourse(x,saved))===key(c)))])),nonObe=promotedSpecial.some(item=>item.id===st.studentId&&Number(item.series)<2020);return{nonObe,id:st.studentId,name:st.studentName,roll:st.rollNo,registration:st.registrationNo,boardViva:"",registered,previousGp:history.previousGp,previousCredit:history.previousCredit,yearlyRegularCredit:promotedSpecial.some(item=>item.id===st.studentId)?specialPriorYearlyCredit(promotedSpecial.find(item=>item.id===st.studentId)!,{examYear,academicYear,semester:"Backlog",examType},sh.records||[]):priorYearlyCredit({id:st.studentId,rollNo:st.rollNo},{examYear,academicYear,semester:"Backlog",examType},ma||[],mba||[],[...(rh||[]),...(rbh||[]).map(item=>({...item,examType:"Backlog"}))]),identityIds:new Set([st.studentId]),failed:history.failed.filter(code=>!clearedBacklogSubjects({id:st.studentId,rollNo:st.rollNo},{examYear,academicYear,semester,examType},b as Backlog[]).includes(norm(code))),need:[...new Set([...history.need,...missed])],cells:Object.fromEntries(cs.map(c=>{const old=(b as Backlog[]).find(x=>x.studentId===st.studentId&&x.examYear===examYear&&x.academicYear===academicYear&&x.semester===c.semester&&norm(x.courseCode)===norm(c.code)),regularMark=(p as Prepared[]).filter(record=>Number(record.examYear)<=Number(examYear)&&record.semester===c.semester&&norm(record.courseCode)===norm(c.code)).sort((left,right)=>Number(right.examYear)-Number(left.examYear)).flatMap(record=>record.students).find(student=>student.studentId===st.studentId||norm(student.rollNo)===norm(st.rollNo)),value={...empty(),a:old?.partA||"",b:old?.partB||"",ct:nonObe?old?.classTestAttendance||regularMark?.classTestAttendance||"":regularMark?.classTestAttendance||old?.classTestAttendance||""};return[key(c),value]}))}}));
   }
  }catch(error){setMessage(error instanceof Error?error.message:"Unable to open Excel sheet.")}finally{setBusy(false)}
 }
 function updateCell(id:string,k:string,change:Partial<Cell>){setRows(old=>old.map(r=>r.id===id?{...r,dirty:true,cells:{...r.cells,[k]:{...r.cells[k],...change}}}:r))}
 function updateRow(id:string,change:Partial<GridRow>){setRows(old=>old.map(r=>r.id===id?{...r,...change}:r))}
 function toggle(r:GridRow,c:SyllabusCourse){const k=key(c),on=!r.registered[k];updateRow(r.id,{dirty:true,registered:{...r.registered,[k]:on},need:r.need})}
 function failedFor(row:GridRow){const values=new Map(row.failed.map(code=>[norm(code),code]));courses.forEach(course=>{if(examType==="Regular"&&(row.specialCourseIds?!row.specialCourseIds.has(course.id):!regularCourseIds.has(course.id)))return;const isEnabled=enabled(row,course);if(examType==="Backlog"&&!isEnabled)return;const code=norm(course.code),letter=isEnabled?grade(row.cells[key(course)],course,row.boardViva,examType==="Backlog"):"-";if(letter==="F")values.set(code,course.code);else if(letter&&letter!=="-")values.delete(code);else if(letter==="-"&&examType==="Regular")values.delete(code)});return[...values.values()]}
 function needFor(row:GridRow){const values=new Map(row.need.map(code=>[norm(code),code]));courses.forEach(course=>{if(examType==="Regular"&&(row.specialCourseIds?!row.specialCourseIds.has(course.id):!regularCourseIds.has(course.id)))return;const isEnabled=enabled(row,course);if(examType==="Backlog"&&!isEnabled)return;const code=norm(course.code),letter=isEnabled?grade(row.cells[key(course)],course,row.boardViva,examType==="Backlog"):"-";if(letter==="-"&&examType==="Regular")values.set(code,course.code);else if(letter)values.delete(code)});return[...values.values()]}
 function currentTotals(row:GridRow){if(examType==="Regular"&&!row.dirty&&row.archivedGp!==undefined&&row.archivedCredit!==undefined)return{gp:row.archivedGp,credit:row.archivedCredit};return courses.reduce((result,course)=>{if(!enabled(row,course))return result;const letter=grade(row.cells[key(course)],course,row.boardViva,examType==="Backlog");if(!letter||letter==="F")return result;const credit=Number(course.credit)||0;return{gp:result.gp+(gradePoints[letter]||0)*credit,credit:result.credit+credit}},{gp:0,credit:0})}
 async function exportExcel(){
  setBusy(true);setMessage("");
  try{
   const {Workbook}=await import("exceljs"),workbook=new Workbook(),sheet=workbook.addWorksheet("Marks",{views:[{state:"frozen",xSplit:4,ySplit:5}]});
   const definitions:Array<{key:string;width:number;label:string;course?:SyllabusCourse}>=[
    {key:"SL",width:7,label:"SL"},{key:"Roll No",width:15,label:"Roll No"},{key:"Student Name",width:30,label:"Student Name"},{key:"Registration No",width:21,label:"Registration No"},
    ...(examType==="Regular"?[{key:"Board Viva",width:14,label:"Board Viva"}]:[]),
    ...courses.flatMap(course=>{const prefix=excelCoursePrefix(course);return[...(examType==="Backlog"?[{key:prefix+" Registered",width:13,label:"Register",course}]:[]),...columns(course).map(label=>({key:prefix+" "+label,width:14,label,course}))]}),
    {key:"Yearly Earned Credit",width:22,label:"Yearly Earned Credit"},{key:"Failed Subjects / Status",width:28,label:"Failed Subjects / Status"},{key:"Need to Register",width:32,label:"Need to Register"}
   ];
   sheet.columns=definitions.map(item=>({key:item.key,width:item.width}));
   sheet.getRow(1).values=definitions.map(item=>item.key);sheet.getRow(1).hidden=true;
   const lastColumn=definitions.length,title="RAJSHAHI UNIVERSITY OF ENGINEERING & TECHNOLOGY",details=`${examType} Examination ${examYear} • ${academicYear} Year${examType==="Regular"?` • ${semester} Semester`:""}`;
   sheet.mergeCells(2,1,2,lastColumn);sheet.getCell(2,1).value=title;
   sheet.mergeCells(3,1,3,lastColumn);sheet.getCell(3,1).value=details;
   const identityCount=4+(examType==="Regular"?1:0),identityLabels=["SL","Roll No","Student Name","Registration No",...(examType==="Regular"?["Board Viva"]:[])];
   identityLabels.forEach((label,index)=>{const column=index+1;sheet.mergeCells(4,column,5,column);sheet.getCell(4,column).value=label});
   let column=identityCount+1;
   courses.forEach(course=>{const subHeaders=[...(examType==="Backlog"?["Register"]:[]),...columns(course)],start=column,end=column+subHeaders.length-1;sheet.mergeCells(4,start,4,end);sheet.getCell(4,start).value=`${course.code} — ${course.title} (${course.semester})`;subHeaders.forEach((label,index)=>{sheet.getCell(5,start+index).value=label});column=end+1});
   ["Yearly Earned Credit","Failed Subjects / Status","Need to Register"].forEach(label=>{sheet.mergeCells(4,column,5,column);sheet.getCell(4,column).value=label;column++});
   rows.forEach((row,index)=>{const values:Record<string,string|number>={"SL":index+1,"Roll No":row.roll,"Student Name":row.name,"Registration No":row.registration,"Yearly Earned Credit":Number((row.yearlyRegularCredit+currentTotals(row).credit).toFixed(2)),"Failed Subjects / Status":failedFor(row).join(", ")||"-","Need to Register":needFor(row).join(", ")||"-"};if(examType==="Regular")values["Board Viva"]=row.boardViva;courses.forEach(course=>{const prefix=excelCoursePrefix(course),value=row.cells[key(course)];if(examType==="Backlog")values[prefix+" Registered"]=row.registered[key(course)]?"Yes":"No";columns(course).forEach(heading=>{values[prefix+" "+heading]=enabled(row,course)?heading==="A"?value.a:heading==="B"?value.b:heading==="CT"?value.ct:heading==="Sessional"?value.sessional:heading==="Internal"?value.internal:heading==="External"?value.external:value.viva:"-"})});sheet.addRow(values)});
   const border={top:{style:"thin" as const,color:{argb:"FFB8C5D6"}},left:{style:"thin" as const,color:{argb:"FFB8C5D6"}},bottom:{style:"thin" as const,color:{argb:"FFB8C5D6"}},right:{style:"thin" as const,color:{argb:"FFB8C5D6"}}};
   sheet.getRow(2).height=28;sheet.getRow(3).height=23;sheet.getRow(4).height=34;sheet.getRow(5).height=25;
   sheet.getCell(2,1).font={bold:true,size:16,color:{argb:"FFFFFFFF"}};sheet.getCell(2,1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF082F57"}};sheet.getCell(2,1).alignment={horizontal:"center",vertical:"middle"};
   sheet.getCell(3,1).font={bold:true,size:11,color:{argb:"FF102555"}};sheet.getCell(3,1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFDCEAF7"}};sheet.getCell(3,1).alignment={horizontal:"center",vertical:"middle"};
   for(let rowNumber=4;rowNumber<=5;rowNumber++)for(let col=1;col<=lastColumn;col++){const cell=sheet.getCell(rowNumber,col);cell.font={bold:true,color:{argb:"FFFFFFFF"}};cell.fill={type:"pattern",pattern:"solid",fgColor:{argb:rowNumber===4?"FF145A86":"FF287EAA"}};cell.alignment={horizontal:"center",vertical:"middle",wrapText:true};cell.border=border}
   const failedColumn=definitions.findIndex(item=>item.key==="Failed Subjects / Status")+1,needColumn=definitions.findIndex(item=>item.key==="Need to Register")+1;
   for(let rowNumber=6;rowNumber<=sheet.rowCount;rowNumber++){const row=sheet.getRow(rowNumber),summaryLines=Math.max(String(row.getCell(failedColumn).value||"").split(",").length,String(row.getCell(needColumn).value||"").split(",").length);row.height=Math.max(23,summaryLines*15);for(let col=1;col<=lastColumn;col++){const cell=row.getCell(col),summaryColumn=col===failedColumn||col===needColumn;cell.alignment={horizontal:col===3||summaryColumn?"left":"center",vertical:"middle",wrapText:summaryColumn};cell.border=border;if(rowNumber%2===0)cell.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFF2F7FB"}}}}
   sheet.pageSetup={orientation:"landscape",fitToPage:true,fitToWidth:1,fitToHeight:0,paperSize:9,margins:{left:0.25,right:0.25,top:0.5,bottom:0.5,header:0.2,footer:0.2}};
   const buffer=await workbook.xlsx.writeBuffer(),blob=new Blob([buffer as BlobPart],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="result-input-"+examType+"-"+examYear+"-"+academicYear+".xlsx";anchor.click();URL.revokeObjectURL(url);setMessage("Smart marksheet Excel template exported successfully.");
  }catch(error){setMessage(error instanceof Error?error.message:"Unable to export the Excel template.")}finally{setBusy(false)}
 }
 async function importExcel(file:File){try{const book=XLSX.read(await file.arrayBuffer()),rawItems=XLSX.utils.sheet_to_json<Record<string,unknown>>(book.Sheets[book.SheetNames[0]],{defval:""}),items=rawItems.filter(item=>{const roll=String(item["Roll No"]??"").trim();return Boolean(roll)&&norm(roll)!=="rollno"}),byRoll=new Map(items.map(item=>[norm(String(item["Roll No"])),item])),rosterRolls=new Set(rows.map(row=>norm(row.roll))),matched=[...byRoll.keys()].filter(roll=>rosterRolls.has(roll)).length;setRows(old=>old.map(row=>{const record=byRoll.get(norm(row.roll));if(!record)return row;const cells={...row.cells},registered={...row.registered};courses.forEach(course=>{const k=key(course),read=(heading:string)=>excelCourseValue(record,course,courses,heading);if(examType==="Backlog"){const flag=norm(String(read("Registered")));if(flag==="yes"||flag==="true"||flag==="1")registered[k]=true;if(flag==="no"||flag==="false"||flag==="0")registered[k]=false}const canImport=examType==="Backlog"?Boolean(registered[k]):enabled(row,course);if(!canImport)return;const value={...cells[k]};value.a=String(read("A")??value.a);value.b=String(read("B")??value.b);if(examType!=="Backlog"||row.nonObe)value.ct=String(read("CT")??value.ct);value.sessional=String(read("Sessional")??value.sessional);value.internal=String(read("Internal")??value.internal);value.external=String(read("External")??value.external);value.viva=String(read("Viva")??value.viva);cells[k]=value});return{...row,dirty:true,registered,boardViva:examType==="Regular"?String(record["Board Viva"]??row.boardViva):row.boardViva,cells}}));setMessage("Excel imported: "+matched+" roll(s) matched, "+(items.length-matched)+" unmatched row(s).")}catch{setMessage("Invalid Excel file. Export and fill the template for this examination first.")}}

 async function submit(finalize:boolean){
  if(!rows.length||busy)return;
  if(finalize&&!window.confirm("Submit these marks as a result publication request for administrator approval?"))return;
  setBusy(true);setMessage("");
  let updateRequested=false;
  try{
   const stamp=new Date().toISOString();
   if(examType==="Regular"){
    const records: Prepared[] = courses.map((course) => {
      const students = rows.filter((row) => enabled(row, course)).map((row) => {
        const value = row.cells[key(course)];
        return { studentId: row.id, name: row.name, rollNo: row.roll, registrationNo: row.registration, registrationType: row.specialCourseIds?"Non-OBE":"Regular", withheld: false, present: true, partA: value.a, partB: value.b, classTestAttendance: value.ct, sessional: value.sessional, internal: value.internal, external: value.external, thesisViva: value.viva, remarks: "", sourceCourseId: course.id };
      });
      return { examYear, academicYear, semester, courseId: course.id, courseCode: course.code, courseTitle: course.title, courseType: course.type, students, updatedAt: stamp };
    });
    await saveResultSection("prepare-result",[...prepared.filter(x=>!(x.examYear===examYear&&x.academicYear===academicYear&&x.semester===semester&&courses.some(c=>c.id===x.courseId))),...records]);
    const vivas=await loadResultSection<VivaCohort[]>("add-viva-marks"),existing=vivas.find(x=>((x.examType||"Regular")==="Regular"&&x.examYear===examYear&&x.academicYear===academicYear&&x.semester===semester)),cohort:VivaCohort={...existing,department:departmentName,examType:"Regular",examYear,academicYear,semester,students:rows.map(r=>({id:r.id,name:r.name,registrationNo:r.registration,rollNo:r.roll,registrationType:r.specialCourseIds?"Non-OBE":"Regular",marks:r.boardViva,present:true})),finalized:finalize||Boolean(existing?.finalized),submitted:finalize?false:Boolean(existing?.submitted),updatedAt:stamp,published:Boolean(existing?.published)};
    await saveResultSection("add-viva-marks",[...vivas.filter(x=>!((x.examType||"Regular")==="Regular"&&x.examYear===examYear&&x.academicYear===academicYear&&x.semester===semester)),cohort]);
    // Refresh existing semester summaries so corrected marks carry forward into
    // saved cumulative results in the same marksheet API transaction.
    const archives=await loadResultSection<MarkSheetArchive[]>("marks-sheet");
    const refreshed=archives.map(archive=>{
      if(archive.examYear!==examYear||archive.academicYear!==academicYear||archive.semester!==semester)return archive;
      return {...archive,students:archive.students.map(student=>{
        const row=rows.find(row=>!row.specialCourseIds&&(row.identityIds.has(student.studentId)||norm(row.roll)===norm(student.rollNo)));
        if(!row)return student;
        const totals=currentTotals(row),regular=courses.filter(course=>regularCourseIds.has(course.id));
        return {...student,earnedCredit:totals.credit,gradePoints:Number(totals.gp.toFixed(3)),sgpa:(Math.round(((totals.credit?totals.gp/totals.credit:0)+Number.EPSILON)*100)/100).toFixed(2),failedSubjects:regular.filter(course=>enabled(row,course)&&grade(row.cells[key(course)],course,row.boardViva)==="F").map(course=>course.code),registerAgain:regular.filter(course=>!enabled(row,course)).map(course=>course.code)};
      })};
    });
    if(JSON.stringify(refreshed)!==JSON.stringify(archives))await saveResultSection("marks-sheet",refreshed);
   }else{
    const selections=rows.map(r=>({studentId:r.id,courses:courses.filter(c=>r.registered[key(c)]).map(c=>({courseCode:c.code,semester:c.semester as "Odd"|"Even"}))}));
    const response=await fetch("/api/backlog-registrations",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({examYear,academicYear,selections})}),body=await response.json();
    if(!response.ok)throw Error(body.error||"Unable to register backlog subjects.");
    const completed:Backlog[]=rows.flatMap(r=>courses.filter(c=>r.registered[key(c)]).map(c=>{const x=r.cells[key(c)],score=total(x,c,""),old=backlog.find(b=>b.studentId===r.id&&b.examYear===examYear&&b.academicYear===academicYear&&b.semester===c.semester&&norm(b.courseCode)===norm(c.code));return{id:old?.id||crypto.randomUUID(),studentId:r.id,studentName:r.name,rollNo:r.roll,registrationNo:r.registration,examYear,academicYear,semester:c.semester as "Odd"|"Even",courseId:c.id,courseCode:c.code,courseTitle:c.title,present:true,partA:x.a,partB:x.b,classTestAttendance:x.ct,marks:String(score),result:grade(x,c,"",true)==="F"?"Fail":"Pass",remarks:"",updatedAt:stamp}}));
    await saveResultSection("prepare-result-backlog",[...backlog.filter(b=>!(b.examYear===examYear&&b.academicYear===academicYear&&completed.some(x=>x.studentId===b.studentId&&x.semester===b.semester&&norm(x.courseCode)===norm(b.courseCode)))),...completed]);
   }
   if(finalize){
    const response=await fetch("/api/result-publications",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({department:departmentName,examType,examYear,academicYear,semester:examType==="Regular"?semester:""})}),body=await response.json();
    if(!response.ok)throw Error("Marks were saved, but the publication request failed: "+(body.error||"Unable to request result publication."));
    updateRequested=Boolean(body.updateRequested);
   }
   if(loadedDraftKey){try{localStorage.removeItem(loadedDraftKey)}catch{/* Keep the server save successful even if browser storage is unavailable. */}}
   setRows(old=>old.map(row=>row.dirty?{...row,dirty:false,archivedGp:undefined,archivedCredit:undefined}:row));
   setSubmitted(finalize);setMessage(finalize?(updateRequested?"Marks saved and published-result update request submitted for administrator approval.":"Marks saved and result publication request submitted for administrator approval."):"Marks saved successfully. You can continue editing and save again.");
  }catch(error){setMessage(error instanceof Error?error.message:"Unable to save marks.")}finally{setBusy(false)}
 }
 const markInput=(r:GridRow,c:SyllabusCourse,name:keyof Cell,value:string)=><td key={key(c)+"-"+name} className="border p-1"><input type="number" min="0" step="0.5" value={value} onChange={e=>updateCell(r.id,key(c),{[name]:e.target.value})} className={field+" w-16"}/></td>;
 return <section className="min-h-screen bg-slate-50 p-3 sm:p-5"><div className="rounded-xl border bg-white shadow-sm">
  <header className="border-b p-5"><h1 className="text-2xl font-extrabold text-[#102555]">Excel Result Input</h1><p className="mt-1 text-sm text-slate-600">One row per roll number. Enter marks here or download, edit and import the Excel file.</p></header>
  <div className="grid gap-4 border-b p-5 md:grid-cols-2">
   <label className="grid gap-2 text-sm font-semibold">Exam Type<select disabled={busy} className={field} value={examType} onChange={e=>{setExamType(e.target.value as "Regular"|"Backlog");clearSheet()}}><option>Regular</option><option>Backlog</option></select></label>
   <label className="grid gap-2 text-sm font-semibold">Exam Year<select disabled={busy} className={field} value={examYear} onChange={e=>{setExamYear(e.target.value);clearSheet()}}>{years.map(y=><option key={y}>{y}</option>)}</select></label>
   <label className="grid gap-2 text-sm font-semibold">Academic Year<select disabled={busy} className={field} value={academicYear} onChange={e=>{setAcademicYear(e.target.value);clearSheet()}}>{academicYears.map(y=><option key={y}>{y}</option>)}</select></label>
   {examType==="Regular"&&<label className="grid gap-2 text-sm font-semibold">Semester<select disabled={busy} className={field} value={semester} onChange={e=>{setSemester(e.target.value as "Odd"|"Even");clearSheet()}}><option>Odd</option><option>Even</option></select></label>}
   <div className="flex flex-wrap items-center gap-3 md:col-span-2"><button disabled={busy} onClick={()=>void openSheet()} className="rounded bg-emerald-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{busy?"Loading...":"Open Excel Sheet"}</button><button disabled={!rows.length||busy} onClick={()=>void submit(false)} className="rounded bg-blue-700 px-5 py-2.5 font-semibold text-white disabled:opacity-40">Save Marks</button><button disabled={!rows.length||busy} onClick={exportExcel} className="rounded bg-sky-700 px-5 py-2.5 font-semibold text-white disabled:opacity-40">Export Excel Template</button><label className={"rounded bg-amber-500 px-5 py-2.5 font-semibold text-white "+(!rows.length||busy?"pointer-events-none opacity-40":"cursor-pointer")}>Import Filled Excel<input type="file" accept=".xlsx,.xls" disabled={!rows.length||busy} className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)void importExcel(file);e.currentTarget.value=""}}/></label><span className="text-xs text-slate-500">Edits are kept as a draft in this browser. Click Save Marks to save them to the server.</span></div>
  </div>
  {message&&<p role="status" className="m-4 rounded bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{message}</p>}
  {rows.length>0&&<>
  <fieldset disabled={busy} className="min-w-0"><div className="max-h-[70vh] overflow-auto"><table className="min-w-max border-collapse text-xs"><thead className="sticky top-0 z-10 bg-[#082f57] text-white"><tr><th rowSpan={2} className="sticky left-0 z-20 border bg-[#082f57] p-2">Roll No.</th><th rowSpan={2} className="border p-2">Student</th>{examType==="Regular"&&<th rowSpan={2} className="border p-2">Board Viva</th>}{courses.map(c=><th key={key(c)} colSpan={columns(c).length+2+(examType==="Backlog"?1:0)} className="border p-2">{c.code}<br/><span className="font-normal">{c.title} - {c.semester}</span></th>)}<th rowSpan={2} className="border p-2">GP</th><th rowSpan={2} className="border p-2">Semester Earned Credit</th><th rowSpan={2} className="border p-2">GPA</th><th rowSpan={2} className="border p-2">Yearly Earned Credit</th><th rowSpan={2} className="border p-2">Previous GP</th><th rowSpan={2} className="border p-2">Previous Earned Credit</th><th rowSpan={2} className="border p-2">Total GP Earned</th><th rowSpan={2} className="border p-2">Total Credits Earned</th><th rowSpan={2} className="border p-2">CGPA</th><th rowSpan={2} className="border p-2">Failed Subjects / Status</th><th rowSpan={2} className="border p-2">Need to Register</th></tr><tr>{courses.flatMap(c=>[...(examType==="Backlog"?["Register"]:[]),...columns(c),"Total","Grade"].map(h=><th key={key(c)+"-"+h} className="border p-2">{h}</th>))}</tr></thead>
  <tbody>{rows.map(r=><tr key={r.id} className="even:bg-slate-50"><td className="sticky left-0 border bg-inherit p-2 font-bold">{r.roll}</td><td className="max-w-44 border p-2">{r.name}</td>{examType==="Regular"&&<td className="border p-1"><input type="number" min="0" max="25" step="0.5" value={r.boardViva} onChange={e=>updateRow(r.id,{boardViva:e.target.value,dirty:true})} className={field+" w-16"}/></td>}
  {courses.flatMap(c=>{const k=key(c),x=r.cells[k],registration=examType==="Backlog"?<td key={k+"-reg"} className="border text-center"><input type="checkbox" checked={Boolean(r.registered[k])} onChange={()=>toggle(r,c)}/></td>:null;if(!enabled(r,c))return[registration,<td key={k+"-dash"} colSpan={columns(c).length+2} className="border bg-slate-100 p-2 text-center text-lg font-bold text-slate-500">-</td>];const inputs=c.type==="Theory"?[markInput(r,c,"a",x.a),markInput(r,c,"b",x.b),examType==="Backlog"&&!r.nonObe?<td key={k+"-ct-readonly"} className="border bg-slate-100 p-2 text-center font-semibold" title="Loaded from the regular semester result">{x.ct||"-"}</td>:markInput(r,c,"ct",x.ct)]:c.type==="Thesis"?[markInput(r,c,"internal",x.internal),markInput(r,c,"external",x.external),markInput(r,c,"viva",x.viva)]:[markInput(r,c,"sessional",x.sessional)];return[registration,...inputs,<td key={k+"-total"} className="border p-2 text-center font-semibold">{total(x,c,r.boardViva)}</td>,<td key={k+"-grade"} className={"border p-2 text-center font-bold "+(grade(x,c,r.boardViva,examType==="Backlog")==="F"?"text-red-600":"")}>{grade(x,c,r.boardViva,examType==="Backlog")}</td>]})}
  {(()=>{const current=currentTotals(r);return <><td className="border p-2 text-center">{current.gp.toFixed(2)}</td><td className="border p-2 text-center">{current.credit.toFixed(2)}</td><td className="border p-2 text-center font-semibold">{current.credit?(current.gp/current.credit).toFixed(2):"0.00"}</td><td className="border p-2 text-center">{(r.yearlyRegularCredit+current.credit).toFixed(2)}</td><td className="border p-2 text-center">{r.previousGp.toFixed(2)}</td><td className="border p-2 text-center">{r.previousCredit.toFixed(2)}</td><td className="border p-2 text-center font-semibold">{(r.previousGp+current.gp).toFixed(2)}</td><td className="border p-2 text-center font-semibold">{(r.previousCredit+current.credit).toFixed(2)}</td><td className="border p-2 text-center font-semibold">{r.previousCredit+current.credit?formatResultToTwo((r.previousGp+current.gp)/(r.previousCredit+current.credit)):"0.00"}</td></>})()}<td className="w-48 max-w-48 whitespace-normal break-words border p-2 font-semibold text-red-700">{failedFor(r).join(", ")||"-"}</td><td className="w-56 max-w-56 whitespace-normal break-words border p-2 text-amber-700">{needFor(r).join(", ")||"-"}</td></tr>)}</tbody></table></div></fieldset>
  <div className="border-t p-5 text-center"><div className="flex flex-wrap justify-center gap-3"><button disabled={busy} onClick={()=>void submit(false)} className="rounded bg-blue-700 px-7 py-3 font-bold text-white disabled:opacity-50">{busy?"Saving...":"Save Marks"}</button><button disabled={busy} onClick={()=>void submit(true)} className="rounded bg-emerald-700 px-7 py-3 font-bold text-white disabled:opacity-50">{busy?"Submitting...":"Final Submission"}</button></div>{submitted&&<div className="mt-4 flex flex-wrap justify-center gap-2"><Link className="rounded border px-3 py-2" href={examType==="Regular"?"/teacher/result/marks-sheet":"/teacher/result/marks-sheet-backlog"}>Meeting / Marks Sheet</Link><Link className="rounded border px-3 py-2" href={examType==="Regular"?"/teacher/result/result-sheet":"/teacher/result/result-sheet-backlog"}>Result Sheet</Link><Link className="rounded border px-3 py-2" href={examType==="Regular"?"/teacher/result/tabulation-sheet":"/teacher/result/tabulation-sheet-backlog"}>Tabulation Sheet</Link></div>}</div></>}
 </div></section>
}
