"use client";

import { useEffect, useMemo, useState } from "react";
import { Search, ShieldAlert, Trash2 } from "lucide-react";
import type { StudentDirectoryRecord } from "@/lib/storage/studentDirectory";

export default function PermanentStudentDelete() {
  const [students, setStudents] = useState<StudentDirectoryRecord[]>([]);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<StudentDirectoryRecord | null>(null);
  const [password, setPassword] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);
  const [deleting, setDeleting] = useState(false);
  useEffect(() => { fetch("/api/admin/permanent-delete", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setStudents(body.students || []); }).catch((error) => setMessage(error instanceof Error ? error.message : "Unable to load students")).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => { const term = query.trim().toLowerCase(); return students.filter((student) => !term || [student.name, student.rollNo, student.registrationNo, student.series, student.year, student.semester].some((value) => value.toLowerCase().includes(term))).sort((a, b) => a.rollNo.localeCompare(b.rollNo, undefined, { numeric: true })); }, [students, query]);
  async function permanentlyDelete() {
    if (!selected || !password) { setMessage("Enter the admin password to confirm permanent deletion."); return; }
    if (!window.confirm(`Permanently delete ${selected.name} (${selected.rollNo}) and all related academic records? This cannot be undone.`)) return;
    setDeleting(true); setMessage("");
    const response = await fetch("/api/admin/permanent-delete", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ studentId: selected.id, password }) }).catch(() => null);
    if (!response) { setMessage("Unable to reach the server."); setDeleting(false); return; }
    const body = await response.json().catch(() => null) as { error?: string } | null;
    if (!response.ok) { setMessage(body?.error || "Unable to permanently delete student."); setDeleting(false); return; }
    setStudents((current) => current.filter((student) => student.id !== selected.id)); setMessage(`${selected.name} was permanently deleted.`); setSelected(null); setPassword(""); setDeleting(false);
  }
  return <div><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-red-600 text-white"><ShieldAlert className="h-6 w-6"/></span><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-red-600">Restricted action</p><h1 className="text-3xl font-extrabold">Permanent Delete</h1></div></div><p className="mt-3 text-slate-500">Permanently remove a student whose registration has been cancelled. The admin password is required.</p>
  {message&&<p role="status" className={`mt-5 rounded-xl p-4 text-sm font-semibold ${message.includes("permanently deleted")?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{message}</p>}
  <section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b p-5"><Search className="h-5 w-5 text-slate-400"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search name, roll, registration, series, year or semester" className="w-full rounded-lg border border-slate-300 px-4 py-2.5 outline-none focus:border-blue-500"/></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] border-collapse text-sm"><thead className="bg-[#082f57] text-white"><tr>{["Student","Roll No","Registration No","Series","Year","Semester","Action"].map((heading)=><th key={heading} className="px-4 py-3 text-left">{heading}</th>)}</tr></thead><tbody>{filtered.map((student)=><tr key={student.id} className="border-b even:bg-slate-50"><td className="px-4 py-3 font-semibold">{student.name}</td><td className="px-4 py-3">{student.rollNo}</td><td className="px-4 py-3">{student.registrationNo}</td><td className="px-4 py-3">{student.series}</td><td className="px-4 py-3">{student.year}</td><td className="px-4 py-3">{student.semester}</td><td className="px-4 py-3"><button onClick={()=>{setSelected(student);setPassword("");setMessage("")}} className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-3 py-2 font-semibold text-white hover:bg-red-700"><Trash2 className="h-4 w-4"/>Delete</button></td></tr>)}{loading&&<tr><td colSpan={7} className="p-10 text-center text-slate-500">Loading students...</td></tr>}{!loading&&!filtered.length&&<tr><td colSpan={7} className="p-10 text-center text-slate-500">No students found.</td></tr>}</tbody></table></div></section>
  {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-extrabold text-red-700">Confirm permanent deletion</h2><p className="mt-3 text-sm text-slate-600">You are deleting <strong>{selected.name}</strong>, roll <strong>{selected.rollNo}</strong>. All related result and eligibility records will also be removed.</p><label className="mt-5 block text-sm font-semibold">Admin password<input autoFocus type="password" value={password} onChange={(event)=>setPassword(event.target.value)} onKeyDown={(event)=>{if(event.key==="Enter")void permanentlyDelete()}} className="mt-2 w-full rounded-lg border border-slate-300 px-4 py-2.5"/></label><div className="mt-6 flex justify-end gap-3"><button disabled={deleting} onClick={()=>{setSelected(null);setPassword("")}} className="rounded-lg border px-4 py-2.5 font-semibold">Cancel</button><button disabled={deleting||!password} onClick={()=>void permanentlyDelete()} className="rounded-lg bg-red-600 px-4 py-2.5 font-semibold text-white disabled:opacity-50">{deleting?"Deleting...":"Permanently Delete"}</button></div></div></div>}</div>;
}