"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronDown, ChevronRight, LoaderCircle, Search } from "lucide-react";
type Item="lab-report"|"association-fee"|"letter-attestation"|"equivalent-certificate";
type Profile={name?:string;email?:string;phone?:string;roll:string;series:string;department:string};
type Payment={id:string;transactionId:string;studentName:string;email:string;phone:string;labReportOption:string;associationYear:number;amount:number;status:string;createdAt:string;paidAt:string|null;profile:Profile|null;verifiedAt:string|null};
type Verified={payment:Payment;profile:Profile|null;verifiedAt:string};
const labAmounts:Record<string,number>={cover:65,main:110,both:175};
function itemDetail(item:Item,p:Payment){if(item==="lab-report")return p.labReportOption==="cover"?"Lab Report Cover":p.labReportOption==="main"?"Main Lab Report":"Lab Report Cover + Main Report";if(item==="association-fee")return `BECM Association Fee â€” Year ${p.associationYear}`;if(item==="letter-attestation")return "Letter of Attestation";return "Equivalent Certificate";}
function itemAmount(item:Item,p:Payment){return item==="lab-report"?(labAmounts[p.labReportOption]||0):item==="association-fee"?750:200;}
export default function StaffStudentPaymentMonitor({item,title}:{item:Item;title:string}){
 const[payments,setPayments]=useState<Payment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[code,setCode]=useState(""),[verifying,setVerifying]=useState(false),[verified,setVerified]=useState<Verified|null>(null),[expandedSeries,setExpandedSeries]=useState<Set<string>>(()=>new Set());
 useEffect(()=>{const c=new AbortController();fetch(`/api/staff/student-payments?item=${item}`,{cache:"no-store",signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load payments");setPayments(d.payments||[])}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:"Unable to load payments")}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[item]);
 async function verify(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setVerified(null);setVerifying(true);try{const response=await fetch("/api/staff/student-payments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({item,code})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to verify code");setVerified(data);setCode("");setPayments(current=>current.map(payment=>payment.id===data.payment.id?{...payment,verifiedAt:data.verifiedAt}:payment));}catch(e){setError(e instanceof Error?e.message:"Unable to verify code");}finally{setVerifying(false)}}
 const filtered=useMemo(()=>payments.filter(p=>(status==="all"||p.status===status)&&[p.studentName,p.email,p.phone,p.profile?.roll,p.profile?.series,p.transactionId].some(v=>v?.toLowerCase().includes(query.toLowerCase()))),[payments,query,status]);
 const paid=payments.filter(p=>p.status==="PAID"),collected=paid.reduce((sum,p)=>sum+itemAmount(item,p),0);
 const associationGroups=useMemo(()=>{const groups=new Map<string,Map<string,{roll:string;years:Set<number>}>>();for(const payment of payments){if(payment.status!=="PAID")continue;const series=payment.profile?.series||"Series not provided",roll=payment.profile?.roll||"Roll not provided";if(!groups.has(series))groups.set(series,new Map());const rows=groups.get(series)!;if(!rows.has(roll))rows.set(roll,{roll,years:new Set()});if(payment.associationYear>=1&&payment.associationYear<=4)rows.get(roll)!.years.add(payment.associationYear);}return Array.from(groups.entries()).sort(([a],[b])=>b.localeCompare(a,undefined,{numeric:true})).map(([series,rows])=>({series,rows:Array.from(rows.values()).sort((a,b)=>a.roll.localeCompare(b.roll,undefined,{numeric:true}))}));},[payments]);
 function toggleSeries(series:string){setExpandedSeries(current=>{const next=new Set(current);if(next.has(series))next.delete(series);else next.add(series);return next;});}
 return <div><h1 className="text-3xl font-extrabold">{title} Payments</h1><p className="mt-2 text-slate-500">Monitor student applications and verify each one-time service code.</p>
 <form onSubmit={verify} className="mt-6 grid gap-4 rounded-2xl border border-blue-200 bg-white p-5 shadow-sm sm:grid-cols-[1fr_220px_auto] sm:items-end"><div><h2 className="text-lg font-bold">Verify {title} code</h2><p className="mt-1 text-sm text-slate-500">The emailed six-digit code can be used only once.</p></div><label className="text-sm font-semibold">Verification code<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} required inputMode="numeric" pattern="\d{6}" maxLength={6} className="mt-2 h-11 w-full rounded-xl border px-4 text-center text-lg tracking-[0.3em]" /></label><button disabled={verifying} className="h-11 rounded-xl bg-blue-600 px-5 font-bold text-white disabled:opacity-60">{verifying?"Verifying...":"Verify Code"}</button></form>
 {verified&&<section className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50/60 p-5"><div className="flex items-center gap-2 text-emerald-800"><CheckCircle2 className="h-6 w-6"/><h2 className="text-xl font-bold">Verified student report</h2></div><div className="mt-4 grid gap-3 rounded-xl bg-white p-4 text-sm sm:grid-cols-2 lg:grid-cols-3"><p><b>Name:</b> {verified.payment.studentName}</p><p><b>Roll:</b> {verified.profile?.roll||"Not provided"}</p><p><b>Series:</b> {verified.profile?.series||"Not provided"}</p><p><b>Department:</b> {verified.profile?.department||"Not provided"}</p><p><b>Email:</b> {verified.payment.email}</p><p><b>Phone:</b> {verified.payment.phone}</p><p><b>Application:</b> {itemDetail(item,verified.payment)}</p><p><b>Item amount:</b> &#2547;{itemAmount(item,verified.payment)}</p><p><b>Total transaction:</b> &#2547;{verified.payment.amount}</p><p><b>Transaction:</b> {verified.payment.transactionId}</p><p><b>Payment status:</b> {verified.payment.status}</p><p><b>Paid:</b> {verified.payment.paidAt?new Date(verified.payment.paidAt).toLocaleString():"Not paid"}</p><p><b>Verified:</b> {new Date(verified.verifiedAt).toLocaleString()}</p></div></section>}
 {item==="association-fee"&&<section className="mt-6"><div className="mb-3"><h2 className="text-xl font-bold">Series-wise Association Fee Summary</h2><p className="mt-1 text-sm text-slate-500">Expand a series to view paid years by roll number.</p></div><div className="space-y-3">{associationGroups.map(group=>{const open=expandedSeries.has(group.series);return <article key={group.series} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><button type="button" onClick={()=>toggleSeries(group.series)} className="flex w-full items-center justify-between px-5 py-4 text-left"><span><b>Series {group.series}</b><span className="ml-3 text-sm font-normal text-slate-500">{group.rows.length} student{group.rows.length===1?"":"s"}</span></span>{open?<ChevronDown className="h-5 w-5"/>:<ChevronRight className="h-5 w-5"/>}</button>{open&&<div className="overflow-x-auto border-t"><table className="w-full min-w-[650px] text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3 text-center">SL No.</th><th className="px-4 py-3 text-left">Roll Number</th>{[1,2,3,4].map(year=><th key={year} className="px-4 py-3 text-center">Year {year}</th>)}</tr></thead><tbody className="divide-y">{group.rows.map((row,index)=><tr key={row.roll}><td className="px-4 py-3 text-center">{index+1}</td><td className="px-4 py-3 font-semibold">{row.roll}</td>{[1,2,3,4].map(year=><td key={year} className="px-4 py-3 text-center">{row.years.has(year)?<span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Paid</span>:<span className="text-slate-400">—</span>}</td>)}</tr>)}</tbody></table></div>}</article>})}{!loading&&!associationGroups.length&&<p className="rounded-2xl border bg-white p-8 text-center text-slate-500">No Association Fee records found.</p>}</div></section>} <div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Applications</p><p className="mt-2 text-3xl font-bold">{payments.length}</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Paid</p><p className="mt-2 text-3xl font-bold text-emerald-700">{paid.length}</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Item amount collected</p><p className="mt-2 text-3xl font-bold text-blue-700">&#2547;{collected.toLocaleString()}</p></div></div>
 <div className="mt-5 flex flex-col gap-3 rounded-2xl border bg-white p-4 shadow-sm sm:flex-row"><label className="relative flex-1"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="h-11 w-full rounded-xl border pl-12 pr-4" placeholder="Search student, roll, email or transaction"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="h-11 rounded-xl border px-4"><option value="all">All statuses</option><option value="PAID">Paid</option><option value="PENDING">Pending</option><option value="FAILED">Failed</option><option value="CANCELLED">Cancelled</option><option value="INIT_FAILED">Initialization failed</option></select></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
 {loading?<div className="flex h-56 items-center justify-center"><LoaderCircle className="h-8 w-8 animate-spin text-blue-600"/></div>:<div className="mt-5 overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-4">Student</th><th className="px-4 py-4">Roll / Series</th><th className="px-4 py-4">Application</th><th className="px-4 py-4">Item amount</th><th className="px-4 py-4">Transaction total</th><th className="px-4 py-4">Transaction</th><th className="px-4 py-4">Status</th><th className="px-4 py-4">Verification</th><th className="px-4 py-4">Submitted / Paid</th></tr></thead><tbody className="divide-y">{filtered.map(p=><tr key={p.id}><td className="px-4 py-4"><p className="font-semibold">{p.studentName}</p><p className="text-xs text-slate-500">{p.email}<br/>{p.phone}</p></td><td className="px-4 py-4">{p.profile?.roll||"Ã¢â‚¬â€"}<br/><span className="text-slate-500">{p.profile?.series||"Ã¢â‚¬â€"}</span></td><td className="px-4 py-4 font-medium">{itemDetail(item,p)}</td><td className="px-4 py-4 font-bold">&#2547;{itemAmount(item,p)}</td><td className="px-4 py-4">&#2547;{p.amount}</td><td className="px-4 py-4 font-mono text-xs">{p.transactionId}</td><td className="px-4 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${p.status==="PAID"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{p.status}</span></td><td className="px-4 py-4">{p.verifiedAt?<span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">Verified</span>:<span className="text-xs text-slate-500">Not verified</span>}</td><td className="px-4 py-4 text-xs">{new Date(p.createdAt).toLocaleString()}<br/><span className="text-slate-500">{p.paidAt?new Date(p.paidAt).toLocaleString():"Not paid"}</span></td></tr>)}{!filtered.length&&<tr><td colSpan={9} className="px-4 py-12 text-center text-slate-500">No matching payments found.</td></tr>}</tbody></table></div>}</div>;
}
