"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Save,Search,UserX} from "lucide-react";
import {academicYears,departmentName,semesters,type OldStudentRecord,type StudentDirectoryRecord} from "@/lib/storage/studentDirectory";
import {syllabusCoursesForExam,type SyllabusCourse,type SyllabusSegment} from "@/lib/storage/syllabuses";
import {cohortSeries,type CourseEligibility} from "@/lib/storage/studentEligibility";
import {loadResultSection} from "@/lib/storage/resultSections";
import type {VivaCohort} from "@/lib/storage/vivaMarks";
const current=String(new Date().getFullYear());
export default function StudentEligibility(){
 const[students,setStudents]=useState<StudentDirectoryRecord[]>([]),[oldStudents,setOldStudents]=useState<OldStudentRecord[]>([]),[saved,setSaved]=useState<CourseEligibility[]>([]),[publications,setPublications]=useState<VivaCohort[]>([]),[selection,setSelection]=useState({examYear:current,academicYear:"1st",semester:"Even"}),[courses,setCourses]=useState<SyllabusCourse[]>([]),[courseId,setCourseId]=useState(""),[checks,setChecks]=useState<Record<string,boolean>>({}),[bulkChecks,setBulkChecks]=useState<Record<string,boolean>>({}),[message,setMessage]=useState("");
 useEffect(()=>{Promise.all([fetch("/api/students/directory?includeHistorical=true",{cache:"no-store"}).then(r=>r.json()),fetch("/api/students/old",{cache:"no-store"}).then(r=>r.json()),fetch("/api/student-eligibility",{cache:"no-store"}).then(r=>r.json()),loadResultSection<VivaCohort[]>("add-viva-marks")]).then(([a,o,c,p])=>{setStudents(a.records||[]);setOldStudents(o.records||[]);setSaved(c.records||[]);setPublications(Array.isArray(p)?p:[])}).catch(()=>setMessage("Unable to load attendance eligibility data."))},[]);
 const series=cohortSeries(selection.examYear,selection.academicYear);const registeredCourseIds=useCallback((student:OldStudentRecord)=>new Set(student.promotions.filter(promotion=>promotion.examYear===selection.examYear&&promotion.academicYear===selection.academicYear&&(promotion.examType==="Backlog"||promotion.semester===selection.semester)).flatMap(promotion=>promotion.courseIds)),[selection.examYear,selection.academicYear,selection.semester]);const promotedSpecial=useMemo(()=>oldStudents.filter(student=>{const registered=registeredCourseIds(student);return courses.some(course=>registered.has(course.id))}),[oldStudents,courses,registeredCourseIds]);const specialIds=useMemo(()=>new Set(promotedSpecial.flatMap(student=>[student.id,student.rollNo.replace(/\s/g,"")])),[promotedSpecial]);const cohort=useMemo(()=>{const byRoll=(a:{rollNo:string},b:{rollNo:string})=>a.rollNo.localeCompare(b.rollNo,undefined,{numeric:true}),regular=students.filter(s=>Number(s.series)<=Number(series)&&s.year===selection.academicYear&&s.semester===selection.semester&&!specialIds.has(s.id)&&!specialIds.has(s.rollNo.replace(/\s/g,""))).sort(byRoll),special=[...promotedSpecial].sort(byRoll);return[...regular,...special]},[students,promotedSpecial,specialIds,series,selection.academicYear,selection.semester]);const selectedCourse=courses.find(c=>c.id===courseId);const studentsForCourse=(id:string)=>cohort.filter(student=>!specialIds.has(student.id)||registeredCourseIds(student as OldStudentRecord).has(id));const courseCohort=selectedCourse?studentsForCourse(selectedCourse.id):cohort;const published=publications.some(item=>item.examYear===selection.examYear&&item.academicYear===selection.academicYear&&item.semester===selection.semester&&item.published);const examYears=Array.from({length:Math.max(1,Number(current)-2018+1)},(_,i)=>String(Number(current)-i));const field="h-9 w-full rounded border border-slate-300 bg-white px-2 text-sm";
 async function searchCourses(){setMessage("");try{const [studentBody,oldStudentBody,syllabusBody,eligibilityBody]=await Promise.all([fetch(`/api/students/directory?includeHistorical=true&refresh=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/students/old?refresh=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/syllabuses?refresh=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/student-eligibility?refresh=${Date.now()}`,{cache:"no-store"}).then(r=>r.json())]);const latestStudents=studentBody.records||[],latestOldStudents=(oldStudentBody.records||[]) as OldStudentRecord[],latestSyllabuses=syllabusBody.syllabuses||[];setStudents(latestStudents);setOldStudents(latestOldStudents);const latestEligibility=(eligibilityBody.records||[]) as CourseEligibility[];setSaved(latestEligibility);const regularCourses=syllabusCoursesForExam(latestSyllabuses as SyllabusSegment[],series,selection.academicYear as SyllabusCourse["year"],selection.semester as SyllabusCourse["semester"]),specialCourseIds=new Set(latestOldStudents.flatMap(student=>student.promotions.filter(promotion=>promotion.examYear===selection.examYear&&promotion.academicYear===selection.academicYear&&(promotion.examType==="Backlog"||promotion.semester===selection.semester)).flatMap(promotion=>promotion.courseIds))),specialCourses=(latestSyllabuses as SyllabusSegment[]).flatMap(segment=>segment.courses).filter(course=>course.semester===selection.semester&&specialCourseIds.has(course.id)),found=[...regularCourses,...specialCourses].filter((course,index,all)=>all.findIndex(candidate=>candidate.id===course.id)===index);setCourses(found);setCourseId("");setChecks({});const matching=found.map(course=>latestEligibility.find(item=>item.examYear===selection.examYear&&item.academicYear===selection.academicYear&&item.semester===selection.semester&&item.courseId===course.id));const fullyIneligible=matching.length===found.length&&matching.every(Boolean)?(matching[0]?.students||[]).filter(student=>student.eligible===false&&matching.every(record=>record?.students.find(candidate=>candidate.studentId===student.studentId)?.eligible===false)).map(student=>student.studentId):[];setBulkChecks(Object.fromEntries(fullyIneligible.map(studentId=>[studentId,true])));setMessage(published?"Result has already been published. Eligibility changes are not allowed.":found.length?"":`No syllabus courses found for series ${series}.`)}catch{setMessage("Unable to refresh students from Neon.")}}
 function choose(id:string){setCourseId(id);const record=saved.find(x=>x.examYear===selection.examYear&&x.academicYear===selection.academicYear&&x.semester===selection.semester&&x.courseId===id);setChecks(Object.fromEntries(studentsForCourse(id).map(student=>[student.id,record?.students.find(x=>x.studentId===student.id)?.eligible??true])))}
 async function markSelectedNotEligible(){
  if(published){setMessage("Result has already been published. Eligibility changes are not allowed.");return}
  const selectedIds=cohort.filter(student=>bulkChecks[student.id]).map(student=>student.id);
  if(!selectedIds.length){setMessage("Select at least one student.");return}
  if(!courses.length){setMessage("Search courses first.");return}
  const selectedSet=new Set(selectedIds),updatedAt=new Date().toISOString();
  const records:CourseEligibility[]=courses.map(course=>{const existing=saved.find(item=>item.examYear===selection.examYear&&item.academicYear===selection.academicYear&&item.semester===selection.semester&&item.courseId===course.id);const eligibilityByStudent=new Map((existing?.students||[]).map(student=>[student.studentId,student.eligible]));studentsForCourse(course.id).forEach(student=>eligibilityByStudent.set(student.id,selectedSet.has(student.id)?false:(eligibilityByStudent.get(student.id)??true)));return{...selection,courseId:course.id,courseCode:course.code,courseTitle:course.title,students:Array.from(eligibilityByStudent,([studentId,eligible])=>({studentId,eligible})),updatedAt}});
  const response=await fetch("/api/student-eligibility",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({records,registerForBacklog:true})});
  const body=await response.json().catch(()=>null);
  if(!response.ok){setMessage(body?.error||"Unable to save bulk eligibility.");return}
  setSaved(body.records||[]);setBulkChecks({});
  if(courseId){const active=(body.records as CourseEligibility[]).find(item=>item.examYear===selection.examYear&&item.academicYear===selection.academicYear&&item.semester===selection.semester&&item.courseId===courseId);setChecks(Object.fromEntries(studentsForCourse(courseId).map(student=>[student.id,active?.students.find(item=>item.studentId===student.id)?.eligible??true])))}
  setMessage(`${selectedIds.length} student${selectedIds.length===1?"":"s"} marked non eligible for all ${courses.length} courses and saved in Neon.`)
 }
 async function save(){if(published){setMessage("Result has already been published. Eligibility changes are not allowed.");return}if(!selectedCourse){setMessage("Select a course first.");return}const record:CourseEligibility={...selection,courseId:selectedCourse.id,courseCode:selectedCourse.code,courseTitle:selectedCourse.title,students:courseCohort.map(s=>({studentId:s.id,eligible:checks[s.id]??true})),updatedAt:new Date().toISOString()};const r=await fetch("/api/student-eligibility",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(record)});const b=await r.json();if(!r.ok){setMessage(b.error);return}setSaved(b.records);setMessage("Attendance eligibility saved successfully in Neon.")}
 return <section className="min-h-screen bg-[#f7f9fd] p-4"><div className="border-t border-[#082f57] bg-white shadow-sm"><div className="border-b border-[#082f57] p-4 text-center"><h1 className="text-2xl font-bold">Student Attendance Eligibility</h1><p className="text-sm text-slate-500">Checked means at least 50% attendance. Untick only students below 50%.</p></div><div className="grid gap-4 border-b border-[#082f57] p-5 md:grid-cols-2"><label className="grid items-center gap-3 sm:grid-cols-[220px_1fr]">Department<select disabled value={departmentName} className={field}><option>{departmentName}</option></select></label><label className="grid items-center gap-3 sm:grid-cols-[220px_1fr]">Exam Year<select value={selection.examYear} onChange={e=>setSelection({...selection,examYear:e.target.value})} className={field}>{examYears.map(y=><option key={y}>{y}</option>)}</select></label><label className="grid items-center gap-3 sm:grid-cols-[220px_1fr]">Year<select value={selection.academicYear} onChange={e=>setSelection({...selection,academicYear:e.target.value})} className={field}>{academicYears.map(y=><option key={y}>{y}</option>)}</select></label><label className="grid items-center gap-3 sm:grid-cols-[220px_1fr]">Semester<select value={selection.semester} onChange={e=>setSelection({...selection,semester:e.target.value})} className={field}>{semesters.map(s=><option key={s}>{s}</option>)}</select></label></div><div className="grid gap-4 border-b border-[#082f57] p-5 md:grid-cols-[240px_1fr]"><button onClick={()=>void searchCourses()} className="w-fit rounded bg-green-600 px-4 py-2 font-semibold text-white"><Search className="mr-1 inline h-4 w-4"/>Search Courses</button><select value={courseId} onChange={e=>choose(e.target.value)} className={field}><option value="">Select Course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.code} - {c.title}</option>)}</select></div>{published&&<div className="mx-5 mt-4 rounded bg-red-500 px-4 py-3 text-center font-bold text-white">Result has already been published. Eligibility changes are not allowed.</div>}{message&&<p className={`m-5 rounded p-3 font-semibold ${message.includes("successfully")?"bg-green-50 text-green-700":"bg-red-50 text-red-700"}`}>{message}</p>}
 {courses.length>0&&!selectedCourse&&<div className="border-b border-[#082f57] p-5"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Bulk Non-Eligibility</h2><p className="text-sm text-slate-500">Tick one or more students to mark them non eligible in every course under this examination selection.</p></div><span className="rounded bg-blue-50 px-3 py-1 text-sm font-semibold text-blue-700">{courses.length} courses</span></div><div className="max-h-80 overflow-auto border"><table className="w-full min-w-[750px] border-collapse text-sm"><thead className="sticky top-0 bg-[#082f57] text-white"><tr><th className="border p-3"><input aria-label="Select all students" type="checkbox" disabled={published} checked={cohort.length>0&&cohort.every(student=>bulkChecks[student.id])} onChange={event=>setBulkChecks(Object.fromEntries(cohort.map(student=>[student.id,event.target.checked])))} className="h-4 w-4"/></th><th className="border p-3">Sl.</th><th className="border p-3">Student Name</th><th className="border p-3">Roll No</th><th className="border p-3">Registration No</th><th className="border p-3">Registration Type</th></tr></thead><tbody>{cohort.map((student,index)=><tr key={student.id} className="even:bg-slate-50"><td className="border p-3 text-center"><input aria-label={`Select ${student.name}`} type="checkbox" disabled={published} checked={bulkChecks[student.id]??false} onChange={event=>setBulkChecks({...bulkChecks,[student.id]:event.target.checked})} className="h-4 w-4"/></td><td className="border p-3 text-center">{index+1}</td><td className="border p-3">{student.name}</td><td className="border p-3">{student.rollNo}</td><td className="border p-3">{student.registrationNo}</td><td className="border p-3 text-center"><span className={`rounded-full px-3 py-1 text-xs font-bold ${specialIds.has(student.id)?"bg-amber-100 text-amber-800":"bg-blue-100 text-blue-700"}`}>{specialIds.has(student.id)?"Non-OBE":"OBE"}</span></td></tr>)}</tbody></table></div><div className="mt-4 text-center"><button type="button" disabled={published} onClick={()=>void markSelectedNotEligible()} className="rounded bg-red-600 px-5 py-2 font-bold text-white hover:bg-red-700"><UserX className="mr-1 inline h-4 w-4"/>Mark Selected Non Eligible for All Courses</button></div></div>}
 {selectedCourse&&<div className="p-5"><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-bold">{selectedCourse.code} - {selectedCourse.title}</h2><span className="rounded bg-blue-50 px-3 py-1 text-sm font-semibold text-blue-700">Series {series} / {courseCohort.length} students</span></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] border-collapse text-sm"><thead className="bg-[#082f57] text-white"><tr><th className="border p-3">Sl.</th><th className="border p-3">Student Name</th><th className="border p-3">Roll No</th><th className="border p-3">Registration No</th><th className="border p-3">Registration Type</th><th className="border p-3">Attendance = 50%</th><th className="border p-3">Eligibility</th></tr></thead><tbody>{courseCohort.map((s,i)=><tr key={s.id} className="even:bg-slate-50"><td className="border p-3 text-center">{i+1}</td><td className="border p-3">{s.name}</td><td className="border p-3">{s.rollNo}</td><td className="border p-3">{s.registrationNo}</td><td className="border p-3 text-center"><span className={`rounded-full px-3 py-1 text-xs font-bold ${specialIds.has(s.id)?"bg-amber-100 text-amber-800":"bg-blue-100 text-blue-700"}`}>{specialIds.has(s.id)?"Non-OBE":"OBE"}</span></td><td className="border p-3 text-center"><input type="checkbox" disabled={published} checked={checks[s.id]??true} onChange={e=>setChecks({...checks,[s.id]:e.target.checked})} className="h-4 w-4"/></td><td className="border p-3 text-center"><span className={`rounded-full px-3 py-1 text-xs font-bold ${(checks[s.id]??true)?"bg-green-100 text-green-700":"bg-red-100 text-red-700"}`}>{(checks[s.id]??true)?"Eligible":"Non Eligible"}</span></td></tr>)}{!courseCohort.length&&<tr><td colSpan={7} className="p-10 text-center text-slate-500">No students found for series {series}.</td></tr>}</tbody></table></div><div className="mt-5 text-center"><button disabled={published} onClick={()=>void save()} className="rounded bg-green-600 px-5 py-2 font-bold text-white"><Save className="mr-1 inline h-4 w-4"/>Save Eligibility</button></div></div>}</div></section>}
