"use client";
import {useEffect,useMemo,useState} from "react";
import {Save,Search} from "lucide-react";
import {academicYears,departmentName,semesters,type StudentDirectoryRecord} from "@/lib/storage/studentDirectory";
import type {SyllabusCourse,SyllabusSegment} from "@/lib/storage/syllabuses";
import {cohortSeries,type CourseEligibility} from "@/lib/storage/studentEligibility";
const current=String(new Date().getFullYear());
export default function StudentEligibility(){
 const[students,setStudents]=useState<StudentDirectoryRecord[]>([]),[saved,setSaved]=useState<CourseEligibility[]>([]),[selection,setSelection]=useState({examYear:current,academicYear:"1st",semester:"Even"}),[courses,setCourses]=useState<SyllabusCourse[]>([]),[courseId,setCourseId]=useState(""),[checks,setChecks]=useState<Record<string,boolean>>({}),[message,setMessage]=useState("");
 useEffect(()=>{Promise.all([fetch("/api/students/directory",{cache:"no-store"}).then(r=>r.json()),fetch("/api/student-eligibility",{cache:"no-store"}).then(r=>r.json())]).then(([a,c])=>{setStudents(a.records||[]);setSaved(c.records||[])}).catch(()=>setMessage("Unable to load attendance eligibility data."))},[]);
 const series=cohortSeries(selection.examYear,selection.academicYear);const cohort=useMemo(()=>students.filter(s=>Number(s.series)<=Number(series)&&s.year===selection.academicYear&&s.semester===selection.semester).sort((a,b)=>{const groupA=a.series===series?0:1,groupB=b.series===series?0:1;return groupA-groupB||a.rollNo.localeCompare(b.rollNo,undefined,{numeric:true})}),[students,series,selection.academicYear,selection.semester]);const selectedCourse=courses.find(c=>c.id===courseId);const examYears=Array.from({length:Math.max(1,Number(current)-2018+1)},(_,i)=>String(Number(current)-i));const field="h-9 w-full rounded border border-slate-300 bg-white px-2 text-sm";
 async function searchCourses(){setMessage("");try{const [studentBody,syllabusBody,eligibilityBody]=await Promise.all([fetch(`/api/students/directory?refresh=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/syllabuses?refresh=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/student-eligibility?refresh=${Date.now()}`,{cache:"no-store"}).then(r=>r.json())]);const latestStudents=studentBody.records||[],latestSyllabuses=syllabusBody.syllabuses||[];setStudents(latestStudents);setSaved(eligibilityBody.records||[]);const syllabus=latestSyllabuses.find((s:SyllabusSegment)=>Number(series)>=Number(s.fromSeries)&&Number(series)<=Number(s.toSeries));const found=syllabus?.courses.filter((c:SyllabusCourse)=>c.year===selection.academicYear&&c.semester===selection.semester)||[];setCourses(found);setCourseId("");setChecks({});setMessage(found.length?"":`No syllabus courses found for series ${series}.`)}catch{setMessage("Unable to refresh students from Neon.")}}
 function choose(id:string){setCourseId(id);const record=saved.find(x=>x.examYear===selection.examYear&&x.academicYear===selection.academicYear&&x.semester===selection.semester&&x.courseId===id);setChecks(Object.fromEntries(cohort.map(student=>[student.id,record?.students.find(x=>x.studentId===student.id)?.eligible??true])))}
 async function save(){if(!selectedCourse){setMessage("Select a course first.");return}const record:CourseEligibility={...selection,courseId:selectedCourse.id,courseCode:selectedCourse.code,courseTitle:selectedCourse.title,students:cohort.map(s=>({studentId:s.id,eligible:checks[s.id]??true})),updatedAt:new Date().toISOString()};const r=await fetch("/api/student-eligibility",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(record)});const b=await r.json();if(!r.ok){setMessage(b.error);return}setSaved(b.records);setMessage("Attendance eligibility saved successfully in Neon.")}
 return <section className="min-h-screen bg-[#f7f9fd] p-4"><div className="border-t border-[#082f57] bg-white shadow-sm"><div className="border-b border-[#082f57] p-4 text-center"><h1 className="text-2xl font-bold">Student Attendance Eligibility</h1><p className="text-sm text-slate-500">Checked means at least 50% attendance. Untick only students below 50%.</p></div><div className="grid gap-4 border-b border-[#082f57] p-5 md:grid-cols-2"><label className="grid items-center gap-3 sm:grid-cols-[220px_1fr]">Department<select disabled value={departmentName} className={field}><option>{departmentName}</option></select></label><label className="grid items-center gap-3 sm:grid-cols-[220px_1fr]">Exam Year<select value={selection.examYear} onChange={e=>setSelection({...selection,examYear:e.target.value})} className={field}>{examYears.map(y=><option key={y}>{y}</option>)}</select></label><label className="grid items-center gap-3 sm:grid-cols-[220px_1fr]">Year<select value={selection.academicYear} onChange={e=>setSelection({...selection,academicYear:e.target.value})} className={field}>{academicYears.map(y=><option key={y}>{y}</option>)}</select></label><label className="grid items-center gap-3 sm:grid-cols-[220px_1fr]">Semester<select value={selection.semester} onChange={e=>setSelection({...selection,semester:e.target.value})} className={field}>{semesters.map(s=><option key={s}>{s}</option>)}</select></label></div><div className="grid gap-4 border-b border-[#082f57] p-5 md:grid-cols-[240px_1fr]"><button onClick={()=>void searchCourses()} className="w-fit rounded bg-green-600 px-4 py-2 font-semibold text-white"><Search className="mr-1 inline h-4 w-4"/>Search Courses</button><select value={courseId} onChange={e=>choose(e.target.value)} className={field}><option value="">Select Course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.code} - {c.title}</option>)}</select></div>{message&&<p className={`m-5 rounded p-3 font-semibold ${message.includes("successfully")?"bg-green-50 text-green-700":"bg-red-50 text-red-700"}`}>{message}</p>}
 {selectedCourse&&<div className="p-5"><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-bold">{selectedCourse.code} - {selectedCourse.title}</h2><span className="rounded bg-blue-50 px-3 py-1 text-sm font-semibold text-blue-700">Series {series} / {cohort.length} students</span></div><div className="overflow-x-auto"><table className="w-full min-w-[750px] border-collapse text-sm"><thead className="bg-[#082f57] text-white"><tr><th className="border p-3">Sl.</th><th className="border p-3">Student Name</th><th className="border p-3">Roll No</th><th className="border p-3">Registration No</th><th className="border p-3">Attendance = 50%</th><th className="border p-3">Eligibility</th></tr></thead><tbody>{cohort.map((s,i)=><tr key={s.id} className="even:bg-slate-50"><td className="border p-3 text-center">{i+1}</td><td className="border p-3">{s.name}</td><td className="border p-3">{s.rollNo}</td><td className="border p-3">{s.registrationNo}</td><td className="border p-3 text-center"><input type="checkbox" checked={checks[s.id]??true} onChange={e=>setChecks({...checks,[s.id]:e.target.checked})} className="h-4 w-4"/></td><td className="border p-3 text-center"><span className={`rounded-full px-3 py-1 text-xs font-bold ${(checks[s.id]??true)?"bg-green-100 text-green-700":"bg-red-100 text-red-700"}`}>{(checks[s.id]??true)?"Eligible":"Non Eligible"}</span></td></tr>)}{!cohort.length&&<tr><td colSpan={6} className="p-10 text-center text-slate-500">No students found for series {series}.</td></tr>}</tbody></table></div><div className="mt-5 text-center"><button onClick={()=>void save()} className="rounded bg-green-600 px-5 py-2 font-bold text-white"><Save className="mr-1 inline h-4 w-4"/>Save Eligibility</button></div></div>}</div></section>}
