"use client";
const roundSgpa=(value:number)=>(Math.round((value+Number.EPSILON)*100)/100).toFixed(2);
import { appendSpecialStudentPdf } from "@/lib/specialStudentPdf";
import{useEffect,useMemo,useState}from"react";
import{FileDown}from"lucide-react";
import{academicYears,departmentName,oldStudentPromotionForExam,semesters,type OldStudentRecord,type StudentDirectoryRecord}from"@/lib/storage/studentDirectory";
import{cohortSeries,type CourseEligibility}from"@/lib/storage/studentEligibility";
import{loadResultSection}from"@/lib/storage/resultSections";
import{loadTabulators,formatTabulatorDate,type TabulatorRecord}from"@/lib/storage/tabulators";
import{loadExamCommittees,type ExamCommitteeRecord}from"@/lib/storage/examCommittees";
import{defaultSyllabuses,syllabusCoursesForExam,type SyllabusCourse,type SyllabusSegment}from"@/lib/storage/syllabuses";
import type{VivaCohort}from"@/lib/storage/vivaMarks";import{isExpelledStudentIdentity,isStudentSuspendedForExam,type ExpelledStudentRecord}from"@/lib/storage/expelledStudents";
import{completionStatus,GRADUATION_CREDIT,rankedPassedStatus,topTenCompetitionRanks,usesLegacyResultFormat}from"@/lib/resultFormatPolicy";
import{compareResultStudentRolls}from"@/lib/resultStudentOrder";

type Mark={studentId:string;present:boolean;withheld:boolean;partA:string;partB:string;classTestAttendance:string;sessional?:string;internal?:string;external?:string;thesisViva?:string;remarks:string};
type Prepared={examYear:string;academicYear:string;semester:string;courseId:string;courseCode:string;courseTitle:string;courseType?:SyllabusCourse["type"];students:Mark[]};
type Archived={studentId:string;rollNo:string;earnedCredit:number;gradePoints:number;sgpa:string;failedSubjects:string[];registerAgain:string[]};
type Archive={examYear:string;academicYear:string;semester:string;series:string;students:Archived[];resultPublishDate?:string;formatVersion?:"legacy"|"status"};
type ResultHistoryStudent={studentId:string;failedSubjects:string[];registerAgain:string[];totalEarnedCredit:number;totalGradePoints:number;cgpa:string};
type ResultHistory={examYear:string;academicYear:string;semester:string;students:ResultHistoryStudent[];updatedAt:string};
type BacklogMark={studentId:string;rollNo?:string;examYear:string;courseCode:string;marks:string;result?:"Pass"|"Fail"};
const pts:Record<string,number>={"A+":4,A:3.75,"A-":3.5,"B+":3.25,B:3,"B-":2.75,"C+":2.5,C:2.25,D:2,F:0};
const gradeRows=[["80% and above","A+","4.00"],["75% to less than 80%","A","3.75"],["70% to less than 75%","A-","3.50"],["65% to less than 70%","B+","3.25"],["60% to less than 65%","B","3.00"],["55% to less than 60%","B-","2.75"],["50% to less than 55%","C+","2.50"],["45% to less than 50%","C","2.25"],["40% to less than 45%","D","2.00"],["Less than 40%","F","0.00"],["Incomplete","I","-"],["Need to Register Again","-","-"]];
const n=(v?:string)=>Number(v)||0;
const distinct=(values:string[])=>[...new Set(values.filter(Boolean))];
const studentDetailScore=(student:StudentDirectoryRecord)=>(student.fatherName.trim()?8:0)+(student.registrationNo.trim()?4:0)+(student.name&&student.name!=="Historical Student"?2:0)+(student.motherName.trim()?1:0);
const normalizedRoll=(value:string)=>value.replace(/\s/g,"").toLowerCase();
const rollSeries=(rollNo:string)=>rollNo.trim().slice(0,2);
const academicOrder:Record<string,number>={"1st":1,"2nd":2,"3rd":3,"4th":4};
const roundedTwo=(value:number)=>{
 const thousandths=Math.floor((value+1e-10)*1000);
 const hundredths=Math.floor(thousandths/10)+(thousandths%10>=5?1:0);
 return (hundredths/100).toFixed(2);
};
function grade(mark:Mark|undefined,total:number,theory:boolean){if(!mark)return"";if(mark.withheld)return"I";if(!mark.present||theory&&n(mark.partA)+n(mark.partB)<15)return"F";if(total>=80)return"A+";if(total>=75)return"A";if(total>=70)return"A-";if(total>=65)return"B+";if(total>=60)return"B";if(total>=55)return"B-";if(total>=50)return"C+";if(total>=45)return"C";if(total>=40)return"D";return"F"}

export default function TabulationSheet({examType,onExamTypeChange}:{examType:"Regular"|"Backlog";onExamTypeChange:(value:"Regular"|"Backlog")=>void}){
 const current=String(new Date().getFullYear()),years=Array.from({length:Number(current)-2020},(_,i)=>String(Number(current)-i));
 const[students,setStudents]=useState<StudentDirectoryRecord[]>([]),[oldStudents,setOldStudents]=useState<OldStudentRecord[]>([]),[eligibility,setEligibility]=useState<CourseEligibility[]>([]),[syllabuses,setSyllabuses]=useState<SyllabusSegment[]>([]),[prepared,setPrepared]=useState<Prepared[]>([]),[vivas,setVivas]=useState<VivaCohort[]>([]),[archives,setArchives]=useState<Archive[]>([]),[backlogArchives,setBacklogArchives]=useState<Archive[]>([]),[resultHistory,setResultHistory]=useState<ResultHistory[]>([]),[backlogMarks,setBacklogMarks]=useState<BacklogMark[]>([]),[tabulators,setTabulators]=useState<TabulatorRecord[]>([]),[committees,setCommittees]=useState<ExamCommitteeRecord[]>([]),[expelled,setExpelled]=useState<ExpelledStudentRecord[]>([]);
 const[selection,setSelection]=useState({examYear:"2021",academicYear:"1st",semester:"Odd"}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),series=cohortSeries(selection.examYear,selection.academicYear);
 useEffect(()=>{Promise.all([fetch("/api/students/directory?includeHistorical=true",{cache:"no-store"}).then(r=>r.json()),fetch("/api/student-eligibility",{cache:"no-store"}).then(r=>r.json()),fetch("/api/syllabuses",{cache:"no-store"}).then(r=>r.json()),loadResultSection<Prepared[]>("prepare-result"),loadResultSection<VivaCohort[]>("add-viva-marks"),loadResultSection<Archive[]>("marks-sheet"),loadResultSection<Archive[]>("marks-sheet-backlog"),loadResultSection<ResultHistory[]>("result-sheet"),loadResultSection<BacklogMark[]>("prepare-result-backlog"),loadTabulators(),loadExamCommittees(),fetch("/api/students/old",{cache:"no-store"}).then(r=>r.json()),fetch("/api/expelled-students",{cache:"no-store"}).then(r=>r.json())]).then(([a,b,c,d,e,f,fb,k,j,g,h,i,x])=>{setStudents(a.records||[]);setOldStudents(i.records||[]);setEligibility(b.records||[]);setSyllabuses(c.syllabuses||[]);setPrepared(d||[]);setVivas(e||[]);setArchives(f||[]);setBacklogArchives(fb||[]);setResultHistory(k||[]);setBacklogMarks(j||[]);setTabulators(g);setCommittees(h);setExpelled(x.records||[]);setMessage("")}).catch(()=>setMessage("Unable to load tabulation data from Neon.")).finally(()=>setLoading(false))},[]);
 const courses=useMemo(()=>{const loaded=syllabusCoursesForExam(syllabuses,series,selection.academicYear as SyllabusCourse["year"],selection.semester as SyllabusCourse["semester"]);return loaded.length?loaded:syllabusCoursesForExam(defaultSyllabuses,series,selection.academicYear as SyllabusCourse["year"],selection.semester as SyllabusCourse["semester"])},[syllabuses,series,selection]);
 const selectedExamStudentIds=useMemo(()=>new Set(eligibility.filter(record=>record.examYear===selection.examYear&&record.academicYear===selection.academicYear&&record.semester===selection.semester&&courses.some(course=>course.id===record.courseId)).flatMap(record=>record.students.map(student=>student.studentId))),[eligibility,courses,selection]);
 const nonObeIdentityKeys=useMemo(()=>new Set(oldStudents.filter(student=>Boolean(oldStudentPromotionForExam(student,selection.examYear,selection.academicYear,selection.semester,"Regular"))).flatMap(student=>[`id:${student.id}`,`roll:${normalizedRoll(student.rollNo)}`])),[oldStudents,selection]);
 const cohort=useMemo(()=>{const eligible=students.filter(s=>Number(s.series)>=2020&&Number(s.series)<=Number(series)&&s.year===selection.academicYear&&(s.semester===selection.semester||selectedExamStudentIds.has(s.id))&&!nonObeIdentityKeys.has(`id:${s.id}`)&&!nonObeIdentityKeys.has(`roll:${normalizedRoll(s.rollNo)}`)&&!expelled.some(record=>isExpelledStudentIdentity(record,s)&&isStudentSuspendedForExam(record,selection.examYear,selection.academicYear,selection.semester))),byRoll=new Map<string,StudentDirectoryRecord>();eligible.forEach(student=>{const key=normalizedRoll(student.rollNo);if(!byRoll.has(key))byRoll.set(key,student)});const resolved=[...byRoll.values()].map(student=>{const details=students.filter(candidate=>normalizedRoll(candidate.rollNo)===normalizedRoll(student.rollNo)).sort((a,b)=>studentDetailScore(b)-studentDetailScore(a))[0];return details?{...student,name:details.name||student.name,registrationNo:details.registrationNo||student.registrationNo,fatherName:details.fatherName||student.fatherName,motherName:details.motherName||student.motherName,localGuardian:details.localGuardian||student.localGuardian}:student}),seriesCounts=new Map<string,number>();resolved.forEach(student=>{const key=rollSeries(student.rollNo);seriesCounts.set(key,(seriesCounts.get(key)||0)+1)});return resolved.sort((a,b)=>compareResultStudentRolls(a.rollNo,b.rollNo,selection.examYear,selection.academicYear))},[students,series,selection,selectedExamStudentIds,nonObeIdentityKeys,expelled]);
 const archive=archives.find(a=>a.examYear===selection.examYear&&a.academicYear===selection.academicYear&&a.semester===selection.semester),tabulator=tabulators.find(r=>r.examType==="Regular"&&r.examYear===selection.examYear&&r.academicYear===selection.academicYear&&r.semester===selection.semester),committee=committees.find(r=>r.examType==="Regular"&&r.examYear===selection.examYear&&r.academicYear===selection.academicYear&&r.semester===selection.semester);const legacyFormat=archive?.formatVersion?archive.formatVersion==="legacy":usesLegacyResultFormat(archive?.resultPublishDate||committee?.resultPublishDate);
 function courseGrade(id:string,c:SyllabusCourse){const eligible=eligibility.find(r=>r.examYear===selection.examYear&&r.academicYear===selection.academicYear&&r.semester===selection.semester&&r.courseId===c.id)?.students.find(s=>s.studentId===id)?.eligible??true;if(!eligible)return"-";const mark=prepared.find(r=>r.examYear===selection.examYear&&r.academicYear===selection.academicYear&&r.semester===selection.semester&&r.courseId===c.id)?.students.find(s=>s.studentId===id),theory=c.type==="Theory",thesis=c.type==="Thesis",viva=vivas.find(r=>r.examYear===selection.examYear&&r.academicYear===selection.academicYear&&r.semester===selection.semester)?.students.find(s=>s.id===id),total=mark?Math.round(theory?(mark.present?n(mark.partA)+n(mark.partB):0)+n(mark.classTestAttendance):thesis?n(mark.internal)+n(mark.external)+n(mark.thesisViva):n(mark.sessional)+(viva?.present?n(viva.marks):0)):0;return grade(mark,total,theory)}
 function summary(student:StudentDirectoryRecord){const sameStudent=(row:Archived)=>row.studentId===student.id||normalizedRoll(row.rollNo)===normalizedRoll(student.rollNo),grades=courses.map(c=>courseGrade(student.id,c)),saved=archive?.students.find(sameStudent),earned=saved?.earnedCredit??courses.reduce((a,c,i)=>a+(grades[i]&&!"F-I".includes(grades[i])&&grades[i]!=="-"?n(c.credit):0),0),quality=saved?.gradePoints??courses.reduce((a,c,i)=>a+(pts[grades[i]]||0)*n(c.credit),0),isPrior=(a:{examYear:string;academicYear:string;semester:string})=>Number(a.examYear)!==Number(selection.examYear)?Number(a.examYear)<Number(selection.examYear):academicOrder[a.academicYear]!==academicOrder[selection.academicYear]?academicOrder[a.academicYear]<academicOrder[selection.academicYear]:a.semester==="Odd"&&selection.semester==="Even",previous=[...archives,...backlogArchives].filter(isPrior).map(a=>a.students.find(sameStudent)).filter((row):row is Archived=>Boolean(row)),previousCredit=previous.reduce((a,s)=>a+s.earnedCredit,0),previousQuality=previous.reduce((a,s)=>a+s.gradePoints,0),priorPublished=resultHistory.filter(isPrior).sort((left,right)=>Number(right.examYear)-Number(left.examYear)||academicOrder[right.academicYear]-academicOrder[left.academicYear]||(right.semester==="Even"?1:0)-(left.semester==="Even"?1:0)).map(record=>record.students.find(row=>row.studentId===student.id)).find(Boolean),failedSet=new Set((priorPublished?.failedSubjects||previous.flatMap(row=>row.failedSubjects)).map(normalizedRoll)),registerSet=new Set((priorPublished?.registerAgain||previous.flatMap(row=>row.registerAgain)).map(normalizedRoll)),labels=new Map<string,string>();[...previous.flatMap(row=>[...row.failedSubjects,...row.registerAgain]),...(priorPublished?[...priorPublished.failedSubjects,...priorPublished.registerAgain]:[]),...courses.map(course=>course.code)].forEach(code=>labels.set(normalizedRoll(code),code));courses.forEach((course,index)=>{const code=normalizedRoll(course.code),letter=grades[index];if(letter==="F"){failedSet.add(code);registerSet.delete(code)}else if(letter==="-"){registerSet.add(code);failedSet.delete(code)}else if(letter&&letter!=="I"){failedSet.delete(code);registerSet.delete(code)}});const clearedCodes=new Set(backlogMarks.filter(mark=>Number(mark.examYear)<Number(selection.examYear)&&(mark.studentId===student.id||normalizedRoll(mark.rollNo||"")===normalizedRoll(student.rollNo))&&mark.result!=="Fail"&&n(mark.marks)>=40).map(mark=>normalizedRoll(mark.courseCode)));clearedCodes.forEach(code=>{failedSet.delete(code);registerSet.delete(code)});const totalCredit=earned+previousCredit,totalQuality=quality+previousQuality;return{grades,earned,quality,gpa:earned?quality/earned:0,previousCredit,previousQuality,totalCredit,totalQuality,cgpa:totalCredit?totalQuality/totalCredit:0,failed:distinct([...failedSet].map(code=>labels.get(code)||code)),register:distinct([...registerSet].map(code=>labels.get(code)||code))}}
 async function generate(){
  if(!courses.length||!tabulator||!committee){setMessage(!courses.length?"No syllabus courses found for this examination.":!tabulator?"No matching tabulator record found.":"No matching examination committee record found.");return}const selectedTabulator=tabulator,selectedCommittee=committee;setBusy(true);setMessage("");
  try{const{jsPDF}=await import("jspdf"),font=async(url:string)=>{const r=await fetch(url);if(!r.ok)throw new Error("Unable to load FreeSerif PDF font.");const b=new Uint8Array(await r.arrayBuffer());let s="";for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(s)},fonts=await Promise.all([font("/fonts/FreeSerif.ttf"),font("/fonts/FreeSerifBold.ttf"),font("/fonts/FreeSerifBoldItalic.ttf")]),doc=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});
   [["FreeSerif.ttf",fonts[0],"normal"],["FreeSerifBold.ttf",fonts[1],"bold"],["FreeSerifBoldItalic.ttf",fonts[2],"bolditalic"]].forEach(f=>{doc.addFileToVFS(f[0],f[1]);doc.addFont(f[0],"FreeSerif",f[2])});
   const W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight(),L=14,R=W-14;
   function cell(x:number,y:number,w:number,h:number,text:string,bold=false,size=7.3,align:"center"|"left"|"right"="center",wrap=true,padding=.7){doc.setLineWidth(.15);doc.rect(x,y,w,h);doc.setFont("FreeSerif",bold?"bold":"normal");doc.setFontSize(size);const explicitLines=text.split("\n"),availableWidth=Math.max(1,w-padding*2),widestLine=Math.max(0,...explicitLines.map(line=>doc.getTextWidth(line))),effectiveSize=!wrap&&widestLine>availableWidth?Math.max(5,size*availableWidth/widestLine):size;doc.setFontSize(effectiveSize);const lines:string[]=wrap?doc.splitTextToSize(text,availableWidth):explicitLines,lh=effectiveSize*.36,sy=y+(h-lines.length*lh)/2+lh*.78;lines.forEach((line,i)=>doc.text(line,align==="left"?x+padding:align==="right"?x+w-padding:x+w/2,sy+i*lh,{align}))}
   function head(){doc.setFont("FreeSerif","bold");doc.setFontSize(8);doc.rect(L,8,44,8);doc.text("Examination Date: "+formatTabulatorDate(selectedCommittee.examDate),L+1,13);doc.text("Heavens Light is Our Guide",W/2,10,{align:"center"});doc.text("Rajshahi University of Engineering & Technology",W/2,14,{align:"center"});doc.text("Tabulation Sheet of B.Sc Engineering "+selection.academicYear+" Year "+selection.semester+" Semester Examination, "+selection.examYear,W/2,18,{align:"center"});doc.text("Department of "+departmentName,W/2,22,{align:"center"});doc.rect(R-44,8,44,20);["BECM",selection.academicYear+" Year",selection.semester+" Semester","Exam "+selection.examYear].forEach((t,i)=>doc.text(t,R-22,13+i*4,{align:"center"}));doc.line(L,29,R,29)}
   function sign(){const sig=(x:number,y:number,w:number,h:number,text:string,bold=false,_size=12,align:"center"|"left"|"right"="center")=>{void _size;cell(x,y,w,h,text,bold,12,align)},y=132,rowH=8,names=[selectedTabulator.chairman,selectedTabulator.member1,selectedTabulator.member2],date=formatTabulatorDate(selectedCommittee.resultPublishDate||selectedTabulator.reportingDate);doc.line(L,y,R,y);sig(L,y+2,16,8,"Sl. No",true);sig(L+16,y+2,52,8,"TABULATORS",true);sig(L+68,y+2,30,8,"SIGNATURE",true);names.forEach((v,i)=>{sig(L,y+10+i*rowH,16,rowH,String(i+1)+".");sig(L+16,y+10+i*rowH,52,rowH,v,false,12,"left");sig(L+68,y+10+i*rowH,30,rowH,"")});sig(L,y+34,16,rowH,"Date");sig(L+16,y+34,52,rowH,date,false,12,"left");sig(L+68,y+34,30,rowH,"");const x=L+99;sig(x,y+2,27,12,"");sig(x+27,y+2,68,12,"EXAMINATION\nCOMMITTEE",true);sig(x+95,y+2,28,12,"SIGNATURE",true);let committeeY=y+14;[["Chairman","Head, BECM"],["Member",selectedCommittee.member1],["Member",selectedCommittee.member2],["Member",selectedCommittee.member3],["Member\n(External)",selectedCommittee.member4],["Date",date]].forEach((v,i)=>{const committeeRowHeight=i===4?11:rowH;sig(x,committeeY,27,committeeRowHeight,v[0]);sig(x+27,committeeY,68,committeeRowHeight,v[1],false,12,"left");sig(x+95,committeeY,28,committeeRowHeight,"");committeeY+=committeeRowHeight});doc.setFont("FreeSerif","bolditalic");doc.setFontSize(9.36);doc.text("Controller of Examinations",x+127,y+43)}
   function foot(page:number,total:number){doc.setFont("FreeSerif","bolditalic");doc.setFontSize(8);doc.text("Page "+page+" of "+total,R,H-8,{align:"right"})}
   const base=[17,13,31],courseArea=60,cw=courses.map(()=>courseArea/Math.max(1,courses.length)),tail=[9,13,9,12,10,13,9,11,9,26.5,26.5],ws=[...base,...cw,...tail];doc.setFont("FreeSerif","normal");doc.setFontSize(7.3);const lineHeight=7.3*.36,remarksColumnWidth=26.5,remarksPadding=1.5,remarksTextWidth=remarksColumnWidth-remarksPadding*2,isFinalSemester=selection.academicYear==="4th"&&selection.semester==="Even",summaries=cohort.map(student=>({student,s:summary(student)})),ranks=topTenCompetitionRanks(summaries.filter(({s})=>s.totalCredit>=GRADUATION_CREDIT).map(({s})=>s.cgpa)),preparedRows=summaries.map(({student,s})=>{const graduated=s.totalCredit>=GRADUATION_CREDIT,status=graduated?(isFinalSemester?rankedPassedStatus(s.cgpa,ranks):completionStatus(s.cgpa,legacyFormat)):s.failed.join(", "),vals=[student.registrationNo+"\n"+student.series+"-"+(Number(student.series)+1),student.rollNo,student.name+"\nS/O "+student.fatherName,...s.grades,s.quality.toFixed(2),s.earned.toFixed(2),roundSgpa(s.gpa),s.earned.toFixed(2),s.previousQuality.toFixed(2),s.previousCredit.toFixed(2),s.totalQuality.toFixed(2),s.totalCredit.toFixed(2),roundedTwo(s.cgpa),status,graduated?"":s.register.join(", ")],remarkLines=graduated?(doc.splitTextToSize(status,remarksColumnWidth*2-remarksPadding*2) as string[]).length:Math.max((doc.splitTextToSize(vals[vals.length-2],remarksTextWidth) as string[]).length,(doc.splitTextToSize(vals[vals.length-1],remarksTextWidth) as string[]).length),rowHeight=Math.max(6.2,...vals.slice(0,-2).map(v=>v.split("\n").length*lineHeight+.8),remarkLines*lineHeight+2);return{vals,rowHeight,graduated}}),dataChunks:{vals:string[];rowHeight:number;graduated:boolean}[][]=[];let chunk:{vals:string[];rowHeight:number;graduated:boolean}[]=[],usedHeight=0;preparedRows.forEach(row=>{if(chunk.length&&usedHeight+row.rowHeight>79){dataChunks.push(chunk);chunk=[];usedHeight=0}chunk.push(row);usedHeight+=row.rowHeight});if(chunk.length)dataChunks.push(chunk);if(!dataChunks.length)dataChunks.push([]);const dataPages=dataChunks.length,pages=2+dataPages;
   head();doc.rect(33,78,W-66,25);doc.setFont("FreeSerif","bold");doc.setFontSize(12);doc.text(series+" SERIES",W/2,87,{align:"center"});doc.setFontSize(18);doc.text(selection.academicYear.toUpperCase()+" YEAR "+selection.semester.toUpperCase()+" SEMESTER EXAMINATION, "+selection.examYear,W/2,96,{align:"center"});sign();foot(1,pages);
   doc.addPage("a4","landscape");head();let x=L,y=36;cell(x,y,134,10,"OFFERED COURSES AND CREDIT",true,18);cell(x+135,y,134,10,"MARKS AND GRADE",true,18);y+=10;[["Course No.",25],["Course Title",94],["Credit",15]].forEach(v=>{cell(x,y,Number(v[1]),8,String(v[0]),true,12);x+=Number(v[1])});x=L+135;[["Marks",78],["Grade",24],["Grade Point",32]].forEach(v=>{cell(x,y,Number(v[1]),8,String(v[0]),true,12);x+=Number(v[1])});let courseY=y+8;courses.forEach(c=>{doc.setFont("FreeSerif","normal");doc.setFontSize(12);const titleLines:string[]=doc.splitTextToSize(c.title,92.6),rowHeight=Math.max(6,titleLines.length*4.32+1.2);cell(L,courseY,25,rowHeight,c.code,false,12,"left");cell(L+25,courseY,94,rowHeight,c.title,false,12,"left");cell(L+119,courseY,15,rowHeight,Number(c.credit).toFixed(2),false,12);courseY+=rowHeight});gradeRows.forEach((g,i)=>{const yy=y+8+i*6;cell(L+135,yy,78,6,g[0],false,12,"left");cell(L+213,yy,24,6,g[1],false,12);cell(L+237,yy,32,6,g[2],false,12)});cell(L,courseY,119,6,"Total Credit",true,12,"right");cell(L+119,courseY,15,6,courses.reduce((a,c)=>a+n(c.credit),0).toFixed(2),false,12);sign();foot(2,pages);
   for(let p=0;p<dataPages;p++){doc.addPage("a4","landscape");head();if(p===0){doc.setFont("FreeSerif","bold");doc.setFontSize(8);doc.text("OBE:",L,27)}const items=dataChunks[p],hs=["Reg. No\n& Session","Roll No.","Student Name",...courses.map(c=>{const match=c.code.match(/^(.*?)(\d+)\s*$/);return match?match[1].trim()+"\n"+match[2]+"\n("+Number(c.credit).toFixed(2)+")":c.code+"\n\n("+Number(c.credit).toFixed(2)+")"}),"GP","Semester\nEarned\nCredit","GPA","Yearly\nEarned\nCredit","Previous\nGP","Previous\nEarned\nCredit","Total\nGP\nEarned","Total\nCredits\nEarned","CGPA"];let xx=L;hs.forEach((h,i)=>{cell(xx,31,ws[i],18,h,true,7.3,"center",false);xx+=ws[i]});cell(xx,31,53,7,"Remarks",true,7.3,"center",false);cell(xx,38,26.5,11,isFinalSemester||!legacyFormat?"Status":"Failed Subjects",true,7.3,"center",false);cell(xx+26.5,38,26.5,11,"Need to Register\nAgain",true,7.3,"center",false);let rowY=49;items.forEach(row=>{xx=L;const regularCount=row.vals.length-2;row.vals.slice(0,regularCount).forEach((v,i)=>{cell(xx,rowY,ws[i],row.rowHeight,v,false,7.3,i===2?"left":"center",false);xx+=ws[i]});if(row.graduated)cell(xx,rowY,ws[regularCount]+ws[regularCount+1],row.rowHeight,row.vals[regularCount],false,7.3,"center",true,1.5);else{cell(xx,rowY,ws[regularCount],row.rowHeight,row.vals[regularCount],false,7.3,"left",true,1.5);xx+=ws[regularCount];cell(xx,rowY,ws[regularCount+1],row.rowHeight,row.vals[regularCount+1],false,7.3,"left",true,1.5)}rowY+=row.rowHeight});sign();foot(p+3,pages)}
   await appendSpecialStudentPdf(doc,selection,"tabulation","Tabulation Sheet",{drawSignature:sign});
   doc.save("tabulation-sheet-"+selection.examYear+"-"+selection.academicYear+"-"+selection.semester+".pdf")
  }catch(error){setMessage(error instanceof Error?error.message:"Unable to generate tabulation sheet.")}finally{setBusy(false)}
 }
 const field="h-9 w-full border border-slate-400 bg-white px-2";
 return <section className="min-h-screen bg-[#f7f7f7] p-1 sm:p-3"><div className="border-t-2 border-[#082f57] bg-white shadow"><header className="border-b-2 border-[#082f57] p-4 text-center"><h1 className="text-2xl font-bold">Tabulation Sheet</h1></header><div className="grid gap-x-14 gap-y-2 p-7 md:grid-cols-2"><label className="grid items-center gap-2 font-semibold sm:grid-cols-[245px_1fr]">Exam Type<select value={examType} onChange={(event) => onExamTypeChange(event.target.value as "Regular" | "Backlog")} className={field}><option value="Regular">Regular</option><option value="Backlog">Backlog</option></select></label><label className="grid items-center gap-2 font-semibold sm:grid-cols-[245px_1fr]">Exam Year<select value={selection.examYear} onChange={e=>setSelection({...selection,examYear:e.target.value})} className={field}>{years.map(v=><option key={v}>{v}</option>)}</select></label><label className="grid items-center gap-2 font-semibold sm:grid-cols-[245px_1fr]">Academic Year<select value={selection.academicYear} onChange={e=>setSelection({...selection,academicYear:e.target.value})} className={field}>{academicYears.map(v=><option key={v}>{v}</option>)}</select></label><label className="grid items-center gap-2 font-semibold sm:grid-cols-[245px_1fr]">Semester<select value={selection.semester} onChange={e=>setSelection({...selection,semester:e.target.value})} className={field}>{semesters.filter(v=>v!=="Short Semester").map(v=><option key={v}>{v}</option>)}</select></label><button disabled={busy||loading} onClick={()=>void generate()} className="mx-auto mt-3 inline-flex rounded bg-sky-500 px-4 py-2 text-white disabled:opacity-50 md:col-span-2"><FileDown className="mr-2 h-4 w-4"/>{loading?"Loading...":busy?"Generating...":"Generate Tabulation Sheet"}</button></div>{message&&<p className="m-4 rounded bg-red-50 p-3 text-red-700">{message}</p>}</div></section>
}
