"use client";
import{useEffect,useMemo,useState}from"react";
import{FileDown}from"lucide-react";
import{academicYears,departmentName,semesters,type StudentDirectoryRecord}from"@/lib/storage/studentDirectory";
import{cohortSeries,type CourseEligibility}from"@/lib/storage/studentEligibility";
import{loadResultSection}from"@/lib/storage/resultSections";
import{loadTabulators,formatTabulatorDate,type TabulatorRecord}from"@/lib/storage/tabulators";
import{loadExamCommittees,type ExamCommitteeRecord}from"@/lib/storage/examCommittees";
import type{SyllabusCourse,SyllabusSegment}from"@/lib/storage/syllabuses";
import type{VivaCohort}from"@/lib/storage/vivaMarks";

type Mark={studentId:string;present:boolean;withheld:boolean;partA:string;partB:string;classTestAttendance:string;sessional?:string;remarks:string};
type Prepared={examYear:string;academicYear:string;semester:string;courseId:string;courseCode:string;courseTitle:string;courseType?:SyllabusCourse["type"];students:Mark[]};
type Archived={studentId:string;rollNo:string;earnedCredit:number;gradePoints:number;sgpa:string;failedSubjects:string[];registerAgain:string[]};
type Archive={examYear:string;academicYear:string;semester:string;series:string;students:Archived[]};
const pts:Record<string,number>={"A+":4,A:3.75,"A-":3.5,"B+":3.25,B:3,"B-":2.75,"C+":2.5,C:2.25,D:2,F:0};
const gradeRows=[["80% and above","A+","4.00"],["75% to less than 80%","A","3.75"],["70% to less than 75%","A-","3.50"],["65% to less than 70%","B+","3.25"],["60% to less than 65%","B","3.00"],["55% to less than 60%","B-","2.75"],["50% to less than 55%","C+","2.50"],["45% to less than 50%","C","2.25"],["40% to less than 45%","D","2.00"],["Less than 40%","F","0.00"],["Incomplete","I","-"],["Need to Register Again","-","-"]];
const n=(v?:string)=>Number(v)||0;
function grade(mark:Mark|undefined,total:number,theory:boolean){if(!mark)return"";if(mark.withheld)return"I";if(!mark.present||theory&&n(mark.partA)+n(mark.partB)<15)return"F";if(total>=80)return"A+";if(total>=75)return"A";if(total>=70)return"A-";if(total>=65)return"B+";if(total>=60)return"B";if(total>=55)return"B-";if(total>=50)return"C+";if(total>=45)return"C";if(total>=40)return"D";return"F"}

export default function TabulationSheet(){
 const current=String(new Date().getFullYear()),years=Array.from({length:Number(current)-2020},(_,i)=>String(Number(current)-i));
 const[students,setStudents]=useState<StudentDirectoryRecord[]>([]),[eligibility,setEligibility]=useState<CourseEligibility[]>([]),[syllabuses,setSyllabuses]=useState<SyllabusSegment[]>([]),[prepared,setPrepared]=useState<Prepared[]>([]),[vivas,setVivas]=useState<VivaCohort[]>([]),[archives,setArchives]=useState<Archive[]>([]),[tabulators,setTabulators]=useState<TabulatorRecord[]>([]),[committees,setCommittees]=useState<ExamCommitteeRecord[]>([]);
 const[selection,setSelection]=useState({examYear:"2021",academicYear:"1st",semester:"Odd"}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),series=cohortSeries(selection.examYear,selection.academicYear);
 useEffect(()=>{Promise.all([fetch("/api/students/directory",{cache:"no-store"}).then(r=>r.json()),fetch("/api/student-eligibility",{cache:"no-store"}).then(r=>r.json()),fetch("/api/syllabuses",{cache:"no-store"}).then(r=>r.json()),loadResultSection<Prepared[]>("prepare-result"),loadResultSection<VivaCohort[]>("add-viva-marks"),loadResultSection<Archive[]>("marks-sheet"),loadTabulators(),loadExamCommittees()]).then(([a,b,c,d,e,f,g,h])=>{setStudents(a.records||[]);setEligibility(b.records||[]);setSyllabuses(c.syllabuses||[]);setPrepared(d||[]);setVivas(e||[]);setArchives(f||[]);setTabulators(g);setCommittees(h)}).catch(()=>setMessage("Unable to load tabulation data from Neon."))},[]);
 const courses=useMemo(()=>syllabuses.find(s=>Number(series)>=Number(s.fromSeries)&&Number(series)<=Number(s.toSeries))?.courses.filter(c=>c.year===selection.academicYear&&c.semester===selection.semester)||[],[syllabuses,series,selection]);
 const cohort=useMemo(()=>students.filter(s=>Number(s.series)<=Number(series)&&s.year===selection.academicYear&&s.semester===selection.semester).sort((a,b)=>(a.series===series?0:1)-(b.series===series?0:1)||a.rollNo.localeCompare(b.rollNo,undefined,{numeric:true})),[students,series,selection]);
 const archive=archives.find(a=>a.examYear===selection.examYear&&a.academicYear===selection.academicYear&&a.semester===selection.semester),tabulator=tabulators.find(r=>r.examType==="Regular"&&r.examYear===selection.examYear&&r.academicYear===selection.academicYear&&r.semester===selection.semester),committee=committees.find(r=>r.examType==="Regular"&&r.examYear===selection.examYear&&r.academicYear===selection.academicYear&&r.semester===selection.semester);
 function courseGrade(id:string,c:SyllabusCourse){const eligible=eligibility.find(r=>r.examYear===selection.examYear&&r.academicYear===selection.academicYear&&r.semester===selection.semester&&r.courseId===c.id)?.students.find(s=>s.studentId===id)?.eligible??true;if(!eligible)return"-";const mark=prepared.find(r=>r.examYear===selection.examYear&&r.academicYear===selection.academicYear&&r.semester===selection.semester&&r.courseId===c.id)?.students.find(s=>s.studentId===id),theory=c.type==="Theory",viva=vivas.find(r=>r.examYear===selection.examYear&&r.academicYear===selection.academicYear&&r.semester===selection.semester)?.students.find(s=>s.id===id),total=mark?Math.round(theory?(mark.present?n(mark.partA)+n(mark.partB):0)+n(mark.classTestAttendance):n(mark.sessional)+(viva?.present?n(viva.marks):0)):0;return grade(mark,total,theory)}
 function summary(student:StudentDirectoryRecord){const grades=courses.map(c=>courseGrade(student.id,c)),saved=archive?.students.find(s=>s.studentId===student.id),earned=saved?.earnedCredit??courses.reduce((a,c,i)=>a+(grades[i]&&!"F-I".includes(grades[i])&&grades[i]!=="-"?n(c.credit):0),0),quality=saved?.gradePoints??courses.reduce((a,c,i)=>a+(pts[grades[i]]||0)*n(c.credit),0),previous=archives.filter(a=>Number(a.examYear)<Number(selection.examYear)).flatMap(a=>a.students.filter(s=>s.studentId===student.id)),previousCredit=previous.reduce((a,s)=>a+s.earnedCredit,0),previousQuality=previous.reduce((a,s)=>a+s.gradePoints,0),totalCredit=earned+previousCredit,totalQuality=quality+previousQuality;return{grades,earned,quality,gpa:earned?quality/earned:0,previousCredit,previousQuality,totalCredit,totalQuality,cgpa:totalCredit?totalQuality/totalCredit:0,failed:saved?.failedSubjects||courses.filter((_,i)=>grades[i]==="F").map(c=>c.code),register:saved?.registerAgain||courses.filter((_,i)=>grades[i]==="-").map(c=>c.code)}}
 async function generate(){
  if(!courses.length||!tabulator||!committee){setMessage(!courses.length?"No syllabus courses found for this examination.":!tabulator?"No matching tabulator record found.":"No matching examination committee record found.");return}const selectedTabulator=tabulator,selectedCommittee=committee;setBusy(true);setMessage("");
  try{const{jsPDF}=await import("jspdf"),font=async(url:string)=>{const r=await fetch(url);if(!r.ok)throw new Error("Unable to load FreeSerif PDF font.");const b=new Uint8Array(await r.arrayBuffer());let s="";for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(s)},fonts=await Promise.all([font("/fonts/FreeSerif.ttf"),font("/fonts/FreeSerifBold.ttf"),font("/fonts/FreeSerifBoldItalic.ttf")]),doc=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});
   [["FreeSerif.ttf",fonts[0],"normal"],["FreeSerifBold.ttf",fonts[1],"bold"],["FreeSerifBoldItalic.ttf",fonts[2],"bolditalic"]].forEach(f=>{doc.addFileToVFS(f[0],f[1]);doc.addFont(f[0],"FreeSerif",f[2])});
   const W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight(),L=14,R=W-14;
   function cell(x:number,y:number,w:number,h:number,text:string,bold=false,size=7.3,align:"center"|"left"|"right"="center",wrap=true){doc.setLineWidth(.15);doc.rect(x,y,w,h);doc.setFont("FreeSerif",bold?"bold":"normal");doc.setFontSize(size);const explicitLines=text.split("\n"),availableWidth=Math.max(1,w-1.4),widestLine=Math.max(0,...explicitLines.map(line=>doc.getTextWidth(line))),effectiveSize=!wrap&&widestLine>availableWidth?Math.max(5,size*availableWidth/widestLine):size;doc.setFontSize(effectiveSize);const lines:string[]=wrap?doc.splitTextToSize(text,availableWidth):explicitLines,lh=effectiveSize*.36,sy=y+(h-lines.length*lh)/2+lh*.78;lines.forEach((line,i)=>doc.text(line,align==="left"?x+.7:align==="right"?x+w-.7:x+w/2,sy+i*lh,{align}))}
   function head(){doc.setFont("FreeSerif","bold");doc.setFontSize(8);doc.rect(L,8,44,8);doc.text("Examination Date: "+formatTabulatorDate(selectedCommittee.examDate),L+1,13);doc.text("Heavens Light is Our Guide",W/2,10,{align:"center"});doc.text("Rajshahi University of Engineering & Technology",W/2,14,{align:"center"});doc.text("Tabulation Sheet of B.Sc Engineering "+selection.academicYear+" Year "+selection.semester+" Semester Examination, "+selection.examYear,W/2,18,{align:"center"});doc.text("Department of "+departmentName,W/2,22,{align:"center"});doc.rect(R-44,8,44,20);["BECM",selection.academicYear+" Year",selection.semester+" Semester","Exam "+selection.examYear].forEach((t,i)=>doc.text(t,R-22,13+i*4,{align:"center"}));doc.line(L,29,R,29)}
   function sign(){const sig=(x:number,y:number,w:number,h:number,text:string,bold=false,_size=12,align:"center"|"left"|"right"="center")=>{void _size;cell(x,y,w,h,text,bold,12,align)},y=132,rowH=8,names=[selectedTabulator.chairman,selectedTabulator.member1,selectedTabulator.member2],date=formatTabulatorDate(selectedCommittee.resultPublishDate||selectedTabulator.reportingDate);doc.line(L,y,R,y);sig(L,y+2,16,8,"Sl. No",true);sig(L+16,y+2,52,8,"TABULATORS",true);sig(L+68,y+2,30,8,"SIGNATURE",true);names.forEach((v,i)=>{sig(L,y+10+i*rowH,16,rowH,String(i+1)+".");sig(L+16,y+10+i*rowH,52,rowH,v,false,12,"left");sig(L+68,y+10+i*rowH,30,rowH,"")});sig(L,y+34,16,rowH,"Date");sig(L+16,y+34,52,rowH,date,false,12,"left");sig(L+68,y+34,30,rowH,"");const x=L+99;sig(x,y+2,27,12,"");sig(x+27,y+2,68,12,"EXAMINATION\nCOMMITTEE",true);sig(x+95,y+2,28,12,"SIGNATURE",true);let committeeY=y+14;[["Chairman","Head, BECM"],["Member",selectedCommittee.member1],["Member",selectedCommittee.member2],["Member",selectedCommittee.member3],["Member\n(External)",selectedCommittee.member4],["Date",date]].forEach((v,i)=>{const committeeRowHeight=i===4?11:rowH;sig(x,committeeY,27,committeeRowHeight,v[0]);sig(x+27,committeeY,68,committeeRowHeight,v[1],false,12,"left");sig(x+95,committeeY,28,committeeRowHeight,"");committeeY+=committeeRowHeight});doc.setFont("FreeSerif","bolditalic");doc.setFontSize(9.36);doc.text("Controller of Examinations",x+127,y+43)}
   function foot(page:number,total:number){doc.setFont("FreeSerif","bolditalic");doc.setFontSize(8);doc.text("Page "+page+" of "+total,R,H-8,{align:"right"})}
   const base=[17,13,31],courseArea=60,cw=courses.map(()=>courseArea/Math.max(1,courses.length)),tail=[9,13,9,12,10,13,9,11,9,26.5,26.5],ws=[...base,...cw,...tail];doc.setFont("FreeSerif","normal");doc.setFontSize(7.3);const lineHeight=7.3*.36,preparedRows=cohort.map(student=>{const s=summary(student),vals=[student.registrationNo+"\n"+student.series+"-"+(Number(student.series)+1),student.rollNo,student.name+"\nS/O "+student.fatherName,...s.grades,s.quality.toFixed(2),s.earned.toFixed(2),s.gpa.toFixed(2),s.earned.toFixed(2),s.previousQuality.toFixed(2),s.previousCredit.toFixed(2),s.totalQuality.toFixed(2),s.totalCredit.toFixed(2),s.cgpa.toFixed(2),s.failed.join(", "),s.register.join(", ")],rowHeight=Math.max(6.2,...vals.map((v,i)=>(i>=vals.length-2?(doc.splitTextToSize(v,Math.max(1,ws[i]-1.4)) as string[]):v.split("\n")).length*lineHeight+.8));return{vals,rowHeight}}),dataChunks:{vals:string[];rowHeight:number}[][]=[];let chunk:{vals:string[];rowHeight:number}[]=[],usedHeight=0;preparedRows.forEach(row=>{if(chunk.length&&usedHeight+row.rowHeight>79){dataChunks.push(chunk);chunk=[];usedHeight=0}chunk.push(row);usedHeight+=row.rowHeight});if(chunk.length)dataChunks.push(chunk);if(!dataChunks.length)dataChunks.push([]);const dataPages=dataChunks.length,pages=2+dataPages;
   head();doc.rect(33,78,W-66,25);doc.setFont("FreeSerif","bold");doc.setFontSize(12);doc.text(series+" SERIES",W/2,87,{align:"center"});doc.setFontSize(18);doc.text(selection.academicYear.toUpperCase()+" YEAR "+selection.semester.toUpperCase()+" SEMESTER EXAMINATION, "+selection.examYear,W/2,96,{align:"center"});sign();foot(1,pages);
   doc.addPage("a4","landscape");head();let x=L,y=36;cell(x,y,134,10,"OFFERED COURSES AND CREDIT",true,18);cell(x+135,y,134,10,"MARKS AND GRADE",true,18);y+=10;[["Course No.",25],["Course Title",94],["Credit",15]].forEach(v=>{cell(x,y,Number(v[1]),8,String(v[0]),true,12);x+=Number(v[1])});x=L+135;[["Marks",78],["Grade",24],["Grade Point",32]].forEach(v=>{cell(x,y,Number(v[1]),8,String(v[0]),true,12);x+=Number(v[1])});let courseY=y+8;courses.forEach(c=>{doc.setFont("FreeSerif","normal");doc.setFontSize(12);const titleLines:string[]=doc.splitTextToSize(c.title,92.6),rowHeight=Math.max(6,titleLines.length*4.32+1.2);cell(L,courseY,25,rowHeight,c.code,false,12,"left");cell(L+25,courseY,94,rowHeight,c.title,false,12,"left");cell(L+119,courseY,15,rowHeight,Number(c.credit).toFixed(2),false,12);courseY+=rowHeight});gradeRows.forEach((g,i)=>{const yy=y+8+i*6;cell(L+135,yy,78,6,g[0],false,12,"left");cell(L+213,yy,24,6,g[1],false,12);cell(L+237,yy,32,6,g[2],false,12)});cell(L,courseY,119,6,"Total Credit",true,12,"right");cell(L+119,courseY,15,6,courses.reduce((a,c)=>a+n(c.credit),0).toFixed(2),false,12);sign();foot(2,pages);
   for(let p=0;p<dataPages;p++){doc.addPage("a4","landscape");head();const items=dataChunks[p],hs=["Reg. No\n& Session","Roll No.","Student Name",...courses.map(c=>{const match=c.code.match(/^(.*?)(\d+)\s*$/);return match?match[1].trim()+"\n"+match[2]+"\n("+Number(c.credit).toFixed(2)+")":c.code+"\n\n("+Number(c.credit).toFixed(2)+")"}),"GP","Semester\nEarned\nCredit","GPA","Yearly\nEarned\nCredit","Previous\nGP","Previous\nEarned\nCredit","Total\nGP\nEarned","Total\nCredits\nEarned","CGPA"];let xx=L;hs.forEach((h,i)=>{cell(xx,31,ws[i],18,h,true,7.3,"center",false);xx+=ws[i]});cell(xx,31,53,7,"Remarks",true,7.3,"center",false);cell(xx,38,26.5,11,"Failed Subjects",true,7.3,"center",false);cell(xx+26.5,38,26.5,11,"Need to Register\nAgain",true,7.3,"center",false);let rowY=49;items.forEach(row=>{xx=L;row.vals.forEach((v,i)=>{cell(xx,rowY,ws[i],row.rowHeight,v,false,7.3,i===2||i>=row.vals.length-2?"left":"center",i>=row.vals.length-2);xx+=ws[i]});rowY+=row.rowHeight});sign();foot(p+3,pages)}
   doc.save("tabulation-sheet-"+selection.examYear+"-"+selection.academicYear+"-"+selection.semester+".pdf")
  }catch(error){setMessage(error instanceof Error?error.message:"Unable to generate tabulation sheet.")}finally{setBusy(false)}
 }
 const field="h-9 w-full border border-slate-400 bg-white px-2";
 return <section className="min-h-screen bg-[#f7f7f7] p-1 sm:p-3"><div className="border-t-2 border-[#082f57] bg-white shadow"><header className="border-b-2 border-[#082f57] p-4 text-center"><h1 className="text-2xl font-bold">Tabulation Sheet</h1></header><div className="grid gap-x-14 gap-y-2 p-7 md:grid-cols-2"><label className="grid items-center gap-2 font-semibold sm:grid-cols-[245px_1fr]">Department<select disabled className={field}><option>{departmentName}</option></select></label><label className="grid items-center gap-2 font-semibold sm:grid-cols-[245px_1fr]">Exam Year<select value={selection.examYear} onChange={e=>setSelection({...selection,examYear:e.target.value})} className={field}>{years.map(v=><option key={v}>{v}</option>)}</select></label><label className="grid items-center gap-2 font-semibold sm:grid-cols-[245px_1fr]">Academic Year<select value={selection.academicYear} onChange={e=>setSelection({...selection,academicYear:e.target.value})} className={field}>{academicYears.map(v=><option key={v}>{v}</option>)}</select></label><label className="grid items-center gap-2 font-semibold sm:grid-cols-[245px_1fr]">Semester<select value={selection.semester} onChange={e=>setSelection({...selection,semester:e.target.value})} className={field}>{semesters.filter(v=>v!=="Short Semester").map(v=><option key={v}>{v}</option>)}</select></label><button disabled={busy} onClick={()=>void generate()} className="mx-auto mt-3 inline-flex rounded bg-sky-500 px-4 py-2 text-white disabled:opacity-50 md:col-span-2"><FileDown className="mr-2 h-4 w-4"/>{busy?"Generating...":"Generate Tabulation Sheet"}</button></div>{message&&<p className="m-4 rounded bg-red-50 p-3 text-red-700">{message}</p>}</div></section>
}