export const resultNavigation = [
  { label: "Tabulators", href: "/teacher/result/tabulators" },
  { label: "Exam Committee", href: "/teacher/result/exam-committee" },
  { label: "Add Viva Marks", href: "/teacher/result/add-viva-marks" },
  { label: "Publish Result", href: "/teacher/result/publish" },
  { label: "Prepare Result", href: "/teacher/result/prepare-result" },
  { label: "Prepare Result (Backlog)", href: "/teacher/result/prepare-result-backlog" },
  { label: "Marks Sheet", href: "/teacher/result/marks-sheet" },
  { label: "Marks Sheet (Backlog)", href: "/teacher/result/marks-sheet-backlog" },
  { label: "Grade Sheet", href: "/teacher/result/grade-sheet" },
  { label: "Result Sheet", href: "/teacher/result/result-sheet" },
  { label: "Exam Result Report", href: "/teacher/result/exam-result-report" },
  { label: "Result Sheet (Backlog)", href: "/teacher/result/result-sheet-backlog" },
  { label: "Tabulation Sheet", href: "/teacher/result/tabulation-sheet" },
  { label: "Tabulation Sheet (Backlog)", href: "/teacher/result/tabulation-sheet-backlog" },
] as const;