import {specialPriorYearlyCredit} from "@/lib/yearlyEarnedCredit";
import { fullyIneligibleForExam } from "@/lib/resultEligibility";
import type{jsPDF}from"jspdf";import type{OldStudentRecord}from"@/lib/storage/studentDirectory";import type{SyllabusCourse,SyllabusSegment}from"@/lib/storage/syllabuses";import{completionStatus,graduationCreditForStudent,statusInsteadOfFailedSubjects,usesLegacyResultFormat}from"@/lib/resultFormatPolicy";import{backlogGrade}from"@/lib/backlogGrading";
const roundSgpa=(value:number)=>(Math.round((value+Number.EPSILON)*100)/100).toFixed(2);
import{formatTabulatorDate}from"@/lib/storage/tabulators";import{compareResultStudentRolls}from"@/lib/resultStudentOrder";
type Selection={examYear:string;academicYear:string;semester:string};type Mark={studentId:string;present:boolean;withheld:boolean;partA:string;partB:string;classTestAttendance:string;sessional?:string;internal?:string;external?:string;thesisViva?:string};type Prepared={examYear:string;academicYear:string;semester:string;courseId:string;students:Mark[]};type Viva={examYear:string;academicYear:string;semester:string;students:Array<{id:string;marks:string;present:boolean}>};type Eligibility={examYear:string;academicYear:string;semester:string;courseId:string;students:Array<{studentId:string;eligible:boolean}>};type CourseChange={courseId:string;before:"failed"|"need-register"|null;after:"failed"|"need-register"|null};type LedgerEntry={examType:"Regular"|"Backlog";examYear:string;academicYear:string;semester:string;applied:boolean;students:Array<{studentId:string;credit?:number;courses:CourseChange[]}>};type Committee={examType:"Regular"|"Backlog";examYear:string;academicYear:string;semester:string;examDate:string};type Mode="marks"|"tabulation"|"result";
const n=(v?:string)=>Number(v)||0,P:Record<string,number>={"A+":4,A:3.75,"A-":3.5,"B+":3.25,B:3,"B-":2.75,"C+":2.5,C:2.25,D:2,F:0},grade=(score:number,m:Mark|undefined,theory:boolean)=>!m?"":m.withheld?"W":!m.present||theory&&n(m.partA)+n(m.partB)<15?"F":score>=80?"A+":score>=75?"A":score>=70?"A-":score>=65?"B+":score>=60?"B":score>=55?"B-":score>=50?"C+":score>=45?"C":score>=40?"D":"F";
const academicOrder:Record<string,number>={"1st":1,"2nd":2,"3rd":3,"4th":4},semesterOrder:Record<string,number>={Odd:1,Even:2,"Short Semester":3,"":4};
const compareExam=(left:{examYear:string;academicYear:string;semester:string},right:Selection)=>Number(left.examYear)-Number(right.examYear)||academicOrder[left.academicYear]-academicOrder[right.academicYear]||semesterOrder[left.semester]-semesterOrder[right.semester];
async function json(url:string){const r=await fetch(url,{cache:"no-store"}),b=await r.json();if(!r.ok)throw Error(b.error||"Unable to load "+url);return b}
export async function appendSpecialStudentPdf(doc:jsPDF,selection:Selection,mode:Mode,title:string,options?:{startY?:number;drawHeader?:()=>void;drawSignature?:()=>void;marksCourseWidths?:Record<string,number>;marksCourseWidthList?:number[];tabulationCourseWidths?:Record<string,number>}){
 const[a,b,c,d,e,f,g]=await Promise.all([json("/api/students/old"),json("/api/syllabuses"),json("/api/result-sections/prepare-result"),json("/api/student-eligibility"),json("/api/result-sections/add-viva-marks"),json("/api/students/old/result-history"),json("/api/exam-committees")]),students=(a.records||[])as OldStudentRecord[],syllabi=(b.syllabuses||[])as SyllabusSegment[],prepared=((c.data||c.records||c)||[])as Prepared[],eligibility=(d.records||[])as Eligibility[],vivas=(e.data||[])as Viva[],ledger=(f.records||[])as LedgerEntry[],committees=(g.data||[])as Committee[],committee=committees.find(item=>item.examType==="Regular"&&item.examYear===selection.examYear&&item.academicYear===selection.academicYear&&item.semester===selection.semester),legacy=usesLegacyResultFormat(committee?.examDate);
 const promotion=(s:OldStudentRecord)=>s.promotions.find(p=>p.examType==="Regular"&&p.examYear===selection.examYear&&p.academicYear===selection.academicYear&&p.semester===selection.semester);
 const cohort=students.filter(s=>{const registered=promotion(s);return Boolean(registered?.courseIds.length)&&!fullyIneligibleForExam(s,students,registered?.courseIds||[],eligibility,selection)}).sort((left,right)=>compareResultStudentRolls(left.rollNo,right.rollNo,selection.examYear,selection.academicYear));if(!cohort.length)return;
 const cohortIds=new Set(cohort.map(s=>s.id)),ids=new Set([...cohort.flatMap(s=>promotion(s)?.courseIds||[]),...eligibility.filter(x=>x.examYear===selection.examYear&&x.academicYear===selection.academicYear&&x.semester===selection.semester&&x.students.some(s=>cohortIds.has(s.studentId)&&s.eligible===false)).map(x=>x.courseId)]),allCourses=syllabi.flatMap(s=>s.courses),courses=[...ids].map(id=>allCourses.find(course=>course.id===id)).filter((course):course is SyllabusCourse=>Boolean(course));
 const outcome=(s:OldStudentRecord,c:SyllabusCourse)=>{const registered=Boolean(promotion(s)?.courseIds.includes(c.id)),nonEligible=registered&&eligibility.find(x=>x.examYear===selection.examYear&&x.academicYear===selection.academicYear&&x.semester===selection.semester&&x.courseId===c.id)?.students.find(x=>x.studentId===s.id)?.eligible===false,m=prepared.find(x=>x.examYear===selection.examYear&&x.academicYear===selection.academicYear&&x.semester===selection.semester&&x.courseId===c.id)?.students.find(x=>x.studentId===s.id),vivaStudent=vivas.find(v=>v.examYear===selection.examYear&&v.academicYear===selection.academicYear&&v.semester===selection.semester)?.students.find(v=>v.id===s.id),viva=vivaStudent?.present?n(vivaStudent.marks):0;if(!registered)return{registered:false,nonEligible:false,m,total:0,letter:"",credit:0,quality:0};const total=m?Math.round(c.type==="Theory"?(m.present?n(m.partA)+n(m.partB):0)+n(m.classTestAttendance):c.type==="Thesis"?n(m.internal)+n(m.external)+n(m.thesisViva):n(m.sessional)+viva):0,baseLetter=nonEligible?"-":selection.semester==="Short Semester"&&m&&!m.withheld&&m.present&&!(c.type==="Theory"&&n(m.partA)+n(m.partB)<15)?backlogGrade(total):grade(total,m,c.type==="Theory"),letter=c.type==="Sessional"&&baseLetter!=="W"&&viva<=0?"F":baseLetter,credit=!nonEligible&&letter&&letter!=="F"&&letter!=="W"?n(c.credit):0;return{registered,nonEligible,m,total,letter,credit,quality:credit*(P[letter]||0)}};
 const outstandingBeforeExam=(student:OldStudentRecord)=>{const statuses=new Map(student.outstandingCourses.map(course=>[course.courseId,course.status]));ledger.filter(entry=>entry.applied&&compareExam(entry,selection)>=0).sort((left,right)=>compareExam(right,selection)-compareExam(left,selection)).forEach(entry=>{const change=entry.students.find(item=>item.studentId===student.id);change?.courses.forEach(course=>course.before===null?statuses.delete(course.courseId):statuses.set(course.courseId,course.before))});return statuses};
 if(mode==="marks"){
  const W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight(),L=12,failedWidth=29,registerWidth=24,remarksWidth=failedWidth+registerWidth,courseBase=courses.map(c=>c.type==="Theory"?20:13.5),fixed=12+7+11+9+remarksWidth,scale=(W-24-fixed)/Math.max(1,courseBase.reduce((a,b)=>a+b,0)),courseWidths=courses.map((course,index)=>options?.marksCourseWidths?.[course.code.replace(/\s/g,"").toLowerCase()]??options?.marksCourseWidthList?.[index]??courseBase[index]*Math.min(1,scale));
  const cell=(x:number,y:number,w:number,h:number,text:string,bold=false,align:"center"|"left"="center")=>{doc.setLineWidth(.15);doc.rect(x,y,w,h);doc.setFont("FreeSerif",bold?"bold":"normal");doc.setFontSize(7.3);const singleLine=/^-?\d+(?:\.\d+)?$/.test(text)||/^(A|B|CT|T\.|Gr\.|Ses|Int\.|Ext\.|Viva)$/.test(text),available=Math.max(1,w-1.6);if(singleLine&&doc.getTextWidth(text)>available)doc.setFontSize(Math.max(5.5,7.3*available/doc.getTextWidth(text)));const lines=singleLine?[text]:doc.splitTextToSize(text||"",available)as string[],lh=2.8,sy=y+(h-lines.length*lh)/2+lh*.78;lines.forEach((line,i)=>doc.text(line,align==="left"?x+.8:x+w/2,sy+i*lh,{align}))};
  const newPage=()=>{doc.addPage("a4","landscape");options?.drawHeader?.();return 30};
  const tableHeader=(headingY:number)=>{doc.setTextColor(0);doc.setFont("FreeSerif","bold");doc.setFontSize(8);doc.text("Non-OBE:",L,headingY);
  let y=headingY+4,x=L;cell(x,y,12,18,"Roll No.",true);x+=12;courses.forEach((course,index)=>{cell(x,y,courseWidths[index],10,course.code+"\n"+Number(course.credit).toFixed(2),true);x+=courseWidths[index]});cell(x,y,7,18,"Viva",true);x+=7;cell(x,y,11,18,"Earned\nCredit",true);x+=11;cell(x,y,9,18,"SGPA",true);x+=9;cell(x,y,remarksWidth,10,"Remarks",true);cell(x,y+10,failedWidth,8,legacy?"Failed Subjects":"Status",true);cell(x+failedWidth,y+10,registerWidth,8,"Need to Register\nAgain",true);x=L+12;courses.forEach((course,index)=>{const labels=course.type==="Theory"?["A","B","CT","T.","Gr."]:["Ses","T.","Gr."],sub=courseWidths[index]/labels.length;labels.forEach(label=>{cell(x,y+10,sub,8,label,true);x+=sub})});y+=18;return y};
  let headingY=options?.startY??30;if(headingY+22+5.35>H-14)headingY=newPage();
  let y=tableHeader(headingY),x=L;
  for(const s of cohort){const results=courses.map(c=>outcome(s,c)),earned=results.reduce((sum,v)=>sum+v.credit,0),quality=results.reduce((sum,v)=>sum+v.quality,0),failedCodes=results.flatMap((v,i)=>v.registered&&v.letter==="F"?[courses[i].code]:[]),failed=legacy?failedCodes.join(", "):statusInsteadOfFailedSubjects(failedCodes),need=results.flatMap((v,i)=>v.nonEligible?[courses[i].code]:[]).join(", "),sgpa=earned?quality/earned:0,viva=vivas.find(v=>v.examYear===selection.examYear&&v.academicYear===selection.academicYear&&v.semester===selection.semester)?.students.find(v=>v.id===s.id),vivaText=viva?.present?viva.marks:"",height=Math.max(5.35,doc.splitTextToSize(failed,failedWidth-1.6).length*2.8+1.2,doc.splitTextToSize(need,registerWidth-1.6).length*2.8+1.2);if(y+height>H-14)y=tableHeader(newPage());x=L;cell(x,y,12,height,s.rollNo);x+=12;results.forEach((v,index)=>{const course=courses[index],blank=!v.registered&&!v.nonEligible,values=course.type==="Theory"?[blank?"":v.nonEligible?"-":v.m?.partA||"",blank?"":v.nonEligible?"-":v.m?.partB||"",blank?"":v.nonEligible?"-":v.m?.classTestAttendance||"",blank?"":v.nonEligible?"-":v.m?String(v.total):"",blank?"":v.letter]:[blank?"":v.nonEligible?"-":v.m?.sessional||"",blank?"":v.nonEligible?"-":v.m?String(v.total):"",blank?"":v.letter],sub=courseWidths[index]/values.length;values.forEach(value=>{cell(x,y,sub,height,String(value));x+=sub})});cell(x,y,7,height,vivaText);x+=7;cell(x,y,11,height,earned.toFixed(2));x+=11;cell(x,y,9,height,roundSgpa(sgpa));x+=9;cell(x,y,failedWidth,height,failed,false,"left");cell(x+failedWidth,y,registerWidth,height,need,false,"left");y+=height}
  return;
 }
 if(mode==="tabulation"){
  const W=doc.internal.pageSize.getWidth(),L=14,R=W-14,courseWidths=courses.map(course=>options?.tabulationCourseWidths?.[course.code.replace(/\s/g,"").toLowerCase()]??Math.min(20,60/Math.max(1,courses.length))),widths=[17,13,31,...courseWidths,9,13,9,12,10,13,9,11,9,26.5,26.5];
  const cell=(x:number,y:number,w:number,h:number,text:string,bold=false,align:"center"|"left"="center",wrap=false,vertical=false)=>{doc.setLineWidth(.15);doc.rect(x,y,w,h);doc.setFont("FreeSerif",bold?"bold":"normal");doc.setFontSize(7.3);const displayText=!wrap&&text.includes("\n(")?text.replace(/\s+/,"\n"):text,available=Math.max(1,(vertical?h:w)-1.4),explicit=displayText.split("\n"),widest=Math.max(0,...explicit.map(line=>doc.getTextWidth(line)));if(!wrap&&widest>available)doc.setFontSize(Math.max(5,7.3*available/widest));const lines=wrap?doc.splitTextToSize(displayText||"",available)as string[]:explicit,lh=doc.getFontSize()*.36;if(vertical){const start=x+(w-lines.length*lh)/2+lh*.78;lines.forEach((line,i)=>doc.text(line,start+i*lh,y+h/2,{align:"center",angle:90}))}else{const sy=y+(h-lines.length*lh)/2+lh*.78;lines.forEach((line,i)=>doc.text(line,align==="left"?x+.7:x+w/2,sy+i*lh,{align}))}};
  const heading=()=>{doc.setFont("FreeSerif","bold");doc.setFontSize(8);doc.rect(L,8,44,8);doc.text("Examination Date: "+formatTabulatorDate(committee?.examDate||""),L+1,13);doc.text("Heavens Light is Our Guide",W/2,10,{align:"center"});doc.text("Rajshahi University of Engineering & Technology",W/2,14,{align:"center"});doc.text("Tabulation Sheet of B.Sc Engineering "+selection.academicYear+" Year "+selection.semester+" Semester Examination, "+selection.examYear,W/2,18,{align:"center"});doc.text("Department of Building Engineering & Construction Management",W/2,22,{align:"center"});doc.rect(R-44,8,44,20);["BECM",selection.academicYear+" Year",selection.semester+" Semester","Exam "+selection.examYear].forEach((text,index)=>doc.text(text,R-22,13+index*4,{align:"center"}));doc.line(L,29,R,29)};
  const headerHeight=18;
  const tableHeader=(y:number,showLabel:boolean)=>{if(showLabel){doc.setFont("FreeSerif","bold");doc.setFontSize(8);doc.text("Non-OBE:",L,y);y+=4}const headers=["Reg. No\n& Session","Roll No.","Student Name",...courses.map(c=>c.code+"\n("+Number(c.credit).toFixed(2)+")"),"GP","Semester\nEarned\nCredit","GPA","Yearly\nEarned\nCredit","Previous\nGP","Previous\nEarned\nCredit","Total\nGP\nEarned","Total\nCredits\nEarned","CGPA"];let x=L;headers.forEach((text,i)=>{cell(x,y,widths[i],headerHeight,text,true,"center",false,false);x+=widths[i]});cell(x,y,53,7,"Remarks",true);cell(x,y+7,26.5,11,legacy?"Failed Subjects":"Status",true);cell(x+26.5,y+7,26.5,11,"Need to Register\nAgain",true);return y+headerHeight};
  const rowData=(s:OldStudentRecord)=>{const results=courses.map(c=>outcome(s,c)),earned=results.reduce((sum,v)=>sum+v.credit,0),quality=results.reduce((sum,v)=>sum+v.quality,0),totalCredit=s.earnedCredit+earned,totalQuality=s.gradePoints+quality,gpa=earned?quality/earned:0,cgpa=totalCredit?totalQuality/totalCredit:0,statuses=outstandingBeforeExam(s);results.forEach((result,index)=>{if(!result.registered)return;const courseId=courses[index].id;if(result.nonEligible)statuses.set(courseId,"need-register");else if(result.letter==="F"||result.letter==="W")statuses.set(courseId,"failed");else if(result.letter)statuses.delete(courseId)});const remaining=[...statuses].map(([courseId,status])=>({courseId,status})),graduated=totalCredit>=graduationCreditForStudent(s),failedCodes=remaining.filter(item=>item.status==="failed").map(item=>allCourses.find(c=>c.id===item.courseId)?.code).filter((code):code is string=>Boolean(code)),failed=graduated?completionStatus(cgpa,legacy):failedCodes.join(", "),need=graduated?"":remaining.filter(item=>item.status==="need-register").map(item=>allCourses.find(c=>c.id===item.courseId)?.code).filter((code):code is string=>Boolean(code)).join(", "),values=[s.registrationNo+"\n"+s.series+"-"+(Number(s.series)+1),s.rollNo,s.name+(s.fatherName?"\nS/O "+s.fatherName:""),...results.map(v=>v.registered?v.letter:""),quality.toFixed(2),earned.toFixed(2),roundSgpa(gpa),(earned+specialPriorYearlyCredit(s,{...selection,examType:"Regular"},ledger)).toFixed(2),s.gradePoints.toFixed(2),s.earnedCredit.toFixed(2),totalQuality.toFixed(2),totalCredit.toFixed(2),cgpa.toFixed(2),failed,need],remarkLines=Math.max((doc.splitTextToSize(failed,25.1)as string[]).length,(doc.splitTextToSize(need,25.1)as string[]).length),rowHeight=Math.max(6.2,...values.slice(0,-2).map(v=>v.split("\n").length*2.63+.8),remarkLines*2.63+.8);return{values,rowHeight,graduated,failed,need}};
  const rows=cohort.map(rowData);
  const newPage=()=>{doc.addPage("a4","landscape");heading();return tableHeader(33,true)};
  const firstBlockHeight=4+headerHeight+(rows[0]?.rowHeight||0);let y:number;if(options?.startY&&options.startY+firstBlockHeight<=128)y=tableHeader(options.startY,true);else{options?.drawSignature?.();y=newPage()}
  for(const row of rows){const{values,rowHeight,graduated,failed,need}=row;if(y+rowHeight>128){options?.drawSignature?.();y=newPage()}let x=L;values.slice(0,-2).forEach((value,i)=>{cell(x,y,widths[i],rowHeight,value,false,i===2?"left":"center");x+=widths[i]});if(graduated)cell(x,y,53,rowHeight,failed,false,"center",true);else{cell(x,y,26.5,rowHeight,failed,false,"left",true);cell(x+26.5,y,26.5,rowHeight,need,false,"left",true)}y+=rowHeight}
  options?.drawSignature?.();return; } const orientation="portrait";doc.addPage("a4",orientation);const W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight(),L=10,R=W-10;doc.setTextColor(0);doc.setFont("FreeSerif","bold");doc.setFontSize(8);doc.text("Rajshahi University of Engineering & Technology",W/2,9,{align:"center"});doc.text("Department of Building Engineering & Construction Management",W/2,13,{align:"center"});doc.text(title+" - "+selection.academicYear+" Year "+selection.semester+" Semester Examination, "+selection.examYear,W/2,17,{align:"center"});doc.text("Non-OBE:",L,25);
 const base=[16,34],courseBase=courses.map(()=>10),tail=[12,14,12,14,12,20,20],available=R-L-base.reduce((x,y)=>x+y,0)-tail.reduce((x,y)=>x+y,0),scale=available/Math.max(1,courseBase.reduce((x,y)=>x+y,0)),courseWidths=courseBase.map(x=>x*scale),widths=[...base,...courseWidths,...tail];
 const cell=(x:number,y:number,w:number,h:number,text:string,bold=false,size=6.4,align:"center"|"left"="center")=>{doc.setLineWidth(.15);doc.rect(x,y,w,h);doc.setFont("FreeSerif",bold?"bold":"normal");doc.setFontSize(size);const lines=doc.splitTextToSize(text||"",Math.max(1,w-1.2))as string[],lh=size*.35,sy=y+(h-lines.length*lh)/2+lh*.78;lines.forEach((line,i)=>doc.text(line,align==="left"?x+.6:x+w/2,sy+i*lh,{align}))};
 let y=27,x=L;const headers=["Roll","Student",...courses.map(c=>c.code+" ("+Number(c.credit).toFixed(2)+")"),"SGP","Semester Credit","SGPA","Total Credit","CGPA",legacy?"Failed Subjects":"Status","Need to Register"];headers.forEach((h,i)=>{cell(x,y,widths[i],14,h,true,5.8);x+=widths[i]});y+=14;
 for(const s of cohort){const results=courses.map(c=>outcome(s,c)),earned=results.reduce((sum,v)=>sum+v.credit,0),quality=results.reduce((sum,v)=>sum+v.quality,0),totalCredit=s.earnedCredit+earned,totalQuality=s.gradePoints+quality,remarks=(()=>{const statuses=outstandingBeforeExam(s);results.forEach((result,index)=>{if(!result.registered)return;const courseId=courses[index].id;if(result.nonEligible)statuses.set(courseId,"need-register");else if(result.letter==="F"||result.letter==="W")statuses.set(courseId,"failed");else if(result.letter)statuses.delete(courseId)});const codes=(status:string)=>[...statuses].filter(([,value])=>value===status).map(([courseId])=>allCourses.find(c=>c.id===courseId)?.code).filter((code):code is string=>Boolean(code));return{failed:codes("failed"),need:codes("need-register")}})(),graduated=totalCredit>=graduationCreditForStudent(s),failed=graduated?completionStatus(totalCredit?totalQuality/totalCredit:0,legacy):remarks.failed.join(", "),need=graduated?"":remarks.need.join(", "),sgpa=earned?quality/earned:0,cgpa=totalCredit?totalQuality/totalCredit:0,courseValues=results.map(v=>!v.registered?(v.nonEligible?"-":""):v.letter);
  const values=[s.rollNo,s.name,...courseValues,quality.toFixed(2),earned.toFixed(2),roundSgpa(sgpa),totalCredit.toFixed(2),cgpa.toFixed(2),failed,need],height=Math.max(7,doc.splitTextToSize(failed,20).length*2.4+2,doc.splitTextToSize(need,20).length*2.4+2);if(y+height>H-12){doc.addPage("a4",orientation);y=12}x=L;values.slice(0,-2).forEach((v,i)=>{cell(x,y,widths[i],height,String(v),false,6.2,i===1?"left":"center");x+=widths[i]});if(graduated)cell(x,y,widths[widths.length-2]+widths[widths.length-1],height,failed,false,6.2,"center");else{cell(x,y,widths[widths.length-2],height,failed,false,6.2,"left");x+=widths[widths.length-2];cell(x,y,widths[widths.length-1],height,need,false,6.2,"left")}y+=height}
}
