"use client";
import { useEffect, useState } from "react";
type Entry={id:string;name:string;rollNo:string;series:string;promotedAt:string;cancelledAt?:string;blockedReason:string;before:{year:string;semester:string;placementExamYear?:string};after:{year:string;semester:string;placementExamYear?:string}};
export default function StudentPromotionPage(){
 const [records,setRecords]=useState<Entry[]>([]),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true);
 async function load(){const response=await fetch('/api/admin/student-promotion',{cache:'no-store'}),body=await response.json();if(!response.ok)throw Error(body.error||'Unable to load promotions');setRecords(body.records||[])}
 useEffect(()=>{fetch('/api/admin/student-promotion',{cache:'no-store'}).then(async response=>{const body=await response.json();if(!response.ok)throw Error(body.error||'Unable to load promotions');setRecords(body.records||[])}).catch(error=>setMessage(error.message)).finally(()=>setLoading(false))},[]);
 async function cancel(entry:Entry){if(!window.confirm(`Cancel the promotion of ${entry.name} (${entry.rollNo}) and restore ${entry.before.year} Year ${entry.before.semester}, exam ${entry.before.placementExamYear||''}?`))return;setBusy(entry.id);setMessage('');try{const response=await fetch('/api/admin/student-promotion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:entry.id})}),body=await response.json();if(!response.ok)throw Error(body.error);await load();setMessage('Promotion cancelled. The previous semester placement was restored.')}catch(error){setMessage(error instanceof Error?error.message:'Cancellation failed')}finally{setBusy('')}}
 const filtered=records.filter(entry=>`${entry.name} ${entry.rollNo} ${entry.series} ${entry.after.placementExamYear}`.toLowerCase().includes(query.toLowerCase())),batches=[...new Set(filtered.map(entry=>entry.series))].sort().reverse();
 return <section className="p-6"><h1 className="text-3xl font-bold">Student promotion</h1><p className="mt-2 text-slate-600">Trace batch promotions and cancel an unused promotion before course registration.</p><input aria-label="Search promotions" placeholder="Search name, roll, batch or exam year" className="my-5 w-full max-w-xl rounded border p-3" value={query} onChange={event=>setQuery(event.target.value)}/>{message&&<p role="status" className="mb-4 rounded bg-blue-50 p-3">{message}</p>}{loading?<p>Loading promotions...</p>:!batches.length?<p>No promotions found.</p>:batches.map(batch=><article key={batch} className="mb-6 overflow-hidden rounded-xl border bg-white shadow-sm"><h2 className="bg-[#082f57] p-4 text-xl font-bold text-white">Batch {batch}</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Student','From','Promoted to','Date','Status / Action'].map(label=><th key={label} className="border-b p-3">{label}</th>)}</tr></thead><tbody>{filtered.filter(entry=>entry.series===batch).sort((a,b)=>a.rollNo.localeCompare(b.rollNo,undefined,{numeric:true})||b.promotedAt.localeCompare(a.promotedAt)).map(entry=><tr key={entry.id}><td className="border-b p-3"><b>{entry.rollNo}</b><br/>{entry.name}</td><td className="border-b p-3">{entry.before.placementExamYear}<br/>{entry.before.year} Year {entry.before.semester}</td><td className="border-b p-3">{entry.after.placementExamYear}<br/>{entry.after.year} Year {entry.after.semester}</td><td className="border-b p-3">{new Date(entry.promotedAt).toLocaleString()}</td><td className="max-w-xs border-b p-3">{entry.blockedReason?<span>{entry.blockedReason}{entry.cancelledAt&&<> — {new Date(entry.cancelledAt).toLocaleString()}</>}</span>:<button disabled={Boolean(busy)} onClick={()=>void cancel(entry)} className="rounded bg-red-600 px-3 py-2 font-semibold text-white disabled:opacity-50">{busy===entry.id?'Cancelling...':'Cancel promotion'}</button>}</td></tr>)}</tbody></table></div></article>)}</section>;
}
