import {cookies} from "next/headers";
import {Prisma} from "@prisma/client";
import {NextResponse} from "next/server";
import {z} from "zod";
import {getPrisma} from "@/lib/prisma";
const SECTION="student-eligibility";
const row=z.object({examYear:z.string().regex(/^\d{4}$/),academicYear:z.enum(["1st","2nd","3rd","4th"]),semester:z.enum(["Odd","Even","Short Semester"]),courseId:z.string().min(1).max(100),courseCode:z.string().max(50),courseTitle:z.string().max(250),students:z.array(z.object({studentId:z.string().min(1).max(100),eligible:z.boolean()})).max(1000),updatedAt:z.string().datetime()});const rows=z.array(row).max(5000);
async function db(){const id=(await cookies()).get("becm-portal-account")?.value;const prisma=getPrisma();if(!id||!prisma)return null;const teacher=await prisma.portalAccount.findFirst({where:{id,role:"teacher",active:true},select:{id:true}});return teacher?prisma:null}
async function load(prisma:NonNullable<ReturnType<typeof getPrisma>>){await prisma.$executeRaw(Prisma.sql`INSERT INTO "ResultSectionStore" ("section","data","updatedAt") VALUES (${SECTION},'[]'::jsonb,NOW()) ON CONFLICT ("section") DO NOTHING`);const found=await prisma.$queryRaw<Array<{data:Prisma.JsonValue}>>(Prisma.sql`SELECT "data" FROM "ResultSectionStore" WHERE "section"=${SECTION}`);return rows.parse(found[0]?.data??[])}
export async function GET(){const prisma=await db();if(!prisma)return NextResponse.json({error:"Teacher login required"},{status:401});try{return NextResponse.json({records:await load(prisma)},{headers:{"Cache-Control":"no-store"}})}catch(e){console.error(e);return NextResponse.json({error:"Unable to load eligibility"},{status:503})}}
export async function PUT(request:Request){const prisma=await db();if(!prisma)return NextResponse.json({error:"Teacher login required"},{status:401});const parsed=row.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Invalid eligibility"},{status:400});try{const current=await load(prisma);const index=current.findIndex(item=>item.examYear===parsed.data.examYear&&item.academicYear===parsed.data.academicYear&&item.semester===parsed.data.semester&&item.courseId===parsed.data.courseId);if(index<0)current.push(parsed.data);else current[index]=parsed.data;const serialized=JSON.stringify(current);await prisma.$executeRaw(Prisma.sql`UPDATE "ResultSectionStore" SET "data"=CAST(${serialized} AS jsonb),"updatedAt"=NOW() WHERE "section"=${SECTION}`);return NextResponse.json({records:current})}catch(e){console.error(e);return NextResponse.json({error:"Unable to save eligibility"},{status:503})}}
